#!/bin/bash
#set -x
cd ${10}$4

if [ $7 != - ]; then
    # TODO: configurations
    echo "Cannot elaborate configuration" > ${10}$2$1.so
    exit 1
else
    nvc --work $3 -e $5 &> ${10}$2$1.so
    nvc --work $3 -r $5 --stop-time=$9$8 &>> ${10}$2$1.so
fi
