# Generated automatically, do not edit.
EXTRA_DIST += \
	test/bounds/aggregate.vhd \
	test/bounds/bounds2.vhd \
	test/bounds/bounds.vhd \
	test/bounds/case2.vhd \
	test/bounds/case3.vhd \
	test/bounds/case4.vhd \
	test/bounds/case5.vhd \
	test/bounds/case.vhd \
	test/bounds/cons1.vhd \
	test/bounds/driver1.vhd \
	test/bounds/initial.vhd \
	test/bounds/issue1021.vhd \
	test/bounds/issue1040.vhd \
	test/bounds/issue1091.vhd \
	test/bounds/issue150.vhd \
	test/bounds/issue200.vhd \
	test/bounds/issue208.vhd \
	test/bounds/issue247.vhd \
	test/bounds/issue269.vhd \
	test/bounds/issue307b.vhd \
	test/bounds/issue356.vhd \
	test/bounds/issue36.vhd \
	test/bounds/issue477a.vhd \
	test/bounds/issue477b.vhd \
	test/bounds/issue54.vhd \
	test/bounds/issue617.vhd \
	test/bounds/issue734.vhd \
	test/bounds/issue800.vhd \
	test/bounds/issue806.vhd \
	test/bounds/issue819.vhd \
	test/bounds/issue863.vhd \
	test/bounds/issue951.vhd \
	test/bounds/issue966.vhd \
	test/bounds/issue975.vhd \
	test/bounds/issue98.vhd \
	test/bounds/issue99.vhd \
	test/bounds/nullrange.vhd \
	test/bounds/osvvm1.vhd \
	test/bounds/range1.vhd \
	test/bounds/subtype.vhd \
	test/bounds/tc1147.vhd \
	test/charset/iso8859-1.vhd \
	test/charset/strings.vhd \
	test/charset/utf8.vhd \
	test/diag/diag1.vhd \
	test/driver/issue930.vhd \
	test/driver/issue953.vhd \
	test/driver/sanity1.vhd \
	test/driver/sanity2.vhd \
	test/driver/unique1.vhd \
	test/driver/unique2.vhd \
	test/driver/unique3.vhd \
	test/dump/psl1.vhd \
	test/dump/vhdl1.vhd \
	test/dump/vhdl2.vhd \
	test/dump/vhdl3.vhd \
	test/dump/vhdl4.vhd \
	test/dump/vhdl5.vhd \
	test/dump/vhdl6.vhd \
	test/dump/vhdl7.vhd \
	test/dump/vlog1.v \
	test/elab/assert7.vhd \
	test/elab/block1.vhd \
	test/elab/block2.vhd \
	test/elab/body1.vhd \
	test/elab/bounds10.vhd \
	test/elab/bounds11.vhd \
	test/elab/bounds14.vhd \
	test/elab/bounds21.vhd \
	test/elab/bounds40.vhd \
	test/elab/bounds41.vhd \
	test/elab/bounds42.vhd \
	test/elab/bounds7.vhd \
	test/elab/comp2.vhd \
	test/elab/comp3.vhd \
	test/elab/comp4.vhd \
	test/elab/comp.vhd \
	test/elab/config1.vhd \
	test/elab/const1.vhd \
	test/elab/copy1.vhd \
	test/elab/elab1.vhd \
	test/elab/elab2.vhd \
	test/elab/elab3.vhd \
	test/elab/elab4.vhd \
	test/elab/ename1.vhd \
	test/elab/ename2.vhd \
	test/elab/ename3.vhd \
	test/elab/eval1.vhd \
	test/elab/fold1.vhd \
	test/elab/fold2.vhd \
	test/elab/gbounds.vhd \
	test/elab/genagg.vhd \
	test/elab/generate1.vhd \
	test/elab/generic1.vhd \
	test/elab/generic2.vhd \
	test/elab/generic3.vhd \
	test/elab/genpack1.vhd \
	test/elab/genpack2.vhd \
	test/elab/genpack3.vhd \
	test/elab/genpack4.vhd \
	test/elab/genpack5.vhd \
	test/elab/gentype1.vhd \
	test/elab/ifgen.vhd \
	test/elab/issue1012.vhd \
	test/elab/issue1017.vhd \
	test/elab/issue153.vhd \
	test/elab/issue157.vhd \
	test/elab/issue159.vhd \
	test/elab/issue175.vhd \
	test/elab/issue17.vhd \
	test/elab/issue184.vhd \
	test/elab/issue19.vhd \
	test/elab/issue228.vhd \
	test/elab/issue232.vhd \
	test/elab/issue251.vhd \
	test/elab/issue305.vhd \
	test/elab/issue307.vhd \
	test/elab/issue315.vhd \
	test/elab/issue325.vhd \
	test/elab/issue328.vhd \
	test/elab/issue330.vhd \
	test/elab/issue336.vhd \
	test/elab/issue373.vhd \
	test/elab/issue374.vhd \
	test/elab/issue404.vhd \
	test/elab/issue435.vhd \
	test/elab/issue442.vhd \
	test/elab/issue448.vhd \
	test/elab/issue459.vhd \
	test/elab/issue514.vhd \
	test/elab/issue518.vhd \
	test/elab/issue539.vhd \
	test/elab/issue669.vhd \
	test/elab/issue707.vhd \
	test/elab/issue759.vhd \
	test/elab/issue855.vhd \
	test/elab/issue860.vhd \
	test/elab/issue864.vhd \
	test/elab/issue93.vhd \
	test/elab/issue969.vhd \
	test/elab/jcore1.vhd \
	test/elab/jcore2.vhd \
	test/elab/libbind2.vhd \
	test/elab/libbind3.vhd \
	test/elab/libbind.vhd \
	test/elab/link1.vhd \
	test/elab/mixed1.v \
	test/elab/mixed1.vhd \
	test/elab/neorv1.vhd \
	test/elab/null1.vhd \
	test/elab/open2.vhd \
	test/elab/open3.vhd \
	test/elab/opencase.vhd \
	test/elab/openinout.vhd \
	test/elab/open.vhd \
	test/elab/record.vhd \
	test/elab/tc2881.vhd \
	test/elab/tc3138.vhd \
	test/elab/tc846.vhd \
	test/elab/toplevel2.vhd \
	test/elab/toplevel3.vhd \
	test/elab/toplevel4.vhd \
	test/elab/toplevel5.vhd \
	test/elab/view1.vhd \
	test/elab/vlog1.v \
	test/eopt/alias1.vhd \
	test/eopt/array3.vhd \
	test/eopt/arrayref1.vhd \
	test/eopt/arrayref2.vhd \
	test/eopt/arrayref3.vhd \
	test/eopt/arrayref4.vhd \
	test/eopt/buffer1.vhd \
	test/eopt/issue250.vhd \
	test/eopt/issue371.vhd \
	test/eopt/issue427.vhd \
	test/eopt/issue72.vhd \
	test/eopt/issue73.vhd \
	test/eopt/issue95.vhd \
	test/eopt/jcore2.vhd \
	test/eopt/jcore4.vhd \
	test/eopt/map1.vhd \
	test/eopt/map2.vhd \
	test/eopt/nonconst1.vhd \
	test/eopt/partial1.vhd \
	test/eopt/pcall1.vhd \
	test/eopt/pcall2.vhd \
	test/eopt/ram1.vhd \
	test/eopt/recref1.vhd \
	test/eopt/recref2.vhd \
	test/eopt/slice1.vhd \
	test/eopt/slice2.vhd \
	test/eopt/source1.vhd \
	test/expect.vhd \
	test/issue746.sh \
	test/jit/access1.vhd \
	test/jit/add1.vhd \
	test/jit/arith1.vhd \
	test/jit/array1.vhd \
	test/jit/assert1.vhd \
	test/jit/case1.vhd \
	test/jit/context1.vhd \
	test/jit/fact.vhd \
	test/jit/ieeewarn.vhd \
	test/jit/issue496.vhd \
	test/jit/issue575.vhd \
	test/jit/layout.vhd \
	test/jit/overflow.vhd \
	test/jit/packsignal.vhd \
	test/jit/proc1.vhd \
	test/jit/process1.vhd \
	test/jit/prot1.vhd \
	test/jit/range1.vhd \
	test/jit/real1.vhd \
	test/jit/record1.vhd \
	test/jit/record2.vhd \
	test/jit/record3.vhd \
	test/jit/record4.vhd \
	test/jit/relop1.vhd \
	test/jit/sum.vhd \
	test/jit/tlab1.vhd \
	test/jit/trace1.vhd \
	test/jit/unreachable.vhd \
	test/jit/value1.vhd \
	test/lower/access1.vhd \
	test/lower/access2.vhd \
	test/lower/access_bug.vhd \
	test/lower/alias1.vhd \
	test/lower/arith1.vhd \
	test/lower/array1.vhd \
	test/lower/array2.vhd \
	test/lower/arrayop1.vhd \
	test/lower/assert1.vhd \
	test/lower/assert2.vhd \
	test/lower/assign1.vhd \
	test/lower/assign2.vhd \
	test/lower/assign3.vhd \
	test/lower/attr1.vhd \
	test/lower/attr2.vhd \
	test/lower/bigarray.vhd \
	test/lower/bounds1.vhd \
	test/lower/bounds2.vhd \
	test/lower/case1.vhd \
	test/lower/case2.vhd \
	test/lower/choice1.vhd \
	test/lower/closefile.vhd \
	test/lower/concat.vhd \
	test/lower/cond1.vhd \
	test/lower/cond2.vhd \
	test/lower/const1.vhd \
	test/lower/const2.vhd \
	test/lower/const3.vhd \
	test/lower/conv1.vhd \
	test/lower/copy1.vhd \
	test/lower/cover.vhd \
	test/lower/dealloc.vhd \
	test/lower/directmap2.vhd \
	test/lower/directmap3.vhd \
	test/lower/directmap5.vhd \
	test/lower/directmap6.vhd \
	test/lower/directmap.vhd \
	test/lower/driver1.vhd \
	test/lower/event1.vhd \
	test/lower/extern1.vhd \
	test/lower/func1.vhd \
	test/lower/func5.vhd \
	test/lower/funcif.vhd \
	test/lower/genpack1.vhd \
	test/lower/hintbug.vhd \
	test/lower/iffold.vhd \
	test/lower/incomplete.vhd \
	test/lower/instance1.vhd \
	test/lower/issue1029.vhd \
	test/lower/issue1080.vhd \
	test/lower/issue116.vhd \
	test/lower/issue122.vhd \
	test/lower/issue124.vhd \
	test/lower/issue125.vhd \
	test/lower/issue134.vhd \
	test/lower/issue135.vhd \
	test/lower/issue136.vhd \
	test/lower/issue149.vhd \
	test/lower/issue158.vhd \
	test/lower/issue164.vhd \
	test/lower/issue167.vhd \
	test/lower/issue181.vhd \
	test/lower/issue203.vhd \
	test/lower/issue215.vhd \
	test/lower/issue303.vhd \
	test/lower/issue324.vhd \
	test/lower/issue333.vhd \
	test/lower/issue338b.vhd \
	test/lower/issue338.vhd \
	test/lower/issue347.vhd \
	test/lower/issue351.vhd \
	test/lower/issue357.vhd \
	test/lower/issue389.vhd \
	test/lower/issue426.vhd \
	test/lower/issue444.vhd \
	test/lower/issue462.vhd \
	test/lower/issue476.vhd \
	test/lower/issue478.vhd \
	test/lower/issue582.vhd \
	test/lower/issue591.vhd \
	test/lower/issue613.vhd \
	test/lower/issue662.vhd \
	test/lower/issue725.vhd \
	test/lower/issue756.vhd \
	test/lower/issue768.vhd \
	test/lower/issue791.vhd \
	test/lower/issue837.vhd \
	test/lower/issue844.vhd \
	test/lower/issue859.vhd \
	test/lower/issue934.vhd \
	test/lower/issue94.vhd \
	test/lower/issue972.vhd \
	test/lower/link1.vhd \
	test/lower/loop1.vhd \
	test/lower/loop2.vhd \
	test/lower/memset.vhd \
	test/lower/mixed2.v \
	test/lower/mixed2.vhd \
	test/lower/mulphys.vhd \
	test/lower/nest1.vhd \
	test/lower/nullarray.vhd \
	test/lower/osvvm2.vhd \
	test/lower/osvvm3.vhd \
	test/lower/pack1.vhd \
	test/lower/predef1.vhd \
	test/lower/proc1.vhd \
	test/lower/proc3.vhd \
	test/lower/proc4.vhd \
	test/lower/proc7.vhd \
	test/lower/protpcall.vhd \
	test/lower/protupref.vhd \
	test/lower/real1.vhd \
	test/lower/record1.vhd \
	test/lower/record2.vhd \
	test/lower/record6.vhd \
	test/lower/recsignal1.vhd \
	test/lower/resfn1.vhd \
	test/lower/sig2var.vhd \
	test/lower/signal11.vhd \
	test/lower/signal1.vhd \
	test/lower/signal2.vhd \
	test/lower/signal4.vhd \
	test/lower/signal5.vhd \
	test/lower/sigvar.vhd \
	test/lower/slice1.vhd \
	test/lower/staticwait.vhd \
	test/lower/subtype1.vhd \
	test/lower/subtype2.vhd \
	test/lower/sum.vhd \
	test/lower/synopsys1.vhd \
	test/lower/tag.vhd \
	test/lower/thunk.vhd \
	test/lower/tounsigned.vhd \
	test/lower/transfer1.vhd \
	test/lower/trigger1.vhd \
	test/lower/vital1.vhd \
	test/lower/vital2.vhd \
	test/lower/vunit1.vhd \
	test/lower/vunit2.vhd \
	test/lower/vunit3.vhd \
	test/lower/vunit4.vhd \
	test/lower/vunit5.vhd \
	test/lower/wait1.vhd \
	test/lower/wait2.vhd \
	test/lower/while1.vhd \
	test/misc/bufr_test.vhd \
	test/misc/elide.vhd \
	test/misc/kcuart.vhd \
	test/misc/lut4_test.vhd \
	test/misc/ramb_test.vhd \
	test/model/alias1.vhd \
	test/model/basic1.vhd \
	test/model/event1.vhd \
	test/model/fast1.vhd \
	test/model/fast2.vhd \
	test/model/index1.vhd \
	test/model/pending1.vhd \
	test/model/stateless1.vhd \
	test/parse/access.vhd \
	test/parse/aggregate2.vhd \
	test/parse/aggregate.vhd \
	test/parse/alias2.vhd \
	test/parse/alias3.vhd \
	test/parse/alias4.vhd \
	test/parse/alias5.vhd \
	test/parse/alias.vhd \
	test/parse/arch.vhd \
	test/parse/array.vhd \
	test/parse/attr.vhd \
	test/parse/badprimary.vhd \
	test/parse/based.vhd \
	test/parse/basic_identifier.vhd \
	test/parse/bitstring.vhd \
	test/parse/block.vhd \
	test/parse/comp.vhd \
	test/parse/concat.vhd \
	test/parse/conc.vhd \
	test/parse/cond1.vhd \
	test/parse/config.vhd \
	test/parse/context.vhd \
	test/parse/defer1.vhd \
	test/parse/empty.vhd \
	test/parse/entity.vhd \
	test/parse/enum.vhd \
	test/parse/error10.vhd \
	test/parse/error11.vhd \
	test/parse/error12.vhd \
	test/parse/error13.vhd \
	test/parse/error2.vhd \
	test/parse/error3.vhd \
	test/parse/error4.vhd \
	test/parse/error5.vhd \
	test/parse/error6.vhd \
	test/parse/error7.vhd \
	test/parse/error8.vhd \
	test/parse/error9.vhd \
	test/parse/error.vhd \
	test/parse/explicit.vhd \
	test/parse/expr.vhd \
	test/parse/extended.vhd \
	test/parse/external.vhd \
	test/parse/func.vhd \
	test/parse/generate.vhd \
	test/parse/gensub.vhd \
	test/parse/group.vhd \
	test/parse/guarded.vhd \
	test/parse/hang.vhd \
	test/parse/homograph.vhd \
	test/parse/implicit.vhd \
	test/parse/instance.vhd \
	test/parse/interface.vhd \
	test/parse/ir1045.vhd \
	test/parse/issue1038.vhd \
	test/parse/issue1055.vhd \
	test/parse/issue1090.vhd \
	test/parse/issue1091b.vhd \
	test/parse/issue1091.vhd \
	test/parse/issue1096.vhd \
	test/parse/issue1124.vhd \
	test/parse/issue1129.vhd \
	test/parse/issue1138.vhd \
	test/parse/issue205.vhd \
	test/parse/issue222.vhd \
	test/parse/issue360.vhd \
	test/parse/issue367.vhd \
	test/parse/issue369.vhd \
	test/parse/issue388.vhd \
	test/parse/issue416.vhd \
	test/parse/issue443.vhd \
	test/parse/issue457.vhd \
	test/parse/issue458.vhd \
	test/parse/issue461.vhd \
	test/parse/issue464.vhd \
	test/parse/issue468.vhd \
	test/parse/issue479.vhd \
	test/parse/issue532.vhd \
	test/parse/issue539.vhd \
	test/parse/issue541.vhd \
	test/parse/issue568.vhd \
	test/parse/issue569.vhd \
	test/parse/issue580.vhd \
	test/parse/issue604.vhd \
	test/parse/issue644.vhd \
	test/parse/issue653.vhd \
	test/parse/issue654.vhd \
	test/parse/issue663.vhd \
	test/parse/issue686.vhd \
	test/parse/issue687.vhd \
	test/parse/issue688.vhd \
	test/parse/issue701.vhd \
	test/parse/issue708.vhd \
	test/parse/issue727.vhd \
	test/parse/issue751.vhd \
	test/parse/issue753.vhd \
	test/parse/issue760.vhd \
	test/parse/issue761.vhd \
	test/parse/issue776.vhd \
	test/parse/issue783.vhd \
	test/parse/issue789.vhd \
	test/parse/issue792.vhd \
	test/parse/issue793.vhd \
	test/parse/issue802.vhd \
	test/parse/issue805.vhd \
	test/parse/issue837.vhd \
	test/parse/issue845.vhd \
	test/parse/issue848.vhd \
	test/parse/issue870.vhd \
	test/parse/issue875.vhd \
	test/parse/issue889.vhd \
	test/parse/issue892.vhd \
	test/parse/issue893.vhd \
	test/parse/issue905.vhd \
	test/parse/issue917.vhd \
	test/parse/issue942.vhd \
	test/parse/issue952.vhd \
	test/parse/issue956.vhd \
	test/parse/issue961.vhd \
	test/parse/issue977.vhd \
	test/parse/issue991.vhd \
	test/parse/lcs2016_i03.vhd \
	test/parse/literal.vhd \
	test/parse/loc.vhd \
	test/parse/names2.vhd \
	test/parse/names3.vhd \
	test/parse/names.vhd \
	test/parse/osvvm6.vhd \
	test/parse/osvvm7.vhd \
	test/parse/package.vhd \
	test/parse/pkgindecl.vhd \
	test/parse/procedure.vhd \
	test/parse/process.vhd \
	test/parse/protected2.vhd \
	test/parse/protected3.vhd \
	test/parse/protected.vhd \
	test/parse/qual.vhd \
	test/parse/range1.vhd \
	test/parse/seq.vhd \
	test/parse/slow1.vhd \
	test/parse/spec.vhd \
	test/parse/subtype2008.vhd \
	test/parse/synth.vhd \
	test/parse/tc1012.vhd \
	test/parse/types.vhd \
	test/parse/typo.vhd \
	test/parse/uvvm1.vhd \
	test/parse/uvvm2.vhd \
	test/parse/vests1.vhd \
	test/parse/vests2.vhd \
	test/parse/vests3.vhd \
	test/parse/vests4.vhd \
	test/parse/vests5.vhd \
	test/parse/vhdl2008.vhd \
	test/parse/vhdl2019.vhd \
	test/parse/visibility10.vhd \
	test/parse/visibility11.vhd \
	test/parse/visibility12.vhd \
	test/parse/visibility1.vhd \
	test/parse/visibility2.vhd \
	test/parse/visibility3.vhd \
	test/parse/visibility4.vhd \
	test/parse/visibility5.vhd \
	test/parse/visibility6.vhd \
	test/parse/visibility7.vhd \
	test/parse/visibility8.vhd \
	test/parse/visibility9.vhd \
	test/parse/vunit10.vhd \
	test/parse/vunit5.vhd \
	test/parse/vunit6.vhd \
	test/parse/vunit7.vhd \
	test/parse/vunit8.vhd \
	test/parse/vunit9.vhd \
	test/perf/alloc.vhd \
	test/perf/arraycase.vhd \
	test/perf/bigcase.vhd \
	test/perf/bigram.vhd \
	test/perf/binarytrees.vhd \
	test/perf/dyn_agg.vhd \
	test/perf/ename.vhd \
	test/perf/grind.vhd \
	test/perf/math_real.vhd \
	test/perf/numeric_std.vhd \
	test/perf/simple.vhd \
	test/perf/std_logic.vhd \
	test/perf/synopsys.vhd \
	test/perf/textio.vhd \
	test/perf/toggle_cov.vhd \
	test/perf/value.vhd \
	test/perf/vital.vhd \
	test/psl/clock1.vhd \
	test/psl/issue1001.vhd \
	test/psl/issue910.vhd \
	test/psl/parse1.vhd \
	test/psl/parse2.vhd \
	test/psl/parse3.vhd \
	test/psl/parse4.vhd \
	test/psl/parse5.vhd \
	test/psl/sem1.vhd \
	test/questa.sh \
	test/regress/access10.vhd \
	test/regress/access11.vhd \
	test/regress/access12.vhd \
	test/regress/access1.vhd \
	test/regress/access2.vhd \
	test/regress/access3.vhd \
	test/regress/access4.vhd \
	test/regress/access5.vhd \
	test/regress/access6.vhd \
	test/regress/access7.vhd \
	test/regress/access8.vhd \
	test/regress/access9.vhd \
	test/regress/agg10.vhd \
	test/regress/agg1.vhd \
	test/regress/agg2.vhd \
	test/regress/agg3.vhd \
	test/regress/agg4.vhd \
	test/regress/agg5.vhd \
	test/regress/agg6.vhd \
	test/regress/agg7.vhd \
	test/regress/agg8.vhd \
	test/regress/agg9.vhd \
	test/regress/alias10.vhd \
	test/regress/alias11.vhd \
	test/regress/alias12.vhd \
	test/regress/alias13.vhd \
	test/regress/alias14.vhd \
	test/regress/alias15.vhd \
	test/regress/alias1.vhd \
	test/regress/alias2.vhd \
	test/regress/alias3.vhd \
	test/regress/alias4.vhd \
	test/regress/alias5.vhd \
	test/regress/alias6.vhd \
	test/regress/alias7.vhd \
	test/regress/alias8.vhd \
	test/regress/alias9.vhd \
	test/regress/arith1.vhd \
	test/regress/arith2.vhd \
	test/regress/arith3.vhd \
	test/regress/arith4.vhd \
	test/regress/arith5.vhd \
	test/regress/array10.vhd \
	test/regress/array11.vhd \
	test/regress/array12.vhd \
	test/regress/array13.vhd \
	test/regress/array14.vhd \
	test/regress/array15.vhd \
	test/regress/array16.vhd \
	test/regress/array17.vhd \
	test/regress/array18.vhd \
	test/regress/array19.vhd \
	test/regress/array1.vhd \
	test/regress/array2.vhd \
	test/regress/array3.vhd \
	test/regress/array4.vhd \
	test/regress/array5.vhd \
	test/regress/array6.vhd \
	test/regress/array7.vhd \
	test/regress/array8.vhd \
	test/regress/array9.vhd \
	test/regress/assert10.vhd \
	test/regress/assert11.vhd \
	test/regress/assert12.vhd \
	test/regress/assert1.vhd \
	test/regress/assert2.vhd \
	test/regress/assert3.vhd \
	test/regress/assert4.vhd \
	test/regress/assert5.vhd \
	test/regress/assert6.vhd \
	test/regress/assert7.vhd \
	test/regress/assert8.vhd \
	test/regress/assert9.vhd \
	test/regress/assign1.vhd \
	test/regress/assign2.vhd \
	test/regress/assign3.vhd \
	test/regress/assign4.vhd \
	test/regress/assign5.vhd \
	test/regress/assign6.vhd \
	test/regress/assign7.vhd \
	test/regress/assign8.vhd \
	test/regress/assign9.vhd \
	test/regress/attr10.vhd \
	test/regress/attr11.vhd \
	test/regress/attr12.vhd \
	test/regress/attr13.vhd \
	test/regress/attr14.vhd \
	test/regress/attr15.vhd \
	test/regress/attr16.vhd \
	test/regress/attr17.vhd \
	test/regress/attr18.vhd \
	test/regress/attr19.vhd \
	test/regress/attr1.vhd \
	test/regress/attr20.vhd \
	test/regress/attr21.vhd \
	test/regress/attr2.vhd \
	test/regress/attr3.vhd \
	test/regress/attr4.vhd \
	test/regress/attr5.vhd \
	test/regress/attr6.vhd \
	test/regress/attr7.vhd \
	test/regress/attr8.vhd \
	test/regress/bitstr1.vhd \
	test/regress/bitvec.vhd \
	test/regress/block1.vhd \
	test/regress/block2.vhd \
	test/regress/bounds10.vhd \
	test/regress/bounds11.vhd \
	test/regress/bounds12.vhd \
	test/regress/bounds13.vhd \
	test/regress/bounds15.vhd \
	test/regress/bounds16.vhd \
	test/regress/bounds17.vhd \
	test/regress/bounds18.vhd \
	test/regress/bounds19.vhd \
	test/regress/bounds1.vhd \
	test/regress/bounds20.vhd \
	test/regress/bounds22.vhd \
	test/regress/bounds23.vhd \
	test/regress/bounds24.vhd \
	test/regress/bounds25.vhd \
	test/regress/bounds26.vhd \
	test/regress/bounds27.vhd \
	test/regress/bounds28.vhd \
	test/regress/bounds29.vhd \
	test/regress/bounds2.vhd \
	test/regress/bounds30.vhd \
	test/regress/bounds31.vhd \
	test/regress/bounds32.vhd \
	test/regress/bounds33.vhd \
	test/regress/bounds34.vhd \
	test/regress/bounds35.vhd \
	test/regress/bounds36.vhd \
	test/regress/bounds37.vhd \
	test/regress/bounds38.vhd \
	test/regress/bounds39.vhd \
	test/regress/bounds3.vhd \
	test/regress/bounds40.vhd \
	test/regress/bounds41.vhd \
	test/regress/bounds42.vhd \
	test/regress/bounds43.vhd \
	test/regress/bounds44.vhd \
	test/regress/bounds45.vhd \
	test/regress/bounds4.vhd \
	test/regress/bounds5.vhd \
	test/regress/bounds6.vhd \
	test/regress/bounds7.vhd \
	test/regress/bounds8.vhd \
	test/regress/bounds9.vhd \
	test/regress/buffer1.vhd \
	test/regress/case10.vhd \
	test/regress/case11.vhd \
	test/regress/case12.vhd \
	test/regress/case13.vhd \
	test/regress/case14.vhd \
	test/regress/case15.vhd \
	test/regress/case1.vhd \
	test/regress/case2.vhd \
	test/regress/case3.vhd \
	test/regress/case4.vhd \
	test/regress/case5.vhd \
	test/regress/case6.vhd \
	test/regress/case7.vhd \
	test/regress/case8.vhd \
	test/regress/case9.vhd \
	test/regress/cmdline10.sh \
	test/regress/cmdline11.sh \
	test/regress/cmdline12.sh \
	test/regress/cmdline13.sh \
	test/regress/cmdline1.sh \
	test/regress/cmdline2.sh \
	test/regress/cmdline3.sh \
	test/regress/cmdline4.sh \
	test/regress/cmdline5.sh \
	test/regress/cmdline6.sh \
	test/regress/cmdline7.sh \
	test/regress/cmdline8.sh \
	test/regress/cmdline9.sh \
	test/regress/comp1.vhd \
	test/regress/comp2.vhd \
	test/regress/comp3.vhd \
	test/regress/concat1.vhd \
	test/regress/concat2.vhd \
	test/regress/concat3.vhd \
	test/regress/concat4.vhd \
	test/regress/concat5.vhd \
	test/regress/concat6.vhd \
	test/regress/concat7.vhd \
	test/regress/cond1.vhd \
	test/regress/cond2.vhd \
	test/regress/cond3.vhd \
	test/regress/cond4.vhd \
	test/regress/cond5.vhd \
	test/regress/cond6.vhd \
	test/regress/conf1.vhd \
	test/regress/conf2.vhd \
	test/regress/conf3.vhd \
	test/regress/conf4.vhd \
	test/regress/conf5.vhd \
	test/regress/const10.vhd \
	test/regress/const1.vhd \
	test/regress/const2.vhd \
	test/regress/const3.vhd \
	test/regress/const4.vhd \
	test/regress/const5.vhd \
	test/regress/const6.vhd \
	test/regress/const7.vhd \
	test/regress/const8.vhd \
	test/regress/const9.vhd \
	test/regress/conv10.vhd \
	test/regress/conv11.vhd \
	test/regress/conv12.vhd \
	test/regress/conv13.vhd \
	test/regress/conv14.vhd \
	test/regress/conv15.vhd \
	test/regress/conv16.vhd \
	test/regress/conv17.vhd \
	test/regress/conv18.vhd \
	test/regress/conv1.vhd \
	test/regress/conv2.vhd \
	test/regress/conv3.vhd \
	test/regress/conv4.vhd \
	test/regress/conv5.vhd \
	test/regress/conv6.vhd \
	test/regress/conv7.vhd \
	test/regress/conv8.vhd \
	test/regress/conv9.vhd \
	test/regress/counter.vhd \
	test/regress/cover10.sh \
	test/regress/cover10.vhd \
	test/regress/cover11.sh \
	test/regress/cover11.vhd \
	test/regress/cover12.sh \
	test/regress/cover12.vhd \
	test/regress/cover13.sh \
	test/regress/cover13.vhd \
	test/regress/cover14.sh \
	test/regress/cover14.vhd \
	test/regress/cover15.vhd \
	test/regress/cover16.vhd \
	test/regress/cover17.vhd \
	test/regress/cover18.sh \
	test/regress/cover18.vhd \
	test/regress/cover19.sh \
	test/regress/cover19.vhd \
	test/regress/cover1.vhd \
	test/regress/cover20.sh \
	test/regress/cover20.vhd \
	test/regress/cover21.sh \
	test/regress/cover21.vhd \
	test/regress/cover22.sh \
	test/regress/cover22.vhd \
	test/regress/cover23.sh \
	test/regress/cover23.vhd \
	test/regress/cover24.sh \
	test/regress/cover24.vhd \
	test/regress/cover25.vhd \
	test/regress/cover2.vhd \
	test/regress/cover3.vhd \
	test/regress/cover4.vhd \
	test/regress/cover5.sh \
	test/regress/cover5.vhd \
	test/regress/cover6.sh \
	test/regress/cover6.vhd \
	test/regress/cover7.vhd \
	test/regress/cover8.vhd \
	test/regress/cover9.sh \
	test/regress/cover9.vhd \
	test/regress/data/cover10_ef1.txt \
	test/regress/data/cover11_ef1.txt \
	test/regress/data/cover13_spec.txt \
	test/regress/data/cover14_ef1.txt \
	test/regress/data/cover18_ef.txt \
	test/regress/data/cover19_spec.txt \
	test/regress/data/cover23_ef.txt \
	test/regress/data/cover9_ef1.txt \
	test/regress/data/cover9_ef2.txt \
	test/regress/data/cover9_ef3.txt \
	test/regress/data/cover9_ef5.txt \
	test/regress/debug1.vhd \
	test/regress/debug2.vhd \
	test/regress/debug3.vhd \
	test/regress/default1.vhd \
	test/regress/default2.vhd \
	test/regress/delay1.vhd \
	test/regress/delay2.vhd \
	test/regress/delay3.vhd \
	test/regress/driver10.vhd \
	test/regress/driver11.vhd \
	test/regress/driver12.vhd \
	test/regress/driver13.vhd \
	test/regress/driver14.vhd \
	test/regress/driver15.vhd \
	test/regress/driver16.vhd \
	test/regress/driver17.vhd \
	test/regress/driver18.vhd \
	test/regress/driver19.vhd \
	test/regress/driver1.vhd \
	test/regress/driver20.vhd \
	test/regress/driver21.vhd \
	test/regress/driver22.vhd \
	test/regress/driver23.vhd \
	test/regress/driver2.vhd \
	test/regress/driver3.vhd \
	test/regress/driver4.vhd \
	test/regress/driver5.vhd \
	test/regress/driver6.vhd \
	test/regress/driver7.vhd \
	test/regress/driver8.vhd \
	test/regress/driver9.vhd \
	test/regress/elab10.vhd \
	test/regress/elab11.vhd \
	test/regress/elab12.vhd \
	test/regress/elab13.vhd \
	test/regress/elab14.vhd \
	test/regress/elab15.vhd \
	test/regress/elab16.vhd \
	test/regress/elab17.vhd \
	test/regress/elab18.vhd \
	test/regress/elab19.vhd \
	test/regress/elab1.vhd \
	test/regress/elab20.vhd \
	test/regress/elab21.vhd \
	test/regress/elab22.vhd \
	test/regress/elab23.vhd \
	test/regress/elab24.vhd \
	test/regress/elab25.vhd \
	test/regress/elab26.vhd \
	test/regress/elab27.vhd \
	test/regress/elab28.vhd \
	test/regress/elab29.vhd \
	test/regress/elab2.vhd \
	test/regress/elab30.vhd \
	test/regress/elab31.vhd \
	test/regress/elab32.vhd \
	test/regress/elab33.vhd \
	test/regress/elab34.vhd \
	test/regress/elab35.vhd \
	test/regress/elab36.vhd \
	test/regress/elab37.vhd \
	test/regress/elab38.vhd \
	test/regress/elab39.sh \
	test/regress/elab3.vhd \
	test/regress/elab40.vhd \
	test/regress/elab4.vhd \
	test/regress/elab5.vhd \
	test/regress/elab6.vhd \
	test/regress/elab7.vhd \
	test/regress/elab8.vhd \
	test/regress/elab9.vhd \
	test/regress/ename10.vhd \
	test/regress/ename11.vhd \
	test/regress/ename12.vhd \
	test/regress/ename13.vhd \
	test/regress/ename14.vhd \
	test/regress/ename15.vhd \
	test/regress/ename16.vhd \
	test/regress/ename17.vhd \
	test/regress/ename1.vhd \
	test/regress/ename2.vhd \
	test/regress/ename3.vhd \
	test/regress/ename4.vhd \
	test/regress/ename5.vhd \
	test/regress/ename6.vhd \
	test/regress/ename7.vhd \
	test/regress/ename8.vhd \
	test/regress/ename9.vhd \
	test/regress/fact.vhd \
	test/regress/file10.vhd \
	test/regress/file11.vhd \
	test/regress/file12.vhd \
	test/regress/file13.vhd \
	test/regress/file14.vhd \
	test/regress/file15.vhd \
	test/regress/file1.vhd \
	test/regress/file2.vhd \
	test/regress/file3.vhd \
	test/regress/file4.vhd \
	test/regress/file5.vhd \
	test/regress/file6.vhd \
	test/regress/file7.vhd \
	test/regress/file8.vhd \
	test/regress/file9.vhd \
	test/regress/for1.vhd \
	test/regress/for2.vhd \
	test/regress/for3.vhd \
	test/regress/for4.vhd \
	test/regress/force1.vhd \
	test/regress/force2.vhd \
	test/regress/force3.vhd \
	test/regress/func10.vhd \
	test/regress/func11.vhd \
	test/regress/func12.vhd \
	test/regress/func13.vhd \
	test/regress/func14.vhd \
	test/regress/func15.vhd \
	test/regress/func16.vhd \
	test/regress/func17.vhd \
	test/regress/func18.vhd \
	test/regress/func19.vhd \
	test/regress/func1.vhd \
	test/regress/func20.vhd \
	test/regress/func21.vhd \
	test/regress/func22.vhd \
	test/regress/func23.vhd \
	test/regress/func24.vhd \
	test/regress/func25.vhd \
	test/regress/func2.vhd \
	test/regress/func3.vhd \
	test/regress/func4.vhd \
	test/regress/func5.vhd \
	test/regress/func6.vhd \
	test/regress/func7.vhd \
	test/regress/func8.vhd \
	test/regress/func9.vhd \
	test/regress/generic1.vhd \
	test/regress/genpack10.vhd \
	test/regress/genpack11.vhd \
	test/regress/genpack12.vhd \
	test/regress/genpack13.vhd \
	test/regress/genpack14.vhd \
	test/regress/genpack15.vhd \
	test/regress/genpack16.vhd \
	test/regress/genpack17.vhd \
	test/regress/genpack18.vhd \
	test/regress/genpack1.vhd \
	test/regress/genpack2.vhd \
	test/regress/genpack3.vhd \
	test/regress/genpack4.vhd \
	test/regress/genpack5.vhd \
	test/regress/genpack6.vhd \
	test/regress/genpack7.vhd \
	test/regress/genpack8.vhd \
	test/regress/genpack9.vhd \
	test/regress/gensub1.vhd \
	test/regress/gensub2.vhd \
	test/regress/gensub3.vhd \
	test/regress/gensub4.vhd \
	test/regress/gensub5.vhd \
	test/regress/gensub6.vhd \
	test/regress/gentype1.vhd \
	test/regress/gentype2.vhd \
	test/regress/gentype3.vhd \
	test/regress/gentype4.vhd \
	test/regress/gentype5.vhd \
	test/regress/gentype6.vhd \
	test/regress/gentype7.vhd \
	test/regress/gentype8.vhd \
	test/regress/gentype9.vhd \
	test/regress/gold/access10.txt \
	test/regress/gold/access1.txt \
	test/regress/gold/access6.txt \
	test/regress/gold/access8.txt \
	test/regress/gold/alias12.txt \
	test/regress/gold/alias1.txt \
	test/regress/gold/alias2.txt \
	test/regress/gold/alias5.txt \
	test/regress/gold/arith2.txt \
	test/regress/gold/arith4.txt \
	test/regress/gold/arith5.txt \
	test/regress/gold/array15.txt \
	test/regress/gold/assert10.txt \
	test/regress/gold/assert1.txt \
	test/regress/gold/assert2.txt \
	test/regress/gold/assert3.txt \
	test/regress/gold/assert6.txt \
	test/regress/gold/assert7.txt \
	test/regress/gold/assert8.txt \
	test/regress/gold/assert9.txt \
	test/regress/gold/attr12.txt \
	test/regress/gold/attr17.txt \
	test/regress/gold/attr19.txt \
	test/regress/gold/attr21.txt \
	test/regress/gold/attr3.txt \
	test/regress/gold/bounds10.txt \
	test/regress/gold/bounds11.txt \
	test/regress/gold/bounds12.txt \
	test/regress/gold/bounds13.txt \
	test/regress/gold/bounds14.txt \
	test/regress/gold/bounds15.txt \
	test/regress/gold/bounds16.txt \
	test/regress/gold/bounds17.txt \
	test/regress/gold/bounds18.txt \
	test/regress/gold/bounds19.txt \
	test/regress/gold/bounds1.txt \
	test/regress/gold/bounds20.txt \
	test/regress/gold/bounds21.txt \
	test/regress/gold/bounds22.txt \
	test/regress/gold/bounds23.txt \
	test/regress/gold/bounds24.txt \
	test/regress/gold/bounds25.txt \
	test/regress/gold/bounds26.txt \
	test/regress/gold/bounds27.txt \
	test/regress/gold/bounds28.txt \
	test/regress/gold/bounds29.txt \
	test/regress/gold/bounds2.txt \
	test/regress/gold/bounds30.txt \
	test/regress/gold/bounds31.txt \
	test/regress/gold/bounds32.txt \
	test/regress/gold/bounds33.txt \
	test/regress/gold/bounds34.txt \
	test/regress/gold/bounds35.txt \
	test/regress/gold/bounds36.txt \
	test/regress/gold/bounds37.txt \
	test/regress/gold/bounds38.txt \
	test/regress/gold/bounds39.txt \
	test/regress/gold/bounds3.txt \
	test/regress/gold/bounds40.txt \
	test/regress/gold/bounds41.txt \
	test/regress/gold/bounds42.txt \
	test/regress/gold/bounds43.txt \
	test/regress/gold/bounds44.txt \
	test/regress/gold/bounds45.txt \
	test/regress/gold/bounds4.txt \
	test/regress/gold/bounds5.txt \
	test/regress/gold/bounds6.txt \
	test/regress/gold/bounds7.txt \
	test/regress/gold/bounds8.txt \
	test/regress/gold/bounds9.txt \
	test/regress/gold/case12.txt \
	test/regress/gold/case13.txt \
	test/regress/gold/case5.txt \
	test/regress/gold/cond1.txt \
	test/regress/gold/cond2.txt \
	test/regress/gold/conf1.txt \
	test/regress/gold/conf2.txt \
	test/regress/gold/const3.txt \
	test/regress/gold/conv10.txt \
	test/regress/gold/counter.txt \
	test/regress/gold/cover10.txt \
	test/regress/gold/cover12.txt \
	test/regress/gold/cover13.txt \
	test/regress/gold/cover14.txt \
	test/regress/gold/cover15.xml \
	test/regress/gold/cover16.xml \
	test/regress/gold/cover17.xml \
	test/regress/gold/cover18.txt \
	test/regress/gold/cover19.txt \
	test/regress/gold/cover1.txt \
	test/regress/gold/cover1.xml \
	test/regress/gold/cover20.txt \
	test/regress/gold/cover21.txt \
	test/regress/gold/cover22.txt \
	test/regress/gold/cover23.txt \
	test/regress/gold/cover24.txt \
	test/regress/gold/cover25.xml \
	test/regress/gold/cover2.xml \
	test/regress/gold/cover3.xml \
	test/regress/gold/cover4.xml \
	test/regress/gold/cover5.txt \
	test/regress/gold/cover6.txt \
	test/regress/gold/cover7.xml \
	test/regress/gold/cover8.xml \
	test/regress/gold/cover9.txt \
	test/regress/gold/debug1.txt \
	test/regress/gold/debug2.txt \
	test/regress/gold/debug3.txt \
	test/regress/gold/delay3.txt \
	test/regress/gold/driver15.txt \
	test/regress/gold/driver21.txt \
	test/regress/gold/driver22.txt \
	test/regress/gold/driver7.txt \
	test/regress/gold/driver9.txt \
	test/regress/gold/elab10.txt \
	test/regress/gold/elab13.txt \
	test/regress/gold/elab3.txt \
	test/regress/gold/elab9.txt \
	test/regress/gold/ename10.txt \
	test/regress/gold/ename11.txt \
	test/regress/gold/ename12.txt \
	test/regress/gold/ename13.txt \
	test/regress/gold/ename14.txt \
	test/regress/gold/ename16.txt \
	test/regress/gold/ename17.txt \
	test/regress/gold/ename2.txt \
	test/regress/gold/ename5.txt \
	test/regress/gold/ename9.txt \
	test/regress/gold/fact.txt \
	test/regress/gold/file13.txt \
	test/regress/gold/file14.txt \
	test/regress/gold/file8.txt \
	test/regress/gold/for1.txt \
	test/regress/gold/for2.txt \
	test/regress/gold/for3.txt \
	test/regress/gold/force3.txt \
	test/regress/gold/func19.txt \
	test/regress/gold/ieee11.txt \
	test/regress/gold/ieee12.txt \
	test/regress/gold/ieee13.txt \
	test/regress/gold/ieee14.txt \
	test/regress/gold/ieee15.txt \
	test/regress/gold/ieee9.txt \
	test/regress/gold/image1.txt \
	test/regress/gold/issue101.txt \
	test/regress/gold/issue1030.dump \
	test/regress/gold/issue103.txt \
	test/regress/gold/issue1060.txt \
	test/regress/gold/issue1071.dump \
	test/regress/gold/issue1079.txt \
	test/regress/gold/issue110.txt \
	test/regress/gold/issue185.txt \
	test/regress/gold/issue202.txt \
	test/regress/gold/issue225.txt \
	test/regress/gold/issue227.txt \
	test/regress/gold/issue228.txt \
	test/regress/gold/issue234.txt \
	test/regress/gold/issue308.txt \
	test/regress/gold/issue351.txt \
	test/regress/gold/issue377.txt \
	test/regress/gold/issue433.txt \
	test/regress/gold/issue454.dump \
	test/regress/gold/issue45.txt \
	test/regress/gold/issue469.txt \
	test/regress/gold/issue494.txt \
	test/regress/gold/issue521.txt \
	test/regress/gold/issue524.dump \
	test/regress/gold/issue536.dump \
	test/regress/gold/issue586.dump \
	test/regress/gold/issue592.txt \
	test/regress/gold/issue597.txt \
	test/regress/gold/issue615.txt \
	test/regress/gold/issue616.txt \
	test/regress/gold/issue617.txt \
	test/regress/gold/issue668.txt \
	test/regress/gold/issue700.txt \
	test/regress/gold/issue701.txt \
	test/regress/gold/issue703.dump \
	test/regress/gold/issue703.gtkw \
	test/regress/gold/issue704.dump \
	test/regress/gold/issue718.txt \
	test/regress/gold/issue730.txt \
	test/regress/gold/issue734.txt \
	test/regress/gold/issue747.txt \
	test/regress/gold/issue801.txt \
	test/regress/gold/issue808.txt \
	test/regress/gold/issue816.txt \
	test/regress/gold/issue817.txt \
	test/regress/gold/issue840.dump \
	test/regress/gold/issue851.dump \
	test/regress/gold/issue852.dump \
	test/regress/gold/issue856.dump \
	test/regress/gold/issue862.txt \
	test/regress/gold/issue878.dump \
	test/regress/gold/issue885.txt \
	test/regress/gold/issue901.dump \
	test/regress/gold/issue903.xml \
	test/regress/gold/issue904.dump \
	test/regress/gold/issue906.xml \
	test/regress/gold/issue907.txt \
	test/regress/gold/issue909.txt \
	test/regress/gold/issue941.xml \
	test/regress/gold/issue957.dump \
	test/regress/gold/issue962.dump \
	test/regress/gold/issue96.txt \
	test/regress/gold/issue970.txt \
	test/regress/gold/issue972.dump \
	test/regress/gold/issue979.dump \
	test/regress/gold/issue985.dump \
	test/regress/gold/ivtest2.txt \
	test/regress/gold/proc7.txt \
	test/regress/gold/proc8.txt \
	test/regress/gold/protected11.txt \
	test/regress/gold/psl10.txt \
	test/regress/gold/psl11.txt \
	test/regress/gold/psl13.txt \
	test/regress/gold/psl14.txt \
	test/regress/gold/psl15.txt \
	test/regress/gold/psl16.txt \
	test/regress/gold/psl17.txt \
	test/regress/gold/psl1.txt \
	test/regress/gold/psl2.txt \
	test/regress/gold/psl3.txt \
	test/regress/gold/psl4.txt \
	test/regress/gold/psl5.txt \
	test/regress/gold/psl6.txt \
	test/regress/gold/psl7.txt \
	test/regress/gold/psl8.txt \
	test/regress/gold/psl9.txt \
	test/regress/gold/range1.txt \
	test/regress/gold/real1.txt \
	test/regress/gold/real3.txt \
	test/regress/gold/real4.txt \
	test/regress/gold/record38.txt \
	test/regress/gold/signal11.txt \
	test/regress/gold/signal23.txt \
	test/regress/gold/signal29.txt \
	test/regress/gold/signal34.txt \
	test/regress/gold/signal6.txt \
	test/regress/gold/stop1.txt \
	test/regress/gold/stop2.txt \
	test/regress/gold/synopsys2.txt \
	test/regress/gold/synopsys3.txt \
	test/regress/gold/tcl3.txt \
	test/regress/gold/textio1.txt \
	test/regress/gold/textio5.txt \
	test/regress/gold/value3.txt \
	test/regress/gold/value4.txt \
	test/regress/gold/vhpi1.txt \
	test/regress/gold/vhpi5.txt \
	test/regress/gold/vlog2.txt \
	test/regress/gold/vlog3.txt \
	test/regress/gold/vlog4.txt \
	test/regress/gold/vlog5.txt \
	test/regress/gold/vlog6.txt \
	test/regress/gold/vlog7.txt \
	test/regress/gold/wait12.txt \
	test/regress/gold/wait26.txt \
	test/regress/gold/wait28.txt \
	test/regress/gold/wait2.txt \
	test/regress/gold/wait6.txt \
	test/regress/gold/wave10.dump \
	test/regress/gold/wave11.dump \
	test/regress/gold/wave12.dump \
	test/regress/gold/wave1.dump \
	test/regress/gold/wave2.dump \
	test/regress/gold/wave3.dump \
	test/regress/gold/wave3.gtkw \
	test/regress/gold/wave4.dump \
	test/regress/gold/wave5.dump \
	test/regress/gold/wave5.gtkw \
	test/regress/gold/wave6.dump \
	test/regress/gold/wave7.dump \
	test/regress/gold/wave8.dump \
	test/regress/gold/wave9.dump \
	test/regress/gold/while1.txt \
	test/regress/grlib1.vhd \
	test/regress/guard1.vhd \
	test/regress/guard2.vhd \
	test/regress/guard3.vhd \
	test/regress/guard4.vhd \
	test/regress/guard5.vhd \
	test/regress/ieee10.vhd \
	test/regress/ieee11.vhd \
	test/regress/ieee12.vhd \
	test/regress/ieee13.vhd \
	test/regress/ieee14.vhd \
	test/regress/ieee15.vhd \
	test/regress/ieee16.vhd \
	test/regress/ieee17.vhd \
	test/regress/ieee1.vhd \
	test/regress/ieee2.vhd \
	test/regress/ieee3.vhd \
	test/regress/ieee4.vhd \
	test/regress/ieee5.vhd \
	test/regress/ieee6.vhd \
	test/regress/ieee7.vhd \
	test/regress/ieee8.vhd \
	test/regress/ieee9.vhd \
	test/regress/image1.vhd \
	test/regress/image2.vhd \
	test/regress/implicit1.vhd \
	test/regress/implicit2.vhd \
	test/regress/implicit3.vhd \
	test/regress/implicit4.vhd \
	test/regress/implicit5.vhd \
	test/regress/implicit6.vhd \
	test/regress/implicit7.vhd \
	test/regress/implicit8.vhd \
	test/regress/implicit9.vhd \
	test/regress/integer1.vhd \
	test/regress/integer2.vhd \
	test/regress/integer3.vhd \
	test/regress/issue101.vhd \
	test/regress/issue1030.vhd \
	test/regress/issue1035.vhd \
	test/regress/issue1036.vhd \
	test/regress/issue103.vhd \
	test/regress/issue1043.vhd \
	test/regress/issue1044.v \
	test/regress/issue1044.vhd \
	test/regress/issue1045.vhd \
	test/regress/issue104.vhd \
	test/regress/issue1057.vhd \
	test/regress/issue1060.vhd \
	test/regress/issue1062.vhd \
	test/regress/issue106.vhd \
	test/regress/issue1071.vhd \
	test/regress/issue1074.vhd \
	test/regress/issue1079.vhd \
	test/regress/issue1094.vhd \
	test/regress/issue109.vhd \
	test/regress/issue10.vhd \
	test/regress/issue110.vhd \
	test/regress/issue1117.vhd \
	test/regress/issue111.vhd \
	test/regress/issue1125.vhd \
	test/regress/issue112.vhd \
	test/regress/issue1137.vhd \
	test/regress/issue115.vhd \
	test/regress/issue116.vhd \
	test/regress/issue121.vhd \
	test/regress/issue122.vhd \
	test/regress/issue123.vhd \
	test/regress/issue126.vhd \
	test/regress/issue13.vhd \
	test/regress/issue141.vhd \
	test/regress/issue143.vhd \
	test/regress/issue146.vhd \
	test/regress/issue148.vhd \
	test/regress/issue152.vhd \
	test/regress/issue153.vhd \
	test/regress/issue163.vhd \
	test/regress/issue169.vhd \
	test/regress/issue16.vhd \
	test/regress/issue183.vhd \
	test/regress/issue185.vhd \
	test/regress/issue186.vhd \
	test/regress/issue187.vhd \
	test/regress/issue18.vhd \
	test/regress/issue194.vhd \
	test/regress/issue196.vhd \
	test/regress/issue197.vhd \
	test/regress/issue200.vhd \
	test/regress/issue201.vhd \
	test/regress/issue202.vhd \
	test/regress/issue204.vhd \
	test/regress/issue206.vhd \
	test/regress/issue217.vhd \
	test/regress/issue225.vhd \
	test/regress/issue227.vhd \
	test/regress/issue229.vhd \
	test/regress/issue234.vhd \
	test/regress/issue262.vhd \
	test/regress/issue284.vhd \
	test/regress/issue293.vhd \
	test/regress/issue29.vhd \
	test/regress/issue308.vhd \
	test/regress/issue309.vhd \
	test/regress/issue315.vhd \
	test/regress/issue323.vhd \
	test/regress/issue327.vhd \
	test/regress/issue335.vhd \
	test/regress/issue338b.vhd \
	test/regress/issue338.vhd \
	test/regress/issue340.vhd \
	test/regress/issue348.vhd \
	test/regress/issue349.vhd \
	test/regress/issue351.vhd \
	test/regress/issue352.vhd \
	test/regress/issue354.vhd \
	test/regress/issue367.vhd \
	test/regress/issue369.vhd \
	test/regress/issue370.vhd \
	test/regress/issue371.vhd \
	test/regress/issue376.vhd \
	test/regress/issue377.vhd \
	test/regress/issue38.vhd \
	test/regress/issue397.vhd \
	test/regress/issue405.vhd \
	test/regress/issue407.vhd \
	test/regress/issue412.vhd \
	test/regress/issue414.vhd \
	test/regress/issue415.vhd \
	test/regress/issue420.vhd \
	test/regress/issue423.vhd \
	test/regress/issue428.vhd \
	test/regress/issue429.vhd \
	test/regress/issue430.vhd \
	test/regress/issue432.vhd \
	test/regress/issue433.vhd \
	test/regress/issue434.vhd \
	test/regress/issue447.vhd \
	test/regress/issue454.sh \
	test/regress/issue454.vhd \
	test/regress/issue45.vhd \
	test/regress/issue460.vhd \
	test/regress/issue467.vhd \
	test/regress/issue469.vhd \
	test/regress/issue472.sh \
	test/regress/issue481.vhd \
	test/regress/issue483.vhd \
	test/regress/issue484.vhd \
	test/regress/issue493.sh \
	test/regress/issue494.vhd \
	test/regress/issue497.vhd \
	test/regress/issue502.vhd \
	test/regress/issue507.sh \
	test/regress/issue508.vhd \
	test/regress/issue516.vhd \
	test/regress/issue519.vhd \
	test/regress/issue520.vhd \
	test/regress/issue521.vhd \
	test/regress/issue524.sh \
	test/regress/issue524.vhd \
	test/regress/issue527.vhd \
	test/regress/issue536.vhd \
	test/regress/issue539.vhd \
	test/regress/issue53.vhd \
	test/regress/issue540.vhd \
	test/regress/issue542.vhd \
	test/regress/issue543.vhd \
	test/regress/issue544.vhd \
	test/regress/issue547.vhd \
	test/regress/issue548.sh \
	test/regress/issue549.vhd \
	test/regress/issue550.vhd \
	test/regress/issue551.vhd \
	test/regress/issue552.vhd \
	test/regress/issue560.vhd \
	test/regress/issue56.vhd \
	test/regress/issue570.vhd \
	test/regress/issue571.vhd \
	test/regress/issue577.vhd \
	test/regress/issue57.vhd \
	test/regress/issue586.sh \
	test/regress/issue586.vhd \
	test/regress/issue589.vhd \
	test/regress/issue590.vhd \
	test/regress/issue592.vhd \
	test/regress/issue595.vhd \
	test/regress/issue597.vhd \
	test/regress/issue59.vhd \
	test/regress/issue603.vhd \
	test/regress/issue609.vhd \
	test/regress/issue60.vhd \
	test/regress/issue610.vhd \
	test/regress/issue612.vhd \
	test/regress/issue613.vhd \
	test/regress/issue615.vhd \
	test/regress/issue616.vhd \
	test/regress/issue617.vhd \
	test/regress/issue618.vhd \
	test/regress/issue620.vhd \
	test/regress/issue63.vhd \
	test/regress/issue640.vhd \
	test/regress/issue643.vhd \
	test/regress/issue644.vhd \
	test/regress/issue646.vhd \
	test/regress/issue653.vhd \
	test/regress/issue654.vhd \
	test/regress/issue655.vhd \
	test/regress/issue658.vhd \
	test/regress/issue668.vhd \
	test/regress/issue670.vhd \
	test/regress/issue674.vhd \
	test/regress/issue675.vhd \
	test/regress/issue676.vhd \
	test/regress/issue677.vhd \
	test/regress/issue681.vhd \
	test/regress/issue690.vhd \
	test/regress/issue69.vhd \
	test/regress/issue700.vhd \
	test/regress/issue701.vhd \
	test/regress/issue703.vhd \
	test/regress/issue704.vhd \
	test/regress/issue705.vhd \
	test/regress/issue70.vhd \
	test/regress/issue712.vhd \
	test/regress/issue714.vhd \
	test/regress/issue715.sh \
	test/regress/issue718.vhd \
	test/regress/issue724.vhd \
	test/regress/issue726.vhd \
	test/regress/issue72.vhd \
	test/regress/issue730.vhd \
	test/regress/issue731.vhd \
	test/regress/issue732.vhd \
	test/regress/issue734.vhd \
	test/regress/issue744.vhd \
	test/regress/issue747.vhd \
	test/regress/issue750.vhd \
	test/regress/issue751.vhd \
	test/regress/issue752.sh \
	test/regress/issue762.vhd \
	test/regress/issue766.vhd \
	test/regress/issue769.sh \
	test/regress/issue787.vhd \
	test/regress/issue790.vhd \
	test/regress/issue791.vhd \
	test/regress/issue794.vhd \
	test/regress/issue799.vhd \
	test/regress/issue79.vhd \
	test/regress/issue801.vhd \
	test/regress/issue808.v \
	test/regress/issue809.vhd \
	test/regress/issue810.vhd \
	test/regress/issue815.vhd \
	test/regress/issue816.vhd \
	test/regress/issue817.vhd \
	test/regress/issue819.vhd \
	test/regress/issue820.vhd \
	test/regress/issue824.vhd \
	test/regress/issue825.vhd \
	test/regress/issue826.vhd \
	test/regress/issue827.vhd \
	test/regress/issue829.vhd \
	test/regress/issue82.vhd \
	test/regress/issue831.vhd \
	test/regress/issue839.vhd \
	test/regress/issue83.vhd \
	test/regress/issue840.vhd \
	test/regress/issue842.vhd \
	test/regress/issue843.vhd \
	test/regress/issue844.vhd \
	test/regress/issue84.vhd \
	test/regress/issue850.sh \
	test/regress/issue851.vhd \
	test/regress/issue852.vhd \
	test/regress/issue854.vhd \
	test/regress/issue856.vhd \
	test/regress/issue858.vhd \
	test/regress/issue862.vhd \
	test/regress/issue86.vhd \
	test/regress/issue873.vhd \
	test/regress/issue874.vhd \
	test/regress/issue877.vhd \
	test/regress/issue878.vhd \
	test/regress/issue881.vhd \
	test/regress/issue884.vhd \
	test/regress/issue885.vhd \
	test/regress/issue887.vhd \
	test/regress/issue890.vhd \
	test/regress/issue894.vhd \
	test/regress/issue899.vhd \
	test/regress/issue8.vhd \
	test/regress/issue901.vhd \
	test/regress/issue903.vhd \
	test/regress/issue904.vhd \
	test/regress/issue906.vhd \
	test/regress/issue907.vhd \
	test/regress/issue908.vhd \
	test/regress/issue909.sh \
	test/regress/issue90.vhd \
	test/regress/issue91.vhd \
	test/regress/issue921.vhd \
	test/regress/issue923.vhd \
	test/regress/issue924.vhd \
	test/regress/issue925.vhd \
	test/regress/issue931.vhd \
	test/regress/issue932.vhd \
	test/regress/issue941.vhd \
	test/regress/issue943.vhd \
	test/regress/issue946.vhd \
	test/regress/issue94.vhd \
	test/regress/issue950.vhd \
	test/regress/issue954.vhd \
	test/regress/issue957.vhd \
	test/regress/issue95.vhd \
	test/regress/issue960.vhd \
	test/regress/issue962.vhd \
	test/regress/issue963.vhd \
	test/regress/issue968.vhd \
	test/regress/issue96.vhd \
	test/regress/issue970.vhd \
	test/regress/issue971.vhd \
	test/regress/issue972.vhd \
	test/regress/issue978.vhd \
	test/regress/issue979.vhd \
	test/regress/issue983.vhd \
	test/regress/issue985.vhd \
	test/regress/issue988.vhd \
	test/regress/issue98.vhd \
	test/regress/issue9.vhd \
	test/regress/ivtest1.v \
	test/regress/ivtest2.v \
	test/regress/ivtest3.v \
	test/regress/ivtest4.v \
	test/regress/ivtest5.v \
	test/regress/jcore1.vhd \
	test/regress/jcore2.vhd \
	test/regress/jcore3.vhd \
	test/regress/jcore4.vhd \
	test/regress/jcore5.vhd \
	test/regress/jcore6.vhd \
	test/regress/lfsr.vhd \
	test/regress/libdir1.sh \
	test/regress/libdir2.sh \
	test/regress/libdir3.sh \
	test/regress/libdir4.sh \
	test/regress/link1.vhd \
	test/regress/link2.vhd \
	test/regress/link3.sh \
	test/regress/link3.vhd \
	test/regress/link4.vhd \
	test/regress/logical1.vhd \
	test/regress/logical2.vhd \
	test/regress/logical3.vhd \
	test/regress/loop1.vhd \
	test/regress/mixed1.v \
	test/regress/mixed1.vhd \
	test/regress/mixed2.v \
	test/regress/mixed2.vhd \
	test/regress/mixed3.v \
	test/regress/mixed3.vhd \
	test/regress/null1.vhd \
	test/regress/null2.vhd \
	test/regress/null3.vhd \
	test/regress/open1.vhd \
	test/regress/open2.vhd \
	test/regress/operator1.vhd \
	test/regress/operator2.vhd \
	test/regress/operator3.vhd \
	test/regress/operator4.vhd \
	test/regress/operator5.vhd \
	test/regress/operator6.vhd \
	test/regress/order1.vhd \
	test/regress/order2.sh \
	test/regress/order3.sh \
	test/regress/predef1.vhd \
	test/regress/predef2.vhd \
	test/regress/predef3.vhd \
	test/regress/predef4.vhd \
	test/regress/predef5.vhd \
	test/regress/proc10.vhd \
	test/regress/proc11.vhd \
	test/regress/proc12.vhd \
	test/regress/proc1.vhd \
	test/regress/proc2.vhd \
	test/regress/proc3.vhd \
	test/regress/proc4.vhd \
	test/regress/proc5.vhd \
	test/regress/proc6.vhd \
	test/regress/proc7.vhd \
	test/regress/proc8.vhd \
	test/regress/proc9.vhd \
	test/regress/protected10.vhd \
	test/regress/protected11.vhd \
	test/regress/protected12.vhd \
	test/regress/protected13.vhd \
	test/regress/protected1.vhd \
	test/regress/protected2.vhd \
	test/regress/protected3.vhd \
	test/regress/protected4.vhd \
	test/regress/protected5.vhd \
	test/regress/protected6.vhd \
	test/regress/protected7.vhd \
	test/regress/protected8.vhd \
	test/regress/protected9.vhd \
	test/regress/psl10.vhd \
	test/regress/psl11.vhd \
	test/regress/psl12.vhd \
	test/regress/psl13.vhd \
	test/regress/psl14.vhd \
	test/regress/psl15.vhd \
	test/regress/psl16.vhd \
	test/regress/psl17.vhd \
	test/regress/psl1.vhd \
	test/regress/psl2.vhd \
	test/regress/psl3.vhd \
	test/regress/psl4.vhd \
	test/regress/psl5.vhd \
	test/regress/psl6.vhd \
	test/regress/psl7.vhd \
	test/regress/psl8.vhd \
	test/regress/psl9.vhd \
	test/regress/ram1.vhd \
	test/regress/range1.vhd \
	test/regress/range2.vhd \
	test/regress/range3.vhd \
	test/regress/real1.vhd \
	test/regress/real2.vhd \
	test/regress/real3.vhd \
	test/regress/real4.vhd \
	test/regress/real5.vhd \
	test/regress/real6.vhd \
	test/regress/record10.vhd \
	test/regress/record11.vhd \
	test/regress/record12.vhd \
	test/regress/record13.vhd \
	test/regress/record14.vhd \
	test/regress/record15.vhd \
	test/regress/record16.vhd \
	test/regress/record17.vhd \
	test/regress/record18.vhd \
	test/regress/record19.vhd \
	test/regress/record1.vhd \
	test/regress/record20.vhd \
	test/regress/record21.vhd \
	test/regress/record22.vhd \
	test/regress/record23.vhd \
	test/regress/record24.vhd \
	test/regress/record25.vhd \
	test/regress/record26.vhd \
	test/regress/record27.vhd \
	test/regress/record28.vhd \
	test/regress/record29.vhd \
	test/regress/record2.vhd \
	test/regress/record30.vhd \
	test/regress/record31.vhd \
	test/regress/record32.vhd \
	test/regress/record33.vhd \
	test/regress/record34.vhd \
	test/regress/record35.vhd \
	test/regress/record36.vhd \
	test/regress/record37.vhd \
	test/regress/record38.vhd \
	test/regress/record39.vhd \
	test/regress/record3.vhd \
	test/regress/record4.vhd \
	test/regress/record5.vhd \
	test/regress/record6.vhd \
	test/regress/record7.vhd \
	test/regress/record8.vhd \
	test/regress/record9.vhd \
	test/regress/reflect1.vhd \
	test/regress/reflect2.vhd \
	test/regress/reflect3.vhd \
	test/regress/reflect4.vhd \
	test/regress/reflect5.vhd \
	test/regress/seqblock1.vhd \
	test/regress/seqblock2.vhd \
	test/regress/shared1.vhd \
	test/regress/shared2.vhd \
	test/regress/shared3.vhd \
	test/regress/shared4.vhd \
	test/regress/shift1.vhd \
	test/regress/shift2.vhd \
	test/regress/shuffle1.vhd \
	test/regress/signal10.vhd \
	test/regress/signal11.vhd \
	test/regress/signal12.vhd \
	test/regress/signal13.vhd \
	test/regress/signal14.vhd \
	test/regress/signal15.vhd \
	test/regress/signal16.vhd \
	test/regress/signal17.vhd \
	test/regress/signal18.vhd \
	test/regress/signal19.vhd \
	test/regress/signal1.vhd \
	test/regress/signal20.vhd \
	test/regress/signal21.vhd \
	test/regress/signal22.vhd \
	test/regress/signal23.vhd \
	test/regress/signal24.vhd \
	test/regress/signal25.vhd \
	test/regress/signal26.vhd \
	test/regress/signal27.vhd \
	test/regress/signal28.vhd \
	test/regress/signal29.vhd \
	test/regress/signal2.vhd \
	test/regress/signal30.vhd \
	test/regress/signal31.vhd \
	test/regress/signal32.vhd \
	test/regress/signal33.vhd \
	test/regress/signal34.vhd \
	test/regress/signal35.vhd \
	test/regress/signal36.vhd \
	test/regress/signal37.vhd \
	test/regress/signal3.vhd \
	test/regress/signal4.vhd \
	test/regress/signal5.vhd \
	test/regress/signal6.vhd \
	test/regress/signal7.vhd \
	test/regress/signal8.vhd \
	test/regress/signal9.vhd \
	test/regress/slice1.vhd \
	test/regress/slice2.vhd \
	test/regress/slice3.vhd \
	test/regress/slice4.vhd \
	test/regress/slice5.vhd \
	test/regress/stack1.vhd \
	test/regress/stdenv1.vhd \
	test/regress/stdenv2.vhd \
	test/regress/stdenv3.vhd \
	test/regress/stdenv4.vhd \
	test/regress/stdenv5.vhd \
	test/regress/stdenv6.vhd \
	test/regress/stop1.vhd \
	test/regress/synopsys1.vhd \
	test/regress/synopsys2.vhd \
	test/regress/synopsys3.vhd \
	test/regress/tcl1.tcl \
	test/regress/tcl2.tcl \
	test/regress/tcl3.tcl \
	test/regress/testlist.txt \
	test/regress/textio1.vhd \
	test/regress/textio2.vhd \
	test/regress/textio3.vhd \
	test/regress/textio4.vhd \
	test/regress/textio5.vhd \
	test/regress/textio6.vhd \
	test/regress/textio7.vhd \
	test/regress/textio8.vhd \
	test/regress/toplevel1.vhd \
	test/regress/toplevel2.vhd \
	test/regress/toplevel3.vhd \
	test/regress/value1.vhd \
	test/regress/value2.vhd \
	test/regress/value3.vhd \
	test/regress/value4.vhd \
	test/regress/vecorder1.vhd \
	test/regress/vecorder2.vhd \
	test/regress/vests10.vhd \
	test/regress/vests11.vhd \
	test/regress/vests12.vhd \
	test/regress/vests13.vhd \
	test/regress/vests14.vhd \
	test/regress/vests15.vhd \
	test/regress/vests16.vhd \
	test/regress/vests17.vhd \
	test/regress/vests18.vhd \
	test/regress/vests19.vhd \
	test/regress/vests1.vhd \
	test/regress/vests20.vhd \
	test/regress/vests21.vhd \
	test/regress/vests22.vhd \
	test/regress/vests23.vhd \
	test/regress/vests24.vhd \
	test/regress/vests25.vhd \
	test/regress/vests26.vhd \
	test/regress/vests27.vhd \
	test/regress/vests28.vhd \
	test/regress/vests29.vhd \
	test/regress/vests2.vhd \
	test/regress/vests30.vhd \
	test/regress/vests31.vhd \
	test/regress/vests32.vhd \
	test/regress/vests33.vhd \
	test/regress/vests34.vhd \
	test/regress/vests35.vhd \
	test/regress/vests36.vhd \
	test/regress/vests37.vhd \
	test/regress/vests38.vhd \
	test/regress/vests39.vhd \
	test/regress/vests3.vhd \
	test/regress/vests40.vhd \
	test/regress/vests41.vhd \
	test/regress/vests42.vhd \
	test/regress/vests43.vhd \
	test/regress/vests44.vhd \
	test/regress/vests45.vhd \
	test/regress/vests46.vhd \
	test/regress/vests47.vhd \
	test/regress/vests48.vhd \
	test/regress/vests49.vhd \
	test/regress/vests4.vhd \
	test/regress/vests5.vhd \
	test/regress/vests6.vhd \
	test/regress/vests7.vhd \
	test/regress/vests8.vhd \
	test/regress/vests9.vhd \
	test/regress/vhpi10.vhd \
	test/regress/vhpi11.vhd \
	test/regress/vhpi12.vhd \
	test/regress/vhpi13.vhd \
	test/regress/vhpi14.vhd \
	test/regress/vhpi15.vhd \
	test/regress/vhpi1.vhd \
	test/regress/vhpi2.vhd \
	test/regress/vhpi3.vhd \
	test/regress/vhpi4.vhd \
	test/regress/vhpi5.vhd \
	test/regress/vhpi6.vhd \
	test/regress/vhpi7.vhd \
	test/regress/vhpi8.vhd \
	test/regress/vhpi9.vhd \
	test/regress/view1.vhd \
	test/regress/view2.vhd \
	test/regress/view3.vhd \
	test/regress/view4.vhd \
	test/regress/view5.vhd \
	test/regress/view6.vhd \
	test/regress/vital1.vhd \
	test/regress/vlog10.v \
	test/regress/vlog11.v \
	test/regress/vlog12.v \
	test/regress/vlog13.v \
	test/regress/vlog1.v \
	test/regress/vlog1.vhd \
	test/regress/vlog2.v \
	test/regress/vlog3.v \
	test/regress/vlog4.v \
	test/regress/vlog5.v \
	test/regress/vlog6.v \
	test/regress/vlog7.v \
	test/regress/vlog8.v \
	test/regress/vlog9.v \
	test/regress/wait10.vhd \
	test/regress/wait11.vhd \
	test/regress/wait12.vhd \
	test/regress/wait13.vhd \
	test/regress/wait14.vhd \
	test/regress/wait15.vhd \
	test/regress/wait16.vhd \
	test/regress/wait17.vhd \
	test/regress/wait18.vhd \
	test/regress/wait19.vhd \
	test/regress/wait1.vhd \
	test/regress/wait20.vhd \
	test/regress/wait21.vhd \
	test/regress/wait22.vhd \
	test/regress/wait23.vhd \
	test/regress/wait24.vhd \
	test/regress/wait25.vhd \
	test/regress/wait26.vhd \
	test/regress/wait27.vhd \
	test/regress/wait28.vhd \
	test/regress/wait2.vhd \
	test/regress/wait3.vhd \
	test/regress/wait4.vhd \
	test/regress/wait5.vhd \
	test/regress/wait6.vhd \
	test/regress/wait7.vhd \
	test/regress/wait8.vhd \
	test/regress/wait9.vhd \
	test/regress/wave10.vhd \
	test/regress/wave11.vhd \
	test/regress/wave12.vhd \
	test/regress/wave1.vhd \
	test/regress/wave2.sh \
	test/regress/wave2.vhd \
	test/regress/wave3.vhd \
	test/regress/wave4.vhd \
	test/regress/wave5.vhd \
	test/regress/wave6.vhd \
	test/regress/wave7.sh \
	test/regress/wave7.vhd \
	test/regress/wave8.vhd \
	test/regress/wave9.vhd \
	test/regress/while1.vhd \
	test/sdf/parse10.sdf \
	test/sdf/parse11.sdf \
	test/sdf/parse12.sdf \
	test/sdf/parse13.sdf \
	test/sdf/parse14.sdf \
	test/sdf/parse15.sdf \
	test/sdf/parse16.sdf \
	test/sdf/parse17.sdf \
	test/sdf/parse18.sdf \
	test/sdf/parse19.sdf \
	test/sdf/parse1.sdf \
	test/sdf/parse20.sdf \
	test/sdf/parse21.sdf \
	test/sdf/parse22.sdf \
	test/sdf/parse23.sdf \
	test/sdf/parse24.sdf \
	test/sdf/parse2.sdf \
	test/sdf/parse3.sdf \
	test/sdf/parse4.sdf \
	test/sdf/parse5.sdf \
	test/sdf/parse6.sdf \
	test/sdf/parse7.sdf \
	test/sdf/parse8.sdf \
	test/sdf/parse9.sdf \
	test/sem/access.vhd \
	test/sem/afunc.vhd \
	test/sem/agg2008.vhd \
	test/sem/alias2.vhd \
	test/sem/alias.vhd \
	test/sem/altera1.vhd \
	test/sem/ambiguous.vhd \
	test/sem/array.vhd \
	test/sem/assert.vhd \
	test/sem/attr.vhd \
	test/sem/block.vhd \
	test/sem/concat.vhd \
	test/sem/conc.vhd \
	test/sem/condexpr.vhd \
	test/sem/config2.vhd \
	test/sem/config.vhd \
	test/sem/const2.vhd \
	test/sem/const.vhd \
	test/sem/context.vhd \
	test/sem/conv.vhd \
	test/sem/driving.vhd \
	test/sem/duplicate.vhd \
	test/sem/dwlau.vhd \
	test/sem/ename.vhd \
	test/sem/entity.vhd \
	test/sem/error1.vhd \
	test/sem/error2.vhd \
	test/sem/error3.vhd \
	test/sem/file_and_access.vhd \
	test/sem/file.vhd \
	test/sem/force.vhd \
	test/sem/foreign1.vhd \
	test/sem/func.vhd \
	test/sem/generate.vhd \
	test/sem/generics2008.vhd \
	test/sem/generics.vhd \
	test/sem/genpack2.vhd \
	test/sem/genpack3.vhd \
	test/sem/genpack4.vhd \
	test/sem/genpack5.vhd \
	test/sem/genpack.vhd \
	test/sem/gensub2.vhd \
	test/sem/gensub.vhd \
	test/sem/gentype.vhd \
	test/sem/implicit.vhd \
	test/sem/incomplete.vhd \
	test/sem/integer.vhd \
	test/sem/interfaces.vhd \
	test/sem/issue1010.vhd \
	test/sem/issue1020.vhd \
	test/sem/issue1024.vhd \
	test/sem/issue1025.vhd \
	test/sem/issue102.vhd \
	test/sem/issue1038.vhd \
	test/sem/issue1057.vhd \
	test/sem/issue105.vhd \
	test/sem/issue1067.vhd \
	test/sem/issue128.vhd \
	test/sem/issue130.vhd \
	test/sem/issue131.vhd \
	test/sem/issue132.vhd \
	test/sem/issue133.vhd \
	test/sem/issue140.vhd \
	test/sem/issue144.vhd \
	test/sem/issue151.vhd \
	test/sem/issue162.vhd \
	test/sem/issue165.vhd \
	test/sem/issue173.vhd \
	test/sem/issue174.vhd \
	test/sem/issue176.vhd \
	test/sem/issue177.vhd \
	test/sem/issue178.vhd \
	test/sem/issue188.vhd \
	test/sem/issue197.vhd \
	test/sem/issue201.vhd \
	test/sem/issue219.vhd \
	test/sem/issue220.vhd \
	test/sem/issue221.vhd \
	test/sem/issue224.vhd \
	test/sem/issue225.vhd \
	test/sem/issue226.vhd \
	test/sem/issue232.vhd \
	test/sem/issue236.vhd \
	test/sem/issue239.vhd \
	test/sem/issue246.vhd \
	test/sem/issue264.vhd \
	test/sem/issue276.vhd \
	test/sem/issue293.vhd \
	test/sem/issue311.vhd \
	test/sem/issue316.vhd \
	test/sem/issue326.vhd \
	test/sem/issue340.vhd \
	test/sem/issue341.vhd \
	test/sem/issue350.vhd \
	test/sem/issue356.vhd \
	test/sem/issue359a.vhd \
	test/sem/issue359.vhd \
	test/sem/issue363.vhd \
	test/sem/issue368.vhd \
	test/sem/issue369.vhd \
	test/sem/issue377.vhd \
	test/sem/issue386.vhd \
	test/sem/issue407.vhd \
	test/sem/issue465.vhd \
	test/sem/issue482.vhd \
	test/sem/issue509.vhd \
	test/sem/issue52.vhd \
	test/sem/issue53.vhd \
	test/sem/issue58.vhd \
	test/sem/issue655.vhd \
	test/sem/issue659.vhd \
	test/sem/issue660.vhd \
	test/sem/issue713.vhd \
	test/sem/issue770.vhd \
	test/sem/issue884.vhd \
	test/sem/issue88.vhd \
	test/sem/issue89.vhd \
	test/sem/issue945.vhd \
	test/sem/issue958.vhd \
	test/sem/issue965.vhd \
	test/sem/issue980.vhd \
	test/sem/jcore1.vhd \
	test/sem/lcs2016_02.vhd \
	test/sem/lcs2016_04.vhd \
	test/sem/lcs2016_07.vhd \
	test/sem/lcs2016_14a.vhd \
	test/sem/lcs2016_16.vhd \
	test/sem/lcs2016_18.vhd \
	test/sem/lcs2016_19.vhd \
	test/sem/lcs2016_23.vhd \
	test/sem/lcs2016_33.vhd \
	test/sem/lcs2016_41.vhd \
	test/sem/lcs2016_45a.vhd \
	test/sem/lcs2016_47.vhd \
	test/sem/lcs2016_49.vhd \
	test/sem/lcs2016_59.vhd \
	test/sem/lcs2016_72b.vhd \
	test/sem/lcs2016_75.vhd \
	test/sem/linkage.vhd \
	test/sem/mcase.vhd \
	test/sem/missingwait.vhd \
	test/sem/murax.vhd \
	test/sem/osvvm1.vhd \
	test/sem/osvvm2.vhd \
	test/sem/osvvm3.vhd \
	test/sem/osvvm4.vhd \
	test/sem/osvvm5.vhd \
	test/sem/physical.vhd \
	test/sem/ports.vhd \
	test/sem/procedure.vhd \
	test/sem/protected2.vhd \
	test/sem/protected.vhd \
	test/sem/real.vhd \
	test/sem/record2008.vhd \
	test/sem/record.vhd \
	test/sem/resolution.vhd \
	test/sem/scope.vhd \
	test/sem/seq.vhd \
	test/sem/signal.vhd \
	test/sem/spec1.vhd \
	test/sem/spec2.vhd \
	test/sem/static.vhd \
	test/sem/std.vhd \
	test/sem/subtype.vhd \
	test/sem/supersede.vhd \
	test/sem/tc251.vhd \
	test/sem/tc792.vhd \
	test/sem/textio.vhd \
	test/sem/universal.vhd \
	test/sem/use.vhd \
	test/sem/varinit.vhd \
	test/sem/vests1.vhd \
	test/sem/vhdl2008.vhd \
	test/sem/vital1.vhd \
	test/sem/wait.vhd \
	test/shell/describe1.vhd \
	test/shell/examine1.vhd \
	test/shell/force1.vhd \
	test/shell/wave1.vhd \
	test/simp/allsens.vhd \
	test/simp/args.vhd \
	test/simp/casearray1.vhd \
	test/simp/casefold1.vhd \
	test/simp/casegen.vhd \
	test/simp/cfold.vhd \
	test/simp/concat.vhd \
	test/simp/condexpr.vhd \
	test/simp/condvar.vhd \
	test/simp/constarr.vhd \
	test/simp/context.vhd \
	test/simp/conv1.vhd \
	test/simp/copysub.vhd \
	test/simp/cpcall.vhd \
	test/simp/ffold2.vhd \
	test/simp/ffold.vhd \
	test/simp/foreign1.vhd \
	test/simp/func9.vhd \
	test/simp/genmap.vhd \
	test/simp/genpack1.vhd \
	test/simp/gentype.vhd \
	test/simp/grlib1.vhd \
	test/simp/guard.vhd \
	test/simp/ieee1.vhd \
	test/simp/issue155.vhd \
	test/simp/issue194.vhd \
	test/simp/issue212.vhd \
	test/simp/issue309.vhd \
	test/simp/issue320.vhd \
	test/simp/issue321.vhd \
	test/simp/issue322.vhd \
	test/simp/issue331.vhd \
	test/simp/issue332.vhd \
	test/simp/issue344.vhd \
	test/simp/issue345.vhd \
	test/simp/issue362.vhd \
	test/simp/issue425.vhd \
	test/simp/issue436.vhd \
	test/simp/issue437.vhd \
	test/simp/issue438.vhd \
	test/simp/issue496.vhd \
	test/simp/issue49.vhd \
	test/simp/issue574.vhd \
	test/simp/issue742.vhd \
	test/simp/issue782.vhd \
	test/simp/issue812.vhd \
	test/simp/issue821.vhd \
	test/simp/issue867.vhd \
	test/simp/issue882.vhd \
	test/simp/length.vhd \
	test/simp/order1.vhd \
	test/simp/order2.vhd \
	test/simp/osvvm4.vhd \
	test/simp/packinst1.vhd \
	test/simp/physical.vhd \
	test/simp/ports2008.vhd \
	test/simp/predef.vhd \
	test/simp/proc.vhd \
	test/simp/protfold1.vhd \
	test/simp/protfold2.vhd \
	test/simp/recrange.vhd \
	test/simp/shift2.vhd \
	test/simp/simpif1.vhd \
	test/simp/static1.vhd \
	test/simp/synth1.vhd \
	test/simp/table.vhd \
	test/test-osvvm.tcl \
	test/tsan-suppress.txt \
	test/vlog/concat1.v \
	test/vlog/dff.v \
	test/vlog/enum1.v \
	test/vlog/gate1.v \
	test/vlog/implicit1.v \
	test/vlog/param1.v \
	test/vlog/parse1.v \
	test/vlog/ports.v \
	test/vlog/pp1.v \
	test/vlog/pp2.v \
	test/vlog/pp3.v \
	test/vlog/pp4.v \
	test/vlog/simple_sem.v \
	test/vlog/specify1.v \
	test/vlog/struct1.v \
	test/vlog/timescale1.v \
	test/vlog/udp1.v \
	test/vlog/union1.v
