# Generated automatically, do not edit.
EXTRA_DIST += \
	test/bounds/aggregate.vhd \
	test/bounds/bounds2.vhd \
	test/bounds/bounds.vhd \
	test/bounds/case2.vhd \
	test/bounds/case.vhd \
	test/bounds/issue150.vhd \
	test/bounds/issue200.vhd \
	test/bounds/issue208.vhd \
	test/bounds/issue247.vhd \
	test/bounds/issue269.vhd \
	test/bounds/issue307b.vhd \
	test/bounds/issue356.vhd \
	test/bounds/issue36.vhd \
	test/bounds/issue477a.vhd \
	test/bounds/issue477b.vhd \
	test/bounds/issue54.vhd \
	test/bounds/issue98.vhd \
	test/bounds/issue99.vhd \
	test/bounds/osvvm1.vhd \
	test/bounds/range1.vhd \
	test/bounds/tc1147.vhd \
	test/diag/diag1.vhd \
	test/elab/block1.vhd \
	test/elab/bounds10.vhd \
	test/elab/comp2.vhd \
	test/elab/comp3.vhd \
	test/elab/comp4.vhd \
	test/elab/comp.vhd \
	test/elab/const1.vhd \
	test/elab/copy1.vhd \
	test/elab/elab1.vhd \
	test/elab/elab2.vhd \
	test/elab/elab3.vhd \
	test/elab/elab4.vhd \
	test/elab/ename1.vhd \
	test/elab/eval1.vhd \
	test/elab/fold1.vhd \
	test/elab/fold2.vhd \
	test/elab/gbounds.vhd \
	test/elab/genagg.vhd \
	test/elab/generate1.vhd \
	test/elab/ifgen.vhd \
	test/elab/issue153.vhd \
	test/elab/issue157.vhd \
	test/elab/issue159.vhd \
	test/elab/issue175.vhd \
	test/elab/issue17.vhd \
	test/elab/issue184.vhd \
	test/elab/issue19.vhd \
	test/elab/issue232.vhd \
	test/elab/issue251.vhd \
	test/elab/issue305.vhd \
	test/elab/issue307.vhd \
	test/elab/issue315.vhd \
	test/elab/issue325.vhd \
	test/elab/issue328.vhd \
	test/elab/issue330.vhd \
	test/elab/issue336.vhd \
	test/elab/issue373.vhd \
	test/elab/issue374.vhd \
	test/elab/issue404.vhd \
	test/elab/issue435.vhd \
	test/elab/issue442.vhd \
	test/elab/issue448.vhd \
	test/elab/issue459.vhd \
	test/elab/issue93.vhd \
	test/elab/jcore1.vhd \
	test/elab/libbind2.vhd \
	test/elab/libbind3.vhd \
	test/elab/libbind.vhd \
	test/elab/link1.vhd \
	test/elab/neorv1.vhd \
	test/elab/open2.vhd \
	test/elab/open3.vhd \
	test/elab/opencase.vhd \
	test/elab/openinout.vhd \
	test/elab/open.vhd \
	test/elab/record.vhd \
	test/elab/tc2881.vhd \
	test/elab/tc3138.vhd \
	test/elab/tc846.vhd \
	test/elab/toplevel2.vhd \
	test/elab/toplevel3.vhd \
	test/elab/toplevel4.vhd \
	test/eopt/alias1.vhd \
	test/eopt/array3.vhd \
	test/eopt/arrayref1.vhd \
	test/eopt/arrayref2.vhd \
	test/eopt/arrayref3.vhd \
	test/eopt/arrayref4.vhd \
	test/eopt/buffer1.vhd \
	test/eopt/issue250.vhd \
	test/eopt/issue371.vhd \
	test/eopt/issue427.vhd \
	test/eopt/issue72.vhd \
	test/eopt/issue73.vhd \
	test/eopt/issue95.vhd \
	test/eopt/jcore2.vhd \
	test/eopt/jcore4.vhd \
	test/eopt/map1.vhd \
	test/eopt/map2.vhd \
	test/eopt/nonconst1.vhd \
	test/eopt/partial1.vhd \
	test/eopt/pcall1.vhd \
	test/eopt/pcall2.vhd \
	test/eopt/ram1.vhd \
	test/eopt/recref1.vhd \
	test/eopt/recref2.vhd \
	test/eopt/slice1.vhd \
	test/eopt/slice2.vhd \
	test/eopt/source1.vhd \
	test/expect.vhd \
	test/jit/access1.vhd \
	test/jit/add1.vhd \
	test/jit/arith1.vhd \
	test/jit/array1.vhd \
	test/jit/assert1.vhd \
	test/jit/case1.vhd \
	test/jit/context1.vhd \
	test/jit/fact.vhd \
	test/jit/ieeewarn.vhd \
	test/jit/issue496.vhd \
	test/jit/overflow.vhd \
	test/jit/packsignal.vhd \
	test/jit/proc1.vhd \
	test/jit/process1.vhd \
	test/jit/prot1.vhd \
	test/jit/range1.vhd \
	test/jit/real1.vhd \
	test/jit/record1.vhd \
	test/jit/record2.vhd \
	test/jit/record3.vhd \
	test/jit/record4.vhd \
	test/jit/relop1.vhd \
	test/jit/sum.vhd \
	test/jit/trace1.vhd \
	test/jit/unreachable.vhd \
	test/lower/access1.vhd \
	test/lower/access2.vhd \
	test/lower/access_bug.vhd \
	test/lower/arith1.vhd \
	test/lower/array1.vhd \
	test/lower/array2.vhd \
	test/lower/arrayop1.vhd \
	test/lower/assert1.vhd \
	test/lower/assign1.vhd \
	test/lower/assign2.vhd \
	test/lower/assign3.vhd \
	test/lower/attr1.vhd \
	test/lower/bounds1.vhd \
	test/lower/case1.vhd \
	test/lower/choice1.vhd \
	test/lower/closefile.vhd \
	test/lower/concat.vhd \
	test/lower/cond1.vhd \
	test/lower/const1.vhd \
	test/lower/const2.vhd \
	test/lower/conv1.vhd \
	test/lower/cover.vhd \
	test/lower/dealloc.vhd \
	test/lower/directmap2.vhd \
	test/lower/directmap3.vhd \
	test/lower/directmap.vhd \
	test/lower/extern1.vhd \
	test/lower/func1.vhd \
	test/lower/func5.vhd \
	test/lower/funcif.vhd \
	test/lower/genpack1.vhd \
	test/lower/hintbug.vhd \
	test/lower/iffold.vhd \
	test/lower/incomplete.vhd \
	test/lower/instance1.vhd \
	test/lower/issue116.vhd \
	test/lower/issue122.vhd \
	test/lower/issue124.vhd \
	test/lower/issue125.vhd \
	test/lower/issue134.vhd \
	test/lower/issue135.vhd \
	test/lower/issue136.vhd \
	test/lower/issue149.vhd \
	test/lower/issue158.vhd \
	test/lower/issue164.vhd \
	test/lower/issue167.vhd \
	test/lower/issue181.vhd \
	test/lower/issue203.vhd \
	test/lower/issue215.vhd \
	test/lower/issue303.vhd \
	test/lower/issue324.vhd \
	test/lower/issue333.vhd \
	test/lower/issue338b.vhd \
	test/lower/issue338.vhd \
	test/lower/issue347.vhd \
	test/lower/issue351.vhd \
	test/lower/issue357.vhd \
	test/lower/issue389.vhd \
	test/lower/issue426.vhd \
	test/lower/issue444.vhd \
	test/lower/issue462.vhd \
	test/lower/issue476.vhd \
	test/lower/issue478.vhd \
	test/lower/issue94.vhd \
	test/lower/loop1.vhd \
	test/lower/loop2.vhd \
	test/lower/memset.vhd \
	test/lower/mulphys.vhd \
	test/lower/nest1.vhd \
	test/lower/nullarray.vhd \
	test/lower/osvvm2.vhd \
	test/lower/pack1.vhd \
	test/lower/proc1.vhd \
	test/lower/proc3.vhd \
	test/lower/proc7.vhd \
	test/lower/protupref.vhd \
	test/lower/real1.vhd \
	test/lower/record1.vhd \
	test/lower/record2.vhd \
	test/lower/record6.vhd \
	test/lower/recsignal1.vhd \
	test/lower/rectype.vhd \
	test/lower/resfn1.vhd \
	test/lower/sig2var.vhd \
	test/lower/signal11.vhd \
	test/lower/signal1.vhd \
	test/lower/signal2.vhd \
	test/lower/signal4.vhd \
	test/lower/sigvar.vhd \
	test/lower/slice1.vhd \
	test/lower/staticwait.vhd \
	test/lower/sum.vhd \
	test/lower/synopsys1.vhd \
	test/lower/tag.vhd \
	test/lower/thunk.vhd \
	test/lower/tounsigned.vhd \
	test/lower/vital1.vhd \
	test/lower/vital2.vhd \
	test/lower/vunit1.vhd \
	test/lower/vunit2.vhd \
	test/lower/vunit3.vhd \
	test/lower/vunit4.vhd \
	test/lower/vunit5.vhd \
	test/lower/wait1.vhd \
	test/lower/while1.vhd \
	test/misc/bufr_test.vhd \
	test/misc/elide.vhd \
	test/misc/kcuart.vhd \
	test/misc/lut4_test.vhd \
	test/misc/ramb_test.vhd \
	test/parse/access.vhd \
	test/parse/alias2.vhd \
	test/parse/alias.vhd \
	test/parse/arch.vhd \
	test/parse/array.vhd \
	test/parse/attr.vhd \
	test/parse/badprimary.vhd \
	test/parse/based.vhd \
	test/parse/bitstring.vhd \
	test/parse/block.vhd \
	test/parse/comp.vhd \
	test/parse/concat.vhd \
	test/parse/conc.vhd \
	test/parse/cond1.vhd \
	test/parse/config.vhd \
	test/parse/context.vhd \
	test/parse/empty.vhd \
	test/parse/entity.vhd \
	test/parse/enum.vhd \
	test/parse/error2.vhd \
	test/parse/error3.vhd \
	test/parse/error4.vhd \
	test/parse/error5.vhd \
	test/parse/error6.vhd \
	test/parse/error7.vhd \
	test/parse/error8.vhd \
	test/parse/error9.vhd \
	test/parse/error.vhd \
	test/parse/explicit.vhd \
	test/parse/expr.vhd \
	test/parse/extended.vhd \
	test/parse/external.vhd \
	test/parse/func.vhd \
	test/parse/generate.vhd \
	test/parse/group.vhd \
	test/parse/guarded.vhd \
	test/parse/homograph.vhd \
	test/parse/implicit.vhd \
	test/parse/instance.vhd \
	test/parse/ir1045.vhd \
	test/parse/issue205.vhd \
	test/parse/issue222.vhd \
	test/parse/issue360.vhd \
	test/parse/issue367.vhd \
	test/parse/issue369.vhd \
	test/parse/issue388.vhd \
	test/parse/issue416.vhd \
	test/parse/issue443.vhd \
	test/parse/issue457.vhd \
	test/parse/issue458.vhd \
	test/parse/issue461.vhd \
	test/parse/issue464.vhd \
	test/parse/issue468.vhd \
	test/parse/issue479.vhd \
	test/parse/literal.vhd \
	test/parse/loc.vhd \
	test/parse/names2.vhd \
	test/parse/names3.vhd \
	test/parse/names.vhd \
	test/parse/osvvm6.vhd \
	test/parse/package.vhd \
	test/parse/procedure.vhd \
	test/parse/process.vhd \
	test/parse/protected2.vhd \
	test/parse/protected.vhd \
	test/parse/qual.vhd \
	test/parse/range1.vhd \
	test/parse/seq.vhd \
	test/parse/spec.vhd \
	test/parse/synth.vhd \
	test/parse/tc1012.vhd \
	test/parse/types.vhd \
	test/parse/typo.vhd \
	test/parse/uvvm1.vhd \
	test/parse/uvvm2.vhd \
	test/parse/vests1.vhd \
	test/parse/vhdl2008.vhd \
	test/parse/visibility1.vhd \
	test/parse/visibility2.vhd \
	test/parse/visibility3.vhd \
	test/parse/visibility4.vhd \
	test/parse/visibility5.vhd \
	test/parse/visibility6.vhd \
	test/parse/vunit5.vhd \
	test/parse/vunit6.vhd \
	test/parse/vunit7.vhd \
	test/parse/vunit8.vhd \
	test/perf/arraycase.vhd \
	test/perf/bigcase.vhd \
	test/perf/bigram.vhd \
	test/perf/dyn_agg.vhd \
	test/perf/grind.vhd \
	test/perf/tounsigned.vhd \
	test/regress/access10.vhd \
	test/regress/access11.vhd \
	test/regress/access1.vhd \
	test/regress/access2.vhd \
	test/regress/access3.vhd \
	test/regress/access4.vhd \
	test/regress/access5.vhd \
	test/regress/access6.vhd \
	test/regress/access7.vhd \
	test/regress/access8.vhd \
	test/regress/access9.vhd \
	test/regress/agg10.vhd \
	test/regress/agg1.vhd \
	test/regress/agg2.vhd \
	test/regress/agg3.vhd \
	test/regress/agg4.vhd \
	test/regress/agg5.vhd \
	test/regress/agg6.vhd \
	test/regress/agg7.vhd \
	test/regress/agg8.vhd \
	test/regress/agg9.vhd \
	test/regress/alias10.vhd \
	test/regress/alias11.vhd \
	test/regress/alias12.vhd \
	test/regress/alias13.vhd \
	test/regress/alias14.vhd \
	test/regress/alias1.vhd \
	test/regress/alias2.vhd \
	test/regress/alias3.vhd \
	test/regress/alias4.vhd \
	test/regress/alias5.vhd \
	test/regress/alias6.vhd \
	test/regress/alias7.vhd \
	test/regress/alias8.vhd \
	test/regress/alias9.vhd \
	test/regress/arith1.vhd \
	test/regress/arith2.vhd \
	test/regress/arith3.vhd \
	test/regress/array10.vhd \
	test/regress/array11.vhd \
	test/regress/array12.vhd \
	test/regress/array13.vhd \
	test/regress/array14.vhd \
	test/regress/array15.vhd \
	test/regress/array1.vhd \
	test/regress/array2.vhd \
	test/regress/array3.vhd \
	test/regress/array4.vhd \
	test/regress/array5.vhd \
	test/regress/array6.vhd \
	test/regress/array7.vhd \
	test/regress/array8.vhd \
	test/regress/array9.vhd \
	test/regress/assert1.vhd \
	test/regress/assert2.vhd \
	test/regress/assert3.vhd \
	test/regress/assert4.vhd \
	test/regress/assert5.vhd \
	test/regress/assert6.vhd \
	test/regress/assert7.vhd \
	test/regress/assign1.vhd \
	test/regress/assign2.vhd \
	test/regress/assign3.vhd \
	test/regress/assign4.vhd \
	test/regress/assign5.vhd \
	test/regress/assign6.vhd \
	test/regress/assign7.vhd \
	test/regress/assign8.vhd \
	test/regress/attr10.vhd \
	test/regress/attr11.vhd \
	test/regress/attr12.vhd \
	test/regress/attr13.vhd \
	test/regress/attr14.vhd \
	test/regress/attr15.vhd \
	test/regress/attr16.vhd \
	test/regress/attr17.vhd \
	test/regress/attr1.vhd \
	test/regress/attr2.vhd \
	test/regress/attr3.vhd \
	test/regress/attr4.vhd \
	test/regress/attr5.vhd \
	test/regress/attr6.vhd \
	test/regress/attr7.vhd \
	test/regress/attr8.vhd \
	test/regress/attr9.vhd \
	test/regress/bitstr1.vhd \
	test/regress/bitvec.vhd \
	test/regress/block1.vhd \
	test/regress/block2.vhd \
	test/regress/bounds10.vhd \
	test/regress/bounds11.vhd \
	test/regress/bounds12.vhd \
	test/regress/bounds13.vhd \
	test/regress/bounds14.vhd \
	test/regress/bounds15.vhd \
	test/regress/bounds16.vhd \
	test/regress/bounds17.vhd \
	test/regress/bounds18.vhd \
	test/regress/bounds19.vhd \
	test/regress/bounds1.vhd \
	test/regress/bounds20.vhd \
	test/regress/bounds21.vhd \
	test/regress/bounds22.vhd \
	test/regress/bounds23.vhd \
	test/regress/bounds24.vhd \
	test/regress/bounds25.vhd \
	test/regress/bounds26.vhd \
	test/regress/bounds27.vhd \
	test/regress/bounds28.vhd \
	test/regress/bounds29.vhd \
	test/regress/bounds2.vhd \
	test/regress/bounds30.vhd \
	test/regress/bounds31.vhd \
	test/regress/bounds32.vhd \
	test/regress/bounds33.vhd \
	test/regress/bounds34.vhd \
	test/regress/bounds35.vhd \
	test/regress/bounds36.vhd \
	test/regress/bounds37.vhd \
	test/regress/bounds38.vhd \
	test/regress/bounds3.vhd \
	test/regress/bounds4.vhd \
	test/regress/bounds5.vhd \
	test/regress/bounds6.vhd \
	test/regress/bounds7.vhd \
	test/regress/bounds8.vhd \
	test/regress/bounds9.vhd \
	test/regress/buffer1.vhd \
	test/regress/case10.vhd \
	test/regress/case11.vhd \
	test/regress/case12.vhd \
	test/regress/case13.vhd \
	test/regress/case1.vhd \
	test/regress/case2.vhd \
	test/regress/case3.vhd \
	test/regress/case4.vhd \
	test/regress/case5.vhd \
	test/regress/case6.vhd \
	test/regress/case7.vhd \
	test/regress/case8.vhd \
	test/regress/case9.vhd \
	test/regress/cmdline1.sh \
	test/regress/cmdline2.sh \
	test/regress/cmdline3.sh \
	test/regress/comp1.vhd \
	test/regress/concat1.vhd \
	test/regress/concat2.vhd \
	test/regress/concat3.vhd \
	test/regress/concat4.vhd \
	test/regress/concat5.vhd \
	test/regress/concat6.vhd \
	test/regress/concat7.vhd \
	test/regress/cond1.vhd \
	test/regress/cond2.vhd \
	test/regress/cond3.vhd \
	test/regress/conf1.vhd \
	test/regress/conf2.vhd \
	test/regress/conf3.vhd \
	test/regress/const1.vhd \
	test/regress/const2.vhd \
	test/regress/const3.vhd \
	test/regress/const4.vhd \
	test/regress/const5.vhd \
	test/regress/const6.vhd \
	test/regress/const7.vhd \
	test/regress/const8.vhd \
	test/regress/const9.vhd \
	test/regress/conv1.vhd \
	test/regress/conv2.vhd \
	test/regress/conv3.vhd \
	test/regress/conv4.vhd \
	test/regress/conv5.vhd \
	test/regress/conv6.vhd \
	test/regress/conv7.vhd \
	test/regress/conv8.vhd \
	test/regress/counter.vhd \
	test/regress/cover1.vhd \
	test/regress/debug1.vhd \
	test/regress/debug2.vhd \
	test/regress/debug3.vhd \
	test/regress/default1.vhd \
	test/regress/default2.vhd \
	test/regress/delay1.vhd \
	test/regress/delay2.vhd \
	test/regress/driver10.vhd \
	test/regress/driver11.vhd \
	test/regress/driver12.vhd \
	test/regress/driver13.vhd \
	test/regress/driver1.vhd \
	test/regress/driver2.vhd \
	test/regress/driver3.vhd \
	test/regress/driver4.vhd \
	test/regress/driver5.vhd \
	test/regress/driver6.vhd \
	test/regress/driver7.vhd \
	test/regress/driver8.vhd \
	test/regress/driver9.vhd \
	test/regress/elab10.vhd \
	test/regress/elab11.vhd \
	test/regress/elab12.vhd \
	test/regress/elab13.vhd \
	test/regress/elab14.vhd \
	test/regress/elab15.vhd \
	test/regress/elab16.vhd \
	test/regress/elab17.vhd \
	test/regress/elab18.vhd \
	test/regress/elab19.vhd \
	test/regress/elab1.vhd \
	test/regress/elab20.vhd \
	test/regress/elab21.vhd \
	test/regress/elab22.vhd \
	test/regress/elab23.vhd \
	test/regress/elab24.vhd \
	test/regress/elab25.vhd \
	test/regress/elab26.vhd \
	test/regress/elab27.vhd \
	test/regress/elab28.vhd \
	test/regress/elab29.vhd \
	test/regress/elab2.vhd \
	test/regress/elab30.vhd \
	test/regress/elab31.vhd \
	test/regress/elab32.vhd \
	test/regress/elab33.vhd \
	test/regress/elab3.vhd \
	test/regress/elab4.vhd \
	test/regress/elab5.vhd \
	test/regress/elab6.vhd \
	test/regress/elab7.vhd \
	test/regress/elab8.vhd \
	test/regress/elab9.vhd \
	test/regress/ename1.vhd \
	test/regress/ename2.vhd \
	test/regress/ename3.vhd \
	test/regress/fact.vhd \
	test/regress/file1.vhd \
	test/regress/file2.vhd \
	test/regress/file3.vhd \
	test/regress/file4.vhd \
	test/regress/file5.vhd \
	test/regress/file6.vhd \
	test/regress/file7.vhd \
	test/regress/file8.vhd \
	test/regress/file9.vhd \
	test/regress/for1.vhd \
	test/regress/for2.vhd \
	test/regress/for3.vhd \
	test/regress/for4.vhd \
	test/regress/force1.vhd \
	test/regress/func10.vhd \
	test/regress/func11.vhd \
	test/regress/func12.vhd \
	test/regress/func13.vhd \
	test/regress/func14.vhd \
	test/regress/func15.vhd \
	test/regress/func16.vhd \
	test/regress/func17.vhd \
	test/regress/func18.vhd \
	test/regress/func19.vhd \
	test/regress/func1.vhd \
	test/regress/func20.vhd \
	test/regress/func2.vhd \
	test/regress/func3.vhd \
	test/regress/func4.vhd \
	test/regress/func5.vhd \
	test/regress/func6.vhd \
	test/regress/func7.vhd \
	test/regress/func8.vhd \
	test/regress/func9.vhd \
	test/regress/generic1.vhd \
	test/regress/genpack10.vhd \
	test/regress/genpack11.vhd \
	test/regress/genpack1.vhd \
	test/regress/genpack2.vhd \
	test/regress/genpack3.vhd \
	test/regress/genpack4.vhd \
	test/regress/genpack5.vhd \
	test/regress/genpack6.vhd \
	test/regress/genpack7.vhd \
	test/regress/genpack8.vhd \
	test/regress/genpack9.vhd \
	test/regress/gensub1.vhd \
	test/regress/gensub2.vhd \
	test/regress/gensub3.vhd \
	test/regress/gensub4.vhd \
	test/regress/gensub5.vhd \
	test/regress/gensub6.vhd \
	test/regress/gentype1.vhd \
	test/regress/gentype2.vhd \
	test/regress/gentype3.vhd \
	test/regress/gentype4.vhd \
	test/regress/gold/access10.txt \
	test/regress/gold/access1.txt \
	test/regress/gold/access6.txt \
	test/regress/gold/access8.txt \
	test/regress/gold/alias12.txt \
	test/regress/gold/alias1.txt \
	test/regress/gold/alias2.txt \
	test/regress/gold/alias5.txt \
	test/regress/gold/arith2.txt \
	test/regress/gold/array15.txt \
	test/regress/gold/assert1.txt \
	test/regress/gold/assert2.txt \
	test/regress/gold/assert3.txt \
	test/regress/gold/assert6.txt \
	test/regress/gold/assert7.txt \
	test/regress/gold/attr12.txt \
	test/regress/gold/attr17.txt \
	test/regress/gold/attr3.txt \
	test/regress/gold/bounds10.txt \
	test/regress/gold/bounds11.txt \
	test/regress/gold/bounds12.txt \
	test/regress/gold/bounds13.txt \
	test/regress/gold/bounds14.txt \
	test/regress/gold/bounds15.txt \
	test/regress/gold/bounds16.txt \
	test/regress/gold/bounds17.txt \
	test/regress/gold/bounds18.txt \
	test/regress/gold/bounds19.txt \
	test/regress/gold/bounds1.txt \
	test/regress/gold/bounds20.txt \
	test/regress/gold/bounds21.txt \
	test/regress/gold/bounds22.txt \
	test/regress/gold/bounds23.txt \
	test/regress/gold/bounds24.txt \
	test/regress/gold/bounds25.txt \
	test/regress/gold/bounds26.txt \
	test/regress/gold/bounds27.txt \
	test/regress/gold/bounds28.txt \
	test/regress/gold/bounds29.txt \
	test/regress/gold/bounds2.txt \
	test/regress/gold/bounds30.txt \
	test/regress/gold/bounds31.txt \
	test/regress/gold/bounds32.txt \
	test/regress/gold/bounds33.txt \
	test/regress/gold/bounds34.txt \
	test/regress/gold/bounds35.txt \
	test/regress/gold/bounds36.txt \
	test/regress/gold/bounds37.txt \
	test/regress/gold/bounds38.txt \
	test/regress/gold/bounds3.txt \
	test/regress/gold/bounds4.txt \
	test/regress/gold/bounds5.txt \
	test/regress/gold/bounds6.txt \
	test/regress/gold/bounds7.txt \
	test/regress/gold/bounds8.txt \
	test/regress/gold/bounds9.txt \
	test/regress/gold/case12.txt \
	test/regress/gold/case13.txt \
	test/regress/gold/case5.txt \
	test/regress/gold/cond1.txt \
	test/regress/gold/cond2.txt \
	test/regress/gold/conf1.txt \
	test/regress/gold/conf2.txt \
	test/regress/gold/const3.txt \
	test/regress/gold/counter.txt \
	test/regress/gold/cover1.txt \
	test/regress/gold/debug1.txt \
	test/regress/gold/debug2.txt \
	test/regress/gold/debug3.txt \
	test/regress/gold/driver7.txt \
	test/regress/gold/driver9.txt \
	test/regress/gold/elab10.txt \
	test/regress/gold/elab13.txt \
	test/regress/gold/elab3.txt \
	test/regress/gold/elab9.txt \
	test/regress/gold/ename2.txt \
	test/regress/gold/fact.txt \
	test/regress/gold/file8.txt \
	test/regress/gold/for1.txt \
	test/regress/gold/for2.txt \
	test/regress/gold/for3.txt \
	test/regress/gold/func19.txt \
	test/regress/gold/ieee9.txt \
	test/regress/gold/image.txt \
	test/regress/gold/issue101.txt \
	test/regress/gold/issue103.txt \
	test/regress/gold/issue110.txt \
	test/regress/gold/issue185.txt \
	test/regress/gold/issue202.txt \
	test/regress/gold/issue225.txt \
	test/regress/gold/issue227.txt \
	test/regress/gold/issue228.txt \
	test/regress/gold/issue234.txt \
	test/regress/gold/issue308.txt \
	test/regress/gold/issue351.txt \
	test/regress/gold/issue377.txt \
	test/regress/gold/issue433.txt \
	test/regress/gold/issue454.dump \
	test/regress/gold/issue45.txt \
	test/regress/gold/issue469.txt \
	test/regress/gold/issue494.txt \
	test/regress/gold/issue96.txt \
	test/regress/gold/proc7.txt \
	test/regress/gold/proc8.txt \
	test/regress/gold/range1.txt \
	test/regress/gold/real1.txt \
	test/regress/gold/real3.txt \
	test/regress/gold/signal11.txt \
	test/regress/gold/signal23.txt \
	test/regress/gold/signal6.txt \
	test/regress/gold/stop1.txt \
	test/regress/gold/stop2.txt \
	test/regress/gold/textio1.txt \
	test/regress/gold/textio5.txt \
	test/regress/gold/vhpi1.txt \
	test/regress/gold/wait12.txt \
	test/regress/gold/wait2.txt \
	test/regress/gold/wait6.txt \
	test/regress/gold/wave1.dump \
	test/regress/gold/wave2.dump \
	test/regress/gold/wave3.dump \
	test/regress/gold/wave4.dump \
	test/regress/gold/wave5.dump \
	test/regress/gold/wave6.dump \
	test/regress/gold/while1.txt \
	test/regress/grlib1.vhd \
	test/regress/guard1.vhd \
	test/regress/guard2.vhd \
	test/regress/ieee1.vhd \
	test/regress/ieee2.vhd \
	test/regress/ieee3.vhd \
	test/regress/ieee4.vhd \
	test/regress/ieee5.vhd \
	test/regress/ieee6.vhd \
	test/regress/ieee7.vhd \
	test/regress/ieee8.vhd \
	test/regress/ieee9.vhd \
	test/regress/image.vhd \
	test/regress/implicit1.vhd \
	test/regress/implicit2.vhd \
	test/regress/implicit3.vhd \
	test/regress/implicit4.vhd \
	test/regress/issue101.vhd \
	test/regress/issue103.vhd \
	test/regress/issue104.vhd \
	test/regress/issue106.vhd \
	test/regress/issue109.vhd \
	test/regress/issue10.vhd \
	test/regress/issue110.vhd \
	test/regress/issue111.vhd \
	test/regress/issue112.vhd \
	test/regress/issue115.vhd \
	test/regress/issue116.vhd \
	test/regress/issue121.vhd \
	test/regress/issue122.vhd \
	test/regress/issue123.vhd \
	test/regress/issue126.vhd \
	test/regress/issue13.vhd \
	test/regress/issue141.vhd \
	test/regress/issue143.vhd \
	test/regress/issue146.vhd \
	test/regress/issue148.vhd \
	test/regress/issue152.vhd \
	test/regress/issue153.vhd \
	test/regress/issue163.vhd \
	test/regress/issue169.vhd \
	test/regress/issue16.vhd \
	test/regress/issue183.vhd \
	test/regress/issue185.vhd \
	test/regress/issue186.vhd \
	test/regress/issue187.vhd \
	test/regress/issue18.vhd \
	test/regress/issue194.vhd \
	test/regress/issue196.vhd \
	test/regress/issue197.vhd \
	test/regress/issue200.vhd \
	test/regress/issue201.vhd \
	test/regress/issue202.vhd \
	test/regress/issue204.vhd \
	test/regress/issue206.vhd \
	test/regress/issue217.vhd \
	test/regress/issue225.vhd \
	test/regress/issue227.vhd \
	test/regress/issue228.vhd \
	test/regress/issue229.vhd \
	test/regress/issue234.vhd \
	test/regress/issue262.vhd \
	test/regress/issue284.vhd \
	test/regress/issue293.vhd \
	test/regress/issue29.vhd \
	test/regress/issue308.vhd \
	test/regress/issue309.vhd \
	test/regress/issue315.vhd \
	test/regress/issue323.vhd \
	test/regress/issue327.vhd \
	test/regress/issue335.vhd \
	test/regress/issue338b.vhd \
	test/regress/issue338.vhd \
	test/regress/issue340.vhd \
	test/regress/issue348.vhd \
	test/regress/issue349.vhd \
	test/regress/issue351.vhd \
	test/regress/issue352.vhd \
	test/regress/issue354.vhd \
	test/regress/issue367.vhd \
	test/regress/issue369.vhd \
	test/regress/issue370.vhd \
	test/regress/issue371.vhd \
	test/regress/issue376.vhd \
	test/regress/issue377.vhd \
	test/regress/issue38.vhd \
	test/regress/issue397.vhd \
	test/regress/issue405.vhd \
	test/regress/issue407.vhd \
	test/regress/issue412.vhd \
	test/regress/issue414.vhd \
	test/regress/issue415.vhd \
	test/regress/issue420.vhd \
	test/regress/issue423.vhd \
	test/regress/issue428.vhd \
	test/regress/issue429.vhd \
	test/regress/issue430.vhd \
	test/regress/issue432.vhd \
	test/regress/issue433.vhd \
	test/regress/issue434.vhd \
	test/regress/issue447.vhd \
	test/regress/issue454.sh \
	test/regress/issue454.vhd \
	test/regress/issue45.vhd \
	test/regress/issue460.vhd \
	test/regress/issue467.vhd \
	test/regress/issue469.vhd \
	test/regress/issue472.sh \
	test/regress/issue481.vhd \
	test/regress/issue483.vhd \
	test/regress/issue484.vhd \
	test/regress/issue493.sh \
	test/regress/issue494.vhd \
	test/regress/issue497.vhd \
	test/regress/issue53.vhd \
	test/regress/issue56.vhd \
	test/regress/issue57.vhd \
	test/regress/issue59.vhd \
	test/regress/issue60.vhd \
	test/regress/issue63.vhd \
	test/regress/issue69.vhd \
	test/regress/issue70.vhd \
	test/regress/issue72.vhd \
	test/regress/issue79.vhd \
	test/regress/issue82.vhd \
	test/regress/issue83.vhd \
	test/regress/issue84.vhd \
	test/regress/issue86.vhd \
	test/regress/issue8.vhd \
	test/regress/issue90.vhd \
	test/regress/issue91.vhd \
	test/regress/issue94.vhd \
	test/regress/issue95.vhd \
	test/regress/issue96.vhd \
	test/regress/issue98.vhd \
	test/regress/issue9.vhd \
	test/regress/jcore1.vhd \
	test/regress/jcore2.vhd \
	test/regress/jcore3.vhd \
	test/regress/jcore4.vhd \
	test/regress/jcore5.vhd \
	test/regress/jcore6.vhd \
	test/regress/lfsr.vhd \
	test/regress/libdir1.sh \
	test/regress/libdir2.sh \
	test/regress/link1.vhd \
	test/regress/link2.vhd \
	test/regress/link3.sh \
	test/regress/link3.vhd \
	test/regress/logical1.vhd \
	test/regress/logical2.vhd \
	test/regress/logical3.vhd \
	test/regress/loop1.vhd \
	test/regress/null1.vhd \
	test/regress/null2.vhd \
	test/regress/operator1.vhd \
	test/regress/operator2.vhd \
	test/regress/operator3.vhd \
	test/regress/operator4.vhd \
	test/regress/operator5.vhd \
	test/regress/order1.vhd \
	test/regress/order2.sh \
	test/regress/predef1.vhd \
	test/regress/predef2.vhd \
	test/regress/proc10.vhd \
	test/regress/proc11.vhd \
	test/regress/proc12.vhd \
	test/regress/proc1.vhd \
	test/regress/proc2.vhd \
	test/regress/proc3.vhd \
	test/regress/proc4.vhd \
	test/regress/proc5.vhd \
	test/regress/proc6.vhd \
	test/regress/proc7.vhd \
	test/regress/proc8.vhd \
	test/regress/proc9.vhd \
	test/regress/protected1.vhd \
	test/regress/protected2.vhd \
	test/regress/protected3.vhd \
	test/regress/protected4.vhd \
	test/regress/protected5.vhd \
	test/regress/protected6.vhd \
	test/regress/protected7.vhd \
	test/regress/ram1.vhd \
	test/regress/range1.vhd \
	test/regress/real1.vhd \
	test/regress/real2.vhd \
	test/regress/real3.vhd \
	test/regress/record10.vhd \
	test/regress/record11.vhd \
	test/regress/record12.vhd \
	test/regress/record13.vhd \
	test/regress/record14.vhd \
	test/regress/record15.vhd \
	test/regress/record16.vhd \
	test/regress/record17.vhd \
	test/regress/record18.vhd \
	test/regress/record19.vhd \
	test/regress/record1.vhd \
	test/regress/record20.vhd \
	test/regress/record21.vhd \
	test/regress/record22.vhd \
	test/regress/record23.vhd \
	test/regress/record24.vhd \
	test/regress/record25.vhd \
	test/regress/record26.vhd \
	test/regress/record27.vhd \
	test/regress/record28.vhd \
	test/regress/record29.vhd \
	test/regress/record2.vhd \
	test/regress/record30.vhd \
	test/regress/record31.vhd \
	test/regress/record32.vhd \
	test/regress/record33.vhd \
	test/regress/record34.vhd \
	test/regress/record35.vhd \
	test/regress/record36.vhd \
	test/regress/record3.vhd \
	test/regress/record4.vhd \
	test/regress/record5.vhd \
	test/regress/record6.vhd \
	test/regress/record7.vhd \
	test/regress/record8.vhd \
	test/regress/record9.vhd \
	test/regress/shared1.vhd \
	test/regress/shared2.vhd \
	test/regress/shared3.vhd \
	test/regress/shared4.vhd \
	test/regress/shift1.vhd \
	test/regress/shift2.vhd \
	test/regress/signal10.vhd \
	test/regress/signal11.vhd \
	test/regress/signal12.vhd \
	test/regress/signal13.vhd \
	test/regress/signal14.vhd \
	test/regress/signal15.vhd \
	test/regress/signal16.vhd \
	test/regress/signal17.vhd \
	test/regress/signal18.vhd \
	test/regress/signal19.vhd \
	test/regress/signal1.vhd \
	test/regress/signal20.vhd \
	test/regress/signal21.vhd \
	test/regress/signal22.vhd \
	test/regress/signal23.vhd \
	test/regress/signal24.vhd \
	test/regress/signal25.vhd \
	test/regress/signal26.vhd \
	test/regress/signal2.vhd \
	test/regress/signal3.vhd \
	test/regress/signal4.vhd \
	test/regress/signal5.vhd \
	test/regress/signal6.vhd \
	test/regress/signal7.vhd \
	test/regress/signal8.vhd \
	test/regress/signal9.vhd \
	test/regress/slice1.vhd \
	test/regress/slice2.vhd \
	test/regress/slice3.vhd \
	test/regress/slice4.vhd \
	test/regress/stack1.vhd \
	test/regress/stop1.vhd \
	test/regress/synopsys1.vhd \
	test/regress/testlist.txt \
	test/regress/textio1.vhd \
	test/regress/textio2.vhd \
	test/regress/textio3.vhd \
	test/regress/textio4.vhd \
	test/regress/textio5.vhd \
	test/regress/textio6.vhd \
	test/regress/textio7.vhd \
	test/regress/textio8.vhd \
	test/regress/toplevel1.vhd \
	test/regress/toplevel2.vhd \
	test/regress/vecorder.vhd \
	test/regress/vests10.vhd \
	test/regress/vests11.vhd \
	test/regress/vests12.vhd \
	test/regress/vests13.vhd \
	test/regress/vests14.vhd \
	test/regress/vests15.vhd \
	test/regress/vests16.vhd \
	test/regress/vests17.vhd \
	test/regress/vests18.vhd \
	test/regress/vests19.vhd \
	test/regress/vests1.vhd \
	test/regress/vests20.vhd \
	test/regress/vests21.vhd \
	test/regress/vests22.vhd \
	test/regress/vests23.vhd \
	test/regress/vests24.vhd \
	test/regress/vests25.vhd \
	test/regress/vests26.vhd \
	test/regress/vests27.vhd \
	test/regress/vests28.vhd \
	test/regress/vests29.vhd \
	test/regress/vests2.vhd \
	test/regress/vests30.vhd \
	test/regress/vests31.vhd \
	test/regress/vests32.vhd \
	test/regress/vests33.vhd \
	test/regress/vests34.vhd \
	test/regress/vests35.vhd \
	test/regress/vests36.vhd \
	test/regress/vests37.vhd \
	test/regress/vests38.vhd \
	test/regress/vests39.vhd \
	test/regress/vests3.vhd \
	test/regress/vests40.vhd \
	test/regress/vests41.vhd \
	test/regress/vests42.vhd \
	test/regress/vests43.vhd \
	test/regress/vests44.vhd \
	test/regress/vests45.vhd \
	test/regress/vests4.vhd \
	test/regress/vests5.vhd \
	test/regress/vests6.vhd \
	test/regress/vests7.vhd \
	test/regress/vests8.vhd \
	test/regress/vests9.vhd \
	test/regress/vhpi1.vhd \
	test/regress/vhpi2.vhd \
	test/regress/vhpi3.vhd \
	test/regress/vhpi4.vhd \
	test/regress/vhpi5.vhd \
	test/regress/wait10.vhd \
	test/regress/wait11.vhd \
	test/regress/wait12.vhd \
	test/regress/wait13.vhd \
	test/regress/wait14.vhd \
	test/regress/wait15.vhd \
	test/regress/wait16.vhd \
	test/regress/wait17.vhd \
	test/regress/wait18.vhd \
	test/regress/wait19.vhd \
	test/regress/wait1.vhd \
	test/regress/wait20.vhd \
	test/regress/wait21.vhd \
	test/regress/wait22.vhd \
	test/regress/wait23.vhd \
	test/regress/wait24.vhd \
	test/regress/wait2.vhd \
	test/regress/wait3.vhd \
	test/regress/wait4.vhd \
	test/regress/wait5.vhd \
	test/regress/wait6.vhd \
	test/regress/wait7.vhd \
	test/regress/wait8.vhd \
	test/regress/wait9.vhd \
	test/regress/wave1.sh \
	test/regress/wave1.vhd \
	test/regress/wave2.sh \
	test/regress/wave2.vhd \
	test/regress/wave3.sh \
	test/regress/wave3.vhd \
	test/regress/wave4.sh \
	test/regress/wave4.vhd \
	test/regress/wave5.sh \
	test/regress/wave5.vhd \
	test/regress/wave6.sh \
	test/regress/wave6.vhd \
	test/regress/while1.vhd \
	test/sem/access.vhd \
	test/sem/afunc.vhd \
	test/sem/agg2008.vhd \
	test/sem/alias.vhd \
	test/sem/ambiguous.vhd \
	test/sem/array.vhd \
	test/sem/assert.vhd \
	test/sem/attr.vhd \
	test/sem/block.vhd \
	test/sem/concat.vhd \
	test/sem/conc.vhd \
	test/sem/config.vhd \
	test/sem/const2.vhd \
	test/sem/const.vhd \
	test/sem/context.vhd \
	test/sem/conv.vhd \
	test/sem/driving.vhd \
	test/sem/duplicate.vhd \
	test/sem/dwlau.vhd \
	test/sem/ename.vhd \
	test/sem/entity.vhd \
	test/sem/error1.vhd \
	test/sem/error2.vhd \
	test/sem/error3.vhd \
	test/sem/file_and_access.vhd \
	test/sem/file.vhd \
	test/sem/force.vhd \
	test/sem/foreign1.vhd \
	test/sem/func.vhd \
	test/sem/generate.vhd \
	test/sem/generics2008.vhd \
	test/sem/generics.vhd \
	test/sem/genpack.vhd \
	test/sem/gensub2.vhd \
	test/sem/gensub.vhd \
	test/sem/gentype.vhd \
	test/sem/implicit.vhd \
	test/sem/integer.vhd \
	test/sem/interfaces.vhd \
	test/sem/issue102.vhd \
	test/sem/issue105.vhd \
	test/sem/issue128.vhd \
	test/sem/issue130.vhd \
	test/sem/issue131.vhd \
	test/sem/issue132.vhd \
	test/sem/issue133.vhd \
	test/sem/issue140.vhd \
	test/sem/issue144.vhd \
	test/sem/issue151.vhd \
	test/sem/issue162.vhd \
	test/sem/issue165.vhd \
	test/sem/issue173.vhd \
	test/sem/issue174.vhd \
	test/sem/issue176.vhd \
	test/sem/issue177.vhd \
	test/sem/issue178.vhd \
	test/sem/issue188.vhd \
	test/sem/issue197.vhd \
	test/sem/issue201.vhd \
	test/sem/issue219.vhd \
	test/sem/issue220.vhd \
	test/sem/issue221.vhd \
	test/sem/issue224.vhd \
	test/sem/issue225.vhd \
	test/sem/issue226.vhd \
	test/sem/issue232.vhd \
	test/sem/issue236.vhd \
	test/sem/issue239.vhd \
	test/sem/issue246.vhd \
	test/sem/issue264.vhd \
	test/sem/issue276.vhd \
	test/sem/issue293.vhd \
	test/sem/issue311.vhd \
	test/sem/issue316.vhd \
	test/sem/issue326.vhd \
	test/sem/issue340.vhd \
	test/sem/issue341.vhd \
	test/sem/issue350.vhd \
	test/sem/issue356.vhd \
	test/sem/issue359a.vhd \
	test/sem/issue359.vhd \
	test/sem/issue363.vhd \
	test/sem/issue368.vhd \
	test/sem/issue369.vhd \
	test/sem/issue377.vhd \
	test/sem/issue386.vhd \
	test/sem/issue407.vhd \
	test/sem/issue465.vhd \
	test/sem/issue482.vhd \
	test/sem/issue52.vhd \
	test/sem/issue53.vhd \
	test/sem/issue58.vhd \
	test/sem/issue88.vhd \
	test/sem/issue89.vhd \
	test/sem/jcore1.vhd \
	test/sem/linkage.vhd \
	test/sem/mcase.vhd \
	test/sem/murax.vhd \
	test/sem/osvvm1.vhd \
	test/sem/osvvm2.vhd \
	test/sem/osvvm3.vhd \
	test/sem/osvvm4.vhd \
	test/sem/osvvm5.vhd \
	test/sem/physical.vhd \
	test/sem/ports2008.vhd \
	test/sem/ports.vhd \
	test/sem/procedure.vhd \
	test/sem/protected2.vhd \
	test/sem/protected.vhd \
	test/sem/real.vhd \
	test/sem/record2008.vhd \
	test/sem/record.vhd \
	test/sem/resolution.vhd \
	test/sem/scope.vhd \
	test/sem/seq.vhd \
	test/sem/signal.vhd \
	test/sem/spec.vhd \
	test/sem/static.vhd \
	test/sem/std.vhd \
	test/sem/subtype.vhd \
	test/sem/supersede.vhd \
	test/sem/tc251.vhd \
	test/sem/tc792.vhd \
	test/sem/textio.vhd \
	test/sem/universal.vhd \
	test/sem/use.vhd \
	test/sem/varinit.vhd \
	test/sem/vests1.vhd \
	test/sem/vhdl2008.vhd \
	test/sem/vital1.vhd \
	test/sem/wait.vhd \
	test/simp/allsens.vhd \
	test/simp/args.vhd \
	test/simp/cfold.vhd \
	test/simp/concat.vhd \
	test/simp/condvar.vhd \
	test/simp/constarr.vhd \
	test/simp/context.vhd \
	test/simp/copysub.vhd \
	test/simp/ffold2.vhd \
	test/simp/ffold.vhd \
	test/simp/foreign1.vhd \
	test/simp/func9.vhd \
	test/simp/genmap.vhd \
	test/simp/genpack1.vhd \
	test/simp/gentype.vhd \
	test/simp/grlib1.vhd \
	test/simp/guard.vhd \
	test/simp/issue155.vhd \
	test/simp/issue194.vhd \
	test/simp/issue212.vhd \
	test/simp/issue309.vhd \
	test/simp/issue320.vhd \
	test/simp/issue321.vhd \
	test/simp/issue322.vhd \
	test/simp/issue331.vhd \
	test/simp/issue332.vhd \
	test/simp/issue344.vhd \
	test/simp/issue345.vhd \
	test/simp/issue362.vhd \
	test/simp/issue425.vhd \
	test/simp/issue436.vhd \
	test/simp/issue437.vhd \
	test/simp/issue438.vhd \
	test/simp/issue496.vhd \
	test/simp/issue49.vhd \
	test/simp/order1.vhd \
	test/simp/osvvm4.vhd \
	test/simp/ports2008.vhd \
	test/simp/predef.vhd \
	test/simp/proc.vhd \
	test/simp/protfold1.vhd \
	test/simp/protfold2.vhd \
	test/simp/recrange.vhd \
	test/simp/shift2.vhd \
	test/simp/simpif1.vhd \
	test/simp/static1.vhd \
	test/simp/table.vhd \
	test/simp/use.vhd
