# Generated automatically, do not edit.
EXTRA_DIST += \
	test/bounds/bounds2.vhd \
	test/bounds/bounds.vhd \
	test/bounds/case.vhd \
	test/bounds/issue150.vhd \
	test/bounds/issue200.vhd \
	test/bounds/issue208.vhd \
	test/bounds/issue247.vhd \
	test/bounds/issue269.vhd \
	test/bounds/issue307b.vhd \
	test/bounds/issue356.vhd \
	test/bounds/issue36.vhd \
	test/bounds/issue54.vhd \
	test/bounds/issue99.vhd \
	test/elab/block1.vhd \
	test/elab/bounds10.vhd \
	test/elab/comp.vhd \
	test/elab/const1.vhd \
	test/elab/copy1.vhd \
	test/elab/elab1.vhd \
	test/elab/elab2.vhd \
	test/elab/elab3.vhd \
	test/elab/elab4.vhd \
	test/elab/eval1.vhd \
	test/elab/gbounds.vhd \
	test/elab/genagg.vhd \
	test/elab/ifgen.vhd \
	test/elab/issue153.vhd \
	test/elab/issue157.vhd \
	test/elab/issue159.vhd \
	test/elab/issue175.vhd \
	test/elab/issue17.vhd \
	test/elab/issue184.vhd \
	test/elab/issue19.vhd \
	test/elab/issue232.vhd \
	test/elab/issue251.vhd \
	test/elab/issue305.vhd \
	test/elab/issue307.vhd \
	test/elab/issue315.vhd \
	test/elab/issue325.vhd \
	test/elab/issue328.vhd \
	test/elab/issue330.vhd \
	test/elab/issue336.vhd \
	test/elab/issue373.vhd \
	test/elab/issue374.vhd \
	test/elab/issue404.vhd \
	test/elab/issue93.vhd \
	test/elab/jcore1.vhd \
	test/elab/libbind2.vhd \
	test/elab/libbind3.vhd \
	test/elab/libbind.vhd \
	test/elab/open2.vhd \
	test/elab/opencase.vhd \
	test/elab/openinout.vhd \
	test/elab/open.vhd \
	test/elab/record.vhd \
	test/elab/toplevel2.vhd \
	test/expect.vhd \
	test/group/array3.vhd \
	test/group/arrayref1.vhd \
	test/group/arrayref2.vhd \
	test/group/arrayref3.vhd \
	test/group/issue250.vhd \
	test/group/issue371.vhd \
	test/group/issue72.vhd \
	test/group/issue73.vhd \
	test/group/issue95.vhd \
	test/group/jcore2.vhd \
	test/group/jcore4.vhd \
	test/group/recref1.vhd \
	test/group/recref2.vhd \
	test/group/slice1.vhd \
	test/json/pragma.vhd \
	test/lower/access1.vhd \
	test/lower/access2.vhd \
	test/lower/access_bug.vhd \
	test/lower/arith1.vhd \
	test/lower/array1.vhd \
	test/lower/arrayop1.vhd \
	test/lower/assert1.vhd \
	test/lower/assign1.vhd \
	test/lower/assign2.vhd \
	test/lower/assign3.vhd \
	test/lower/attr1.vhd \
	test/lower/bounds1.vhd \
	test/lower/case1.vhd \
	test/lower/choice1.vhd \
	test/lower/cond1.vhd \
	test/lower/const1.vhd \
	test/lower/const2.vhd \
	test/lower/cover.vhd \
	test/lower/dealloc.vhd \
	test/lower/extern1.vhd \
	test/lower/func1.vhd \
	test/lower/func5.vhd \
	test/lower/funcif.vhd \
	test/lower/hintbug.vhd \
	test/lower/iffold.vhd \
	test/lower/incomplete.vhd \
	test/lower/issue116.vhd \
	test/lower/issue122.vhd \
	test/lower/issue124.vhd \
	test/lower/issue125.vhd \
	test/lower/issue134.vhd \
	test/lower/issue135.vhd \
	test/lower/issue136.vhd \
	test/lower/issue149.vhd \
	test/lower/issue158.vhd \
	test/lower/issue164.vhd \
	test/lower/issue167.vhd \
	test/lower/issue181.vhd \
	test/lower/issue203.vhd \
	test/lower/issue215.vhd \
	test/lower/issue303.vhd \
	test/lower/issue324.vhd \
	test/lower/issue333.vhd \
	test/lower/issue338b.vhd \
	test/lower/issue338.vhd \
	test/lower/issue347.vhd \
	test/lower/issue351.vhd \
	test/lower/issue357.vhd \
	test/lower/issue389.vhd \
	test/lower/issue94.vhd \
	test/lower/loop1.vhd \
	test/lower/loop2.vhd \
	test/lower/memset.vhd \
	test/lower/mulphys.vhd \
	test/lower/nest1.vhd \
	test/lower/pack1.vhd \
	test/lower/proc1.vhd \
	test/lower/proc3.vhd \
	test/lower/proc7.vhd \
	test/lower/real1.vhd \
	test/lower/record1.vhd \
	test/lower/record6.vhd \
	test/lower/rectype.vhd \
	test/lower/signal11.vhd \
	test/lower/signal1.vhd \
	test/lower/signal2.vhd \
	test/lower/signal4.vhd \
	test/lower/sigvar.vhd \
	test/lower/slice1.vhd \
	test/lower/staticwait.vhd \
	test/lower/sum.vhd \
	test/lower/synopsys1.vhd \
	test/lower/tag.vhd \
	test/lower/thunk.vhd \
	test/lower/tounsigned.vhd \
	test/lower/vital1.vhd \
	test/lower/wait1.vhd \
	test/lower/while1.vhd \
	test/misc/bufr_test.vhd \
	test/misc/elide.vhd \
	test/misc/kcuart.vhd \
	test/misc/lut4_test.vhd \
	test/misc/ramb_test.vhd \
	test/parse/access.vhd \
	test/parse/alias.vhd \
	test/parse/arch.vhd \
	test/parse/array.vhd \
	test/parse/attr.vhd \
	test/parse/based.vhd \
	test/parse/bitstring.vhd \
	test/parse/block.vhd \
	test/parse/comp.vhd \
	test/parse/concat.vhd \
	test/parse/conc.vhd \
	test/parse/cond1.vhd \
	test/parse/config.vhd \
	test/parse/context.vhd \
	test/parse/empty.vhd \
	test/parse/entity.vhd \
	test/parse/enum.vhd \
	test/parse/error2.vhd \
	test/parse/error.vhd \
	test/parse/expr.vhd \
	test/parse/extended.vhd \
	test/parse/func.vhd \
	test/parse/generate.vhd \
	test/parse/guarded.vhd \
	test/parse/implicit.vhd \
	test/parse/instance.vhd \
	test/parse/ir1045.vhd \
	test/parse/issue205.vhd \
	test/parse/issue222.vhd \
	test/parse/issue360.vhd \
	test/parse/issue367.vhd \
	test/parse/issue369.vhd \
	test/parse/issue388.vhd \
	test/parse/literal.vhd \
	test/parse/loc.vhd \
	test/parse/names.vhd \
	test/parse/package.vhd \
	test/parse/pragma.vhd \
	test/parse/procedure.vhd \
	test/parse/process.vhd \
	test/parse/protected.vhd \
	test/parse/qual.vhd \
	test/parse/seq.vhd \
	test/parse/spec.vhd \
	test/parse/synth.vhd \
	test/parse/types.vhd \
	test/parse/vests1.vhd \
	test/perf/arraycase.vhd \
	test/perf/bigram.vhd \
	test/perf/dyn_agg.vhd \
	test/perf/tounsigned.vhd \
	test/regress/access1.vhd \
	test/regress/access2.vhd \
	test/regress/access3.vhd \
	test/regress/access4.vhd \
	test/regress/access5.vhd \
	test/regress/access6.vhd \
	test/regress/access7.vhd \
	test/regress/agg1.vhd \
	test/regress/agg2.vhd \
	test/regress/agg3.vhd \
	test/regress/agg4.vhd \
	test/regress/agg5.vhd \
	test/regress/agg6.vhd \
	test/regress/alias1.vhd \
	test/regress/alias2.vhd \
	test/regress/alias3.vhd \
	test/regress/alias4.vhd \
	test/regress/alias5.vhd \
	test/regress/alias6.vhd \
	test/regress/alias7.vhd \
	test/regress/alias8.vhd \
	test/regress/alias9.vhd \
	test/regress/arith1.vhd \
	test/regress/arith2.vhd \
	test/regress/arith3.vhd \
	test/regress/array1.vhd \
	test/regress/array2.vhd \
	test/regress/array3.vhd \
	test/regress/array4.vhd \
	test/regress/assert1.vhd \
	test/regress/assert2.vhd \
	test/regress/assert3.vhd \
	test/regress/assert4.vhd \
	test/regress/assert5.vhd \
	test/regress/assign1.vhd \
	test/regress/assign2.vhd \
	test/regress/assign3.vhd \
	test/regress/attr10.vhd \
	test/regress/attr11.vhd \
	test/regress/attr12.vhd \
	test/regress/attr1.vhd \
	test/regress/attr2.vhd \
	test/regress/attr3.vhd \
	test/regress/attr4.vhd \
	test/regress/attr5.vhd \
	test/regress/attr6.vhd \
	test/regress/attr7.vhd \
	test/regress/attr8.vhd \
	test/regress/attr9.vhd \
	test/regress/binary_files.vhd \
	test/regress/bitvec.vhd \
	test/regress/block1.vhd \
	test/regress/block2.vhd \
	test/regress/bounds10.vhd \
	test/regress/bounds11.vhd \
	test/regress/bounds12.vhd \
	test/regress/bounds13.vhd \
	test/regress/bounds14.vhd \
	test/regress/bounds15.vhd \
	test/regress/bounds16.vhd \
	test/regress/bounds17.vhd \
	test/regress/bounds1.vhd \
	test/regress/bounds2.vhd \
	test/regress/bounds3.vhd \
	test/regress/bounds4.vhd \
	test/regress/bounds5.vhd \
	test/regress/bounds6.vhd \
	test/regress/bounds7.vhd \
	test/regress/bounds8.vhd \
	test/regress/bounds9.vhd \
	test/regress/case1.vhd \
	test/regress/case2.vhd \
	test/regress/case3.vhd \
	test/regress/case4.vhd \
	test/regress/case5.vhd \
	test/regress/case6.vhd \
	test/regress/case7.vhd \
	test/regress/comp1.vhd \
	test/regress/concat1.vhd \
	test/regress/concat2.vhd \
	test/regress/concat3.vhd \
	test/regress/concat4.vhd \
	test/regress/concat5.vhd \
	test/regress/cond1.vhd \
	test/regress/cond2.vhd \
	test/regress/cond3.vhd \
	test/regress/const1.vhd \
	test/regress/const2.vhd \
	test/regress/const3.vhd \
	test/regress/const4.vhd \
	test/regress/const5.vhd \
	test/regress/const6.vhd \
	test/regress/const7.vhd \
	test/regress/conv1.vhd \
	test/regress/counter.vhd \
	test/regress/cover1.vhd \
	test/regress/default1.vhd \
	test/regress/delay1.vhd \
	test/regress/delay2.vhd \
	test/regress/driver1.vhd \
	test/regress/driver2.vhd \
	test/regress/driver3.vhd \
	test/regress/driver4.vhd \
	test/regress/driver5.vhd \
	test/regress/elab10.vhd \
	test/regress/elab11.vhd \
	test/regress/elab12.vhd \
	test/regress/elab13.vhd \
	test/regress/elab14.vhd \
	test/regress/elab15.vhd \
	test/regress/elab16.vhd \
	test/regress/elab17.vhd \
	test/regress/elab18.vhd \
	test/regress/elab19.vhd \
	test/regress/elab1.vhd \
	test/regress/elab20.vhd \
	test/regress/elab21.vhd \
	test/regress/elab22.vhd \
	test/regress/elab23.vhd \
	test/regress/elab24.vhd \
	test/regress/elab25.vhd \
	test/regress/elab2.vhd \
	test/regress/elab3.vhd \
	test/regress/elab4.vhd \
	test/regress/elab5.vhd \
	test/regress/elab6.vhd \
	test/regress/elab7.vhd \
	test/regress/elab8.vhd \
	test/regress/elab9.vhd \
	test/regress/fact.vhd \
	test/regress/file1.vhd \
	test/regress/file2.vhd \
	test/regress/for1.vhd \
	test/regress/for2.vhd \
	test/regress/for3.vhd \
	test/regress/func10.vhd \
	test/regress/func11.vhd \
	test/regress/func12.vhd \
	test/regress/func13.vhd \
	test/regress/func14.vhd \
	test/regress/func15.vhd \
	test/regress/func16.vhd \
	test/regress/func17.vhd \
	test/regress/func1.vhd \
	test/regress/func2.vhd \
	test/regress/func3.vhd \
	test/regress/func4.vhd \
	test/regress/func5.vhd \
	test/regress/func6.vhd \
	test/regress/func7.vhd \
	test/regress/func8.vhd \
	test/regress/func9.vhd \
	test/regress/generic1.vhd \
	test/regress/gold/access1.txt \
	test/regress/gold/access6.txt \
	test/regress/gold/alias1.txt \
	test/regress/gold/alias2.txt \
	test/regress/gold/alias5.txt \
	test/regress/gold/arith2.txt \
	test/regress/gold/assert1.txt \
	test/regress/gold/assert2.txt \
	test/regress/gold/assert3.txt \
	test/regress/gold/attr12.txt \
	test/regress/gold/attr3.txt \
	test/regress/gold/bounds10.txt \
	test/regress/gold/bounds11.txt \
	test/regress/gold/bounds12.txt \
	test/regress/gold/bounds13.txt \
	test/regress/gold/bounds14.txt \
	test/regress/gold/bounds15.txt \
	test/regress/gold/bounds16.txt \
	test/regress/gold/bounds17.txt \
	test/regress/gold/bounds1.txt \
	test/regress/gold/bounds2.txt \
	test/regress/gold/bounds3.txt \
	test/regress/gold/bounds4.txt \
	test/regress/gold/bounds5.txt \
	test/regress/gold/bounds6.txt \
	test/regress/gold/bounds7.txt \
	test/regress/gold/bounds8.txt \
	test/regress/gold/bounds9.txt \
	test/regress/gold/case5.txt \
	test/regress/gold/cond1.txt \
	test/regress/gold/cond2.txt \
	test/regress/gold/const3.txt \
	test/regress/gold/counter.txt \
	test/regress/gold/cover1.txt \
	test/regress/gold/elab10.txt \
	test/regress/gold/elab13.txt \
	test/regress/gold/elab3.txt \
	test/regress/gold/elab9.txt \
	test/regress/gold/fact.txt \
	test/regress/gold/for1.txt \
	test/regress/gold/for2.txt \
	test/regress/gold/for3.txt \
	test/regress/gold/image.txt \
	test/regress/gold/issue103.txt \
	test/regress/gold/issue110.txt \
	test/regress/gold/issue185.txt \
	test/regress/gold/issue202.txt \
	test/regress/gold/issue225.txt \
	test/regress/gold/issue227.txt \
	test/regress/gold/issue234.txt \
	test/regress/gold/issue308.txt \
	test/regress/gold/issue351.txt \
	test/regress/gold/issue377.txt \
	test/regress/gold/issue45.txt \
	test/regress/gold/issue96.txt \
	test/regress/gold/proc7.txt \
	test/regress/gold/proc8.txt \
	test/regress/gold/range1.txt \
	test/regress/gold/real1.txt \
	test/regress/gold/real3.txt \
	test/regress/gold/signal11.txt \
	test/regress/gold/signal6.txt \
	test/regress/gold/stop1.txt \
	test/regress/gold/stop2.txt \
	test/regress/gold/textio1.txt \
	test/regress/gold/textio2008.txt \
	test/regress/gold/vhpi1.txt \
	test/regress/gold/wait12.txt \
	test/regress/gold/wait2.txt \
	test/regress/gold/wait6.txt \
	test/regress/gold/while1.txt \
	test/regress/ieee1.vhd \
	test/regress/ieee2.vhd \
	test/regress/ieee3.vhd \
	test/regress/ieee4.vhd \
	test/regress/ieee5.vhd \
	test/regress/image.vhd \
	test/regress/implicit1.vhd \
	test/regress/implicit2.vhd \
	test/regress/implicit3.vhd \
	test/regress/issue103.vhd \
	test/regress/issue104.vhd \
	test/regress/issue106.vhd \
	test/regress/issue109.vhd \
	test/regress/issue10.vhd \
	test/regress/issue110.vhd \
	test/regress/issue111.vhd \
	test/regress/issue112.vhd \
	test/regress/issue115.vhd \
	test/regress/issue116.vhd \
	test/regress/issue121.vhd \
	test/regress/issue122.vhd \
	test/regress/issue123.vhd \
	test/regress/issue126.vhd \
	test/regress/issue13.vhd \
	test/regress/issue141.vhd \
	test/regress/issue143.vhd \
	test/regress/issue146.vhd \
	test/regress/issue148.vhd \
	test/regress/issue152.vhd \
	test/regress/issue153.vhd \
	test/regress/issue163.vhd \
	test/regress/issue169.vhd \
	test/regress/issue16.vhd \
	test/regress/issue183.vhd \
	test/regress/issue185.vhd \
	test/regress/issue186.vhd \
	test/regress/issue187.vhd \
	test/regress/issue18.vhd \
	test/regress/issue194.vhd \
	test/regress/issue196.vhd \
	test/regress/issue197.vhd \
	test/regress/issue200.vhd \
	test/regress/issue201.vhd \
	test/regress/issue202.vhd \
	test/regress/issue204.vhd \
	test/regress/issue206.vhd \
	test/regress/issue217.vhd \
	test/regress/issue225.vhd \
	test/regress/issue227.vhd \
	test/regress/issue229.vhd \
	test/regress/issue234.vhd \
	test/regress/issue262.vhd \
	test/regress/issue284.vhd \
	test/regress/issue293.vhd \
	test/regress/issue29.vhd \
	test/regress/issue308.vhd \
	test/regress/issue309.vhd \
	test/regress/issue315.vhd \
	test/regress/issue323.vhd \
	test/regress/issue327.vhd \
	test/regress/issue335.vhd \
	test/regress/issue338b.vhd \
	test/regress/issue338.vhd \
	test/regress/issue340.vhd \
	test/regress/issue348.vhd \
	test/regress/issue349.vhd \
	test/regress/issue351.vhd \
	test/regress/issue352.vhd \
	test/regress/issue354.vhd \
	test/regress/issue367.vhd \
	test/regress/issue369.vhd \
	test/regress/issue370.vhd \
	test/regress/issue371.vhd \
	test/regress/issue376.vhd \
	test/regress/issue377.vhd \
	test/regress/issue38.vhd \
	test/regress/issue397.vhd \
	test/regress/issue407.vhd \
	test/regress/issue45.vhd \
	test/regress/issue53.vhd \
	test/regress/issue56.vhd \
	test/regress/issue57.vhd \
	test/regress/issue59.vhd \
	test/regress/issue60.vhd \
	test/regress/issue63.vhd \
	test/regress/issue69.vhd \
	test/regress/issue70.vhd \
	test/regress/issue72.vhd \
	test/regress/issue79.vhd \
	test/regress/issue82.vhd \
	test/regress/issue83.vhd \
	test/regress/issue84.vhd \
	test/regress/issue86.vhd \
	test/regress/issue8.vhd \
	test/regress/issue90.vhd \
	test/regress/issue91.vhd \
	test/regress/issue94.vhd \
	test/regress/issue95.vhd \
	test/regress/issue96.vhd \
	test/regress/issue9.vhd \
	test/regress/jcore1.vhd \
	test/regress/jcore2.vhd \
	test/regress/jcore3.vhd \
	test/regress/jcore4.vhd \
	test/regress/jcore5.vhd \
	test/regress/jcore6.vhd \
	test/regress/lfsr.vhd \
	test/regress/link1.vhd \
	test/regress/link2.vhd \
	test/regress/logical1.vhd \
	test/regress/logical2.vhd \
	test/regress/loop1.vhd \
	test/regress/null1.vhd \
	test/regress/null2.vhd \
	test/regress/operator1.vhd \
	test/regress/operator2.vhd \
	test/regress/operator3.vhd \
	test/regress/operator4.vhd \
	test/regress/operator5.vhd \
	test/regress/proc10.vhd \
	test/regress/proc11.vhd \
	test/regress/proc1.vhd \
	test/regress/proc2.vhd \
	test/regress/proc3.vhd \
	test/regress/proc4.vhd \
	test/regress/proc5.vhd \
	test/regress/proc6.vhd \
	test/regress/proc7.vhd \
	test/regress/proc8.vhd \
	test/regress/proc9.vhd \
	test/regress/protected1.vhd \
	test/regress/protected2.vhd \
	test/regress/protected3.vhd \
	test/regress/protected4.vhd \
	test/regress/ram1.vhd \
	test/regress/range1.vhd \
	test/regress/real1.vhd \
	test/regress/real2.vhd \
	test/regress/real3.vhd \
	test/regress/record10.vhd \
	test/regress/record11.vhd \
	test/regress/record12.vhd \
	test/regress/record13.vhd \
	test/regress/record1.vhd \
	test/regress/record2.vhd \
	test/regress/record3.vhd \
	test/regress/record4.vhd \
	test/regress/record5.vhd \
	test/regress/record6.vhd \
	test/regress/record7.vhd \
	test/regress/record8.vhd \
	test/regress/record9.vhd \
	test/regress/shared1.vhd \
	test/regress/shared2.vhd \
	test/regress/shift1.vhd \
	test/regress/shift2.vhd \
	test/regress/signal10.vhd \
	test/regress/signal11.vhd \
	test/regress/signal12.vhd \
	test/regress/signal13.vhd \
	test/regress/signal14.vhd \
	test/regress/signal1.vhd \
	test/regress/signal2.vhd \
	test/regress/signal3.vhd \
	test/regress/signal4.vhd \
	test/regress/signal5.vhd \
	test/regress/signal6.vhd \
	test/regress/signal7.vhd \
	test/regress/signal8.vhd \
	test/regress/signal9.vhd \
	test/regress/slice1.vhd \
	test/regress/slice2.vhd \
	test/regress/slice3.vhd \
	test/regress/slice4.vhd \
	test/regress/stack1.vhd \
	test/regress/stop1.vhd \
	test/regress/stop2.vhd \
	test/regress/synopsys1.vhd \
	test/regress/testlist.txt \
	test/regress/textio1.vhd \
	test/regress/textio2008.vhd \
	test/regress/textio2.vhd \
	test/regress/textio3.vhd \
	test/regress/textio4.vhd \
	test/regress/toplevel1.vhd \
	test/regress/toplevel2.vhd \
	test/regress/vecorder.vhd \
	test/regress/vhpi1.vhd \
	test/regress/vhpi2.vhd \
	test/regress/vhpi3.vhd \
	test/regress/wait10.vhd \
	test/regress/wait11.vhd \
	test/regress/wait12.vhd \
	test/regress/wait13.vhd \
	test/regress/wait14.vhd \
	test/regress/wait1.vhd \
	test/regress/wait2.vhd \
	test/regress/wait3.vhd \
	test/regress/wait4.vhd \
	test/regress/wait5.vhd \
	test/regress/wait6.vhd \
	test/regress/wait7.vhd \
	test/regress/wait8.vhd \
	test/regress/wait9.vhd \
	test/regress/while1.vhd \
	test/sem/access.vhd \
	test/sem/afunc.vhd \
	test/sem/alias.vhd \
	test/sem/ambiguous.vhd \
	test/sem/array.vhd \
	test/sem/assert.vhd \
	test/sem/attr.vhd \
	test/sem/block.vhd \
	test/sem/concat.vhd \
	test/sem/conc.vhd \
	test/sem/config.vhd \
	test/sem/const2.vhd \
	test/sem/const.vhd \
	test/sem/context.vhd \
	test/sem/conv.vhd \
	test/sem/duplicate.vhd \
	test/sem/dwlau.vhd \
	test/sem/entity.vhd \
	test/sem/file_and_access.vhd \
	test/sem/file.vhd \
	test/sem/foreign1.vhd \
	test/sem/func.vhd \
	test/sem/generate.vhd \
	test/sem/generics.vhd \
	test/sem/implicit.vhd \
	test/sem/integer.vhd \
	test/sem/interfaces.vhd \
	test/sem/issue102.vhd \
	test/sem/issue105.vhd \
	test/sem/issue128.vhd \
	test/sem/issue130.vhd \
	test/sem/issue131.vhd \
	test/sem/issue132.vhd \
	test/sem/issue133.vhd \
	test/sem/issue140.vhd \
	test/sem/issue144.vhd \
	test/sem/issue151.vhd \
	test/sem/issue162.vhd \
	test/sem/issue165.vhd \
	test/sem/issue173.vhd \
	test/sem/issue174.vhd \
	test/sem/issue176.vhd \
	test/sem/issue177.vhd \
	test/sem/issue178.vhd \
	test/sem/issue188.vhd \
	test/sem/issue197.vhd \
	test/sem/issue201.vhd \
	test/sem/issue219.vhd \
	test/sem/issue220.vhd \
	test/sem/issue221.vhd \
	test/sem/issue224.vhd \
	test/sem/issue225.vhd \
	test/sem/issue226.vhd \
	test/sem/issue232.vhd \
	test/sem/issue236.vhd \
	test/sem/issue239.vhd \
	test/sem/issue246.vhd \
	test/sem/issue264.vhd \
	test/sem/issue276.vhd \
	test/sem/issue293.vhd \
	test/sem/issue311.vhd \
	test/sem/issue316.vhd \
	test/sem/issue326.vhd \
	test/sem/issue340.vhd \
	test/sem/issue341.vhd \
	test/sem/issue350.vhd \
	test/sem/issue356.vhd \
	test/sem/issue359a.vhd \
	test/sem/issue359.vhd \
	test/sem/issue363.vhd \
	test/sem/issue368.vhd \
	test/sem/issue369.vhd \
	test/sem/issue377.vhd \
	test/sem/issue386.vhd \
	test/sem/issue407.vhd \
	test/sem/issue52.vhd \
	test/sem/issue53.vhd \
	test/sem/issue58.vhd \
	test/sem/issue88.vhd \
	test/sem/issue89.vhd \
	test/sem/jcore1.vhd \
	test/sem/physical.vhd \
	test/sem/ports.vhd \
	test/sem/procedure.vhd \
	test/sem/protected2.vhd \
	test/sem/protected.vhd \
	test/sem/real.vhd \
	test/sem/record.vhd \
	test/sem/scope.vhd \
	test/sem/seq.vhd \
	test/sem/signal.vhd \
	test/sem/spec.vhd \
	test/sem/static.vhd \
	test/sem/std.vhd \
	test/sem/subtype.vhd \
	test/sem/supersede.vhd \
	test/sem/textio.vhd \
	test/sem/universal.vhd \
	test/sem/use.vhd \
	test/sem/varinit.vhd \
	test/sem/vests1.vhd \
	test/sem/vital1.vhd \
	test/sem/wait.vhd \
	test/simp/allsens.vhd \
	test/simp/args.vhd \
	test/simp/cfold.vhd \
	test/simp/constarr.vhd \
	test/simp/context.vhd \
	test/simp/ffold2.vhd \
	test/simp/ffold.vhd \
	test/simp/func9.vhd \
	test/simp/issue155.vhd \
	test/simp/issue194.vhd \
	test/simp/issue212.vhd \
	test/simp/issue309.vhd \
	test/simp/issue320.vhd \
	test/simp/issue321.vhd \
	test/simp/issue322.vhd \
	test/simp/issue331.vhd \
	test/simp/issue332.vhd \
	test/simp/issue344.vhd \
	test/simp/issue345.vhd \
	test/simp/issue362.vhd \
	test/simp/issue49.vhd \
	test/simp/proc.vhd \
	test/simp/shift2.vhd \
	test/simp/table.vhd \
	test/wave/wave_test.vhd
