# Generated by nvc 1.19-devel

lib/std.08/STD.ENV-body: $(top_srcdir)/lib/std.08/env-body.vhd lib/std.08/STD.STANDARD lib/std.08/STD.ENV

lib/std.08/STD.ENV: $(top_srcdir)/lib/std.08/env.vhd lib/std.08/STD.STANDARD

lib/std.08/STD.STANDARD: $(top_srcdir)/lib/std.08/standard.vhd

lib/std.08/STD.TEXTIO: $(top_srcdir)/lib/std.08/textio.vhd lib/std.08/STD.STANDARD

lib/std.08/STD.STANDARD-body: $(top_srcdir)/lib/std/standard-body.vhd lib/std.08/STD.STANDARD

lib/std.08/STD.TEXTIO-body: $(top_srcdir)/lib/std/textio-body.vhd lib/std.08/STD.TEXTIO lib/std.08/STD.STANDARD lib/nvc.08/NVC.POLYFILL

