# Generated by nvc 0.1

ieee/IEEE.STD_LOGIC_TEXTIO-body ieee/_IEEE.STD_LOGIC_TEXTIO-body.so ieee/_IEEE.STD_LOGIC_TEXTIO-body.bc ieee/IEEE.STD_LOGIC_TEXTIO: ieee/IEEE.STD_LOGIC_1164 ../../../lib/synopsys/std_logic_textio.vhd

ieee/IEEE.STD_LOGIC_SIGNED-body ieee/_IEEE.STD_LOGIC_SIGNED-body.so ieee/_IEEE.STD_LOGIC_SIGNED-body.bc ieee/IEEE.STD_LOGIC_SIGNED: ieee/IEEE.STD_LOGIC_1164 ieee/IEEE.STD_LOGIC_ARITH ../../../lib/synopsys/std_logic_signed.vhd

ieee/IEEE.VITAL_MEMORY: ieee/IEEE.STD_LOGIC_1164 ieee/IEEE.VITAL_TIMING ieee/IEEE.VITAL_PRIMITIVES ../../../lib/ieee/memory_p.vhdl

ieee/IEEE.VITAL_PRIMITIVES ieee/_IEEE.VITAL_PRIMITIVES.so ieee/_IEEE.VITAL_PRIMITIVES.bc: ieee/IEEE.STD_LOGIC_1164 ieee/IEEE.VITAL_TIMING ../../../lib/ieee/prmtvs_p.vhdl

ieee/IEEE.VITAL_TIMING ieee/_IEEE.VITAL_TIMING.so ieee/_IEEE.VITAL_TIMING.bc: ieee/IEEE.STD_LOGIC_1164 ../../../lib/ieee/timing_p.vhdl

ieee/IEEE.MATH_REAL ieee/_IEEE.MATH_REAL.so ieee/_IEEE.MATH_REAL.bc: ../../../lib/ieee/math_real.vhdl

ieee/IEEE.NUMERIC_STD-body ieee/_IEEE.NUMERIC_STD-body.so ieee/_IEEE.NUMERIC_STD-body.bc: ieee/IEEE.NUMERIC_STD ../../../lib/ieee/numeric_std-body.vhdl

ieee/IEEE.NUMERIC_STD ieee/_IEEE.NUMERIC_STD.so ieee/_IEEE.NUMERIC_STD.bc: ieee/IEEE.STD_LOGIC_1164 ../../../lib/ieee/numeric_std.vhdl

ieee/IEEE.NUMERIC_BIT ieee/_IEEE.NUMERIC_BIT.so ieee/_IEEE.NUMERIC_BIT.bc: ../../../lib/ieee/numeric_bit.vhdl

ieee/IEEE.STD_LOGIC_1164-body ieee/_IEEE.STD_LOGIC_1164-body.so ieee/_IEEE.STD_LOGIC_1164-body.bc: ieee/IEEE.STD_LOGIC_1164 ../../../lib/ieee/std_logic_1164-body.vhdl

ieee/IEEE.NUMERIC_BIT-body ieee/_IEEE.NUMERIC_BIT-body.so ieee/_IEEE.NUMERIC_BIT-body.bc: ieee/IEEE.NUMERIC_BIT ../../../lib/ieee/numeric_bit-body.vhdl

ieee/IEEE.MATH_REAL-body ieee/_IEEE.MATH_REAL-body.so ieee/_IEEE.MATH_REAL-body.bc: ieee/IEEE.MATH_REAL ../../../lib/ieee/math_real-body.vhdl

ieee/IEEE.VITAL_TIMING-body ieee/_IEEE.VITAL_TIMING-body.so ieee/_IEEE.VITAL_TIMING-body.bc: ieee/IEEE.VITAL_TIMING ../../../lib/ieee/timing_b.vhdl

ieee/IEEE.VITAL_PRIMITIVES-body ieee/_IEEE.VITAL_PRIMITIVES-body.so ieee/_IEEE.VITAL_PRIMITIVES-body.bc: ieee/IEEE.VITAL_PRIMITIVES ../../../lib/ieee/prmtvs_b.vhdl

ieee/IEEE.STD_LOGIC_1164: ../../../lib/ieee/std_logic_1164.vhdl

ieee/IEEE.STD_LOGIC_ARITH-body ieee/_IEEE.STD_LOGIC_ARITH-body.so ieee/_IEEE.STD_LOGIC_ARITH-body.bc ieee/IEEE.STD_LOGIC_ARITH: ieee/IEEE.STD_LOGIC_1164 ../../../lib/synopsys/std_logic_arith.vhd

ieee/IEEE.STD_LOGIC_UNSIGNED ieee/IEEE.STD_LOGIC_UNSIGNED-body ieee/_IEEE.STD_LOGIC_UNSIGNED-body.so ieee/_IEEE.STD_LOGIC_UNSIGNED-body.bc: ieee/IEEE.STD_LOGIC_1164 ieee/IEEE.STD_LOGIC_ARITH ../../../lib/synopsys/std_logic_unsigned.vhd

