# Generated by nvc 0.1

lib/ieee/IEEE.VITAL_MEMORY: lib/std/STD.TEXTIO lib/ieee/IEEE.VITAL_PRIMITIVES lib/ieee/IEEE.VITAL_TIMING lib/ieee/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee/memory_p.vhdl

lib/ieee/_IEEE.VITAL_MEMORY.a: lib/std/STD.TEXTIO lib/ieee/IEEE.VITAL_PRIMITIVES lib/ieee/IEEE.VITAL_TIMING lib/ieee/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee/memory_p.vhdl

lib/ieee/_IEEE.VITAL_MEMORY.so: lib/std/STD.TEXTIO lib/ieee/IEEE.VITAL_PRIMITIVES lib/ieee/IEEE.VITAL_TIMING lib/ieee/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee/memory_p.vhdl

lib/ieee/_IEEE.VITAL_MEMORY.bc: lib/std/STD.TEXTIO lib/ieee/IEEE.VITAL_PRIMITIVES lib/ieee/IEEE.VITAL_TIMING lib/ieee/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee/memory_p.vhdl

lib/ieee/IEEE.MATH_COMPLEX: lib/ieee/IEEE.MATH_REAL $(top_srcdir)/lib/ieee/math_complex.vhdl

lib/ieee/_IEEE.MATH_COMPLEX.a: lib/ieee/IEEE.MATH_REAL $(top_srcdir)/lib/ieee/math_complex.vhdl

lib/ieee/_IEEE.MATH_COMPLEX.so: lib/ieee/IEEE.MATH_REAL $(top_srcdir)/lib/ieee/math_complex.vhdl

lib/ieee/_IEEE.MATH_COMPLEX.bc: lib/ieee/IEEE.MATH_REAL $(top_srcdir)/lib/ieee/math_complex.vhdl

lib/ieee/IEEE.NUMERIC_STD-body: lib/ieee/IEEE.NUMERIC_STD $(top_srcdir)/lib/ieee/numeric_std-body.vhdl

lib/ieee/_IEEE.NUMERIC_STD-body.a: lib/ieee/IEEE.NUMERIC_STD $(top_srcdir)/lib/ieee/numeric_std-body.vhdl

lib/ieee/_IEEE.NUMERIC_STD-body.so: lib/ieee/IEEE.NUMERIC_STD $(top_srcdir)/lib/ieee/numeric_std-body.vhdl

lib/ieee/_IEEE.NUMERIC_STD-body.bc: lib/ieee/IEEE.NUMERIC_STD $(top_srcdir)/lib/ieee/numeric_std-body.vhdl

lib/ieee/IEEE.NUMERIC_STD: lib/ieee/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee/numeric_std.vhdl

lib/ieee/_IEEE.NUMERIC_STD.a: lib/ieee/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee/numeric_std.vhdl

lib/ieee/_IEEE.NUMERIC_STD.so: lib/ieee/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee/numeric_std.vhdl

lib/ieee/_IEEE.NUMERIC_STD.bc: lib/ieee/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee/numeric_std.vhdl

lib/ieee/IEEE.STD_LOGIC_1164-body: lib/ieee/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee/std_logic_1164-body.vhdl

lib/ieee/_IEEE.STD_LOGIC_1164-body.a: lib/ieee/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee/std_logic_1164-body.vhdl

lib/ieee/_IEEE.STD_LOGIC_1164-body.so: lib/ieee/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee/std_logic_1164-body.vhdl

lib/ieee/_IEEE.STD_LOGIC_1164-body.bc: lib/ieee/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee/std_logic_1164-body.vhdl

lib/ieee/IEEE.VITAL_PRIMITIVES: lib/ieee/IEEE.VITAL_TIMING lib/ieee/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee/prmtvs_p.vhdl

lib/ieee/_IEEE.VITAL_PRIMITIVES.a: lib/ieee/IEEE.VITAL_TIMING lib/ieee/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee/prmtvs_p.vhdl

lib/ieee/_IEEE.VITAL_PRIMITIVES.so: lib/ieee/IEEE.VITAL_TIMING lib/ieee/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee/prmtvs_p.vhdl

lib/ieee/_IEEE.VITAL_PRIMITIVES.bc: lib/ieee/IEEE.VITAL_TIMING lib/ieee/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee/prmtvs_p.vhdl

lib/ieee/IEEE.STD_LOGIC_1164: $(top_srcdir)/lib/ieee/std_logic_1164.vhdl

lib/ieee/IEEE.VITAL_TIMING: lib/ieee/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee/timing_p.vhdl

lib/ieee/_IEEE.VITAL_TIMING.a: lib/ieee/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee/timing_p.vhdl

lib/ieee/_IEEE.VITAL_TIMING.so: lib/ieee/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee/timing_p.vhdl

lib/ieee/_IEEE.VITAL_TIMING.bc: lib/ieee/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee/timing_p.vhdl

lib/ieee/IEEE.VITAL_PRIMITIVES-body: lib/std/STD.TEXTIO lib/ieee/IEEE.VITAL_PRIMITIVES $(top_srcdir)/lib/ieee/prmtvs_b.vhdl

lib/ieee/_IEEE.VITAL_PRIMITIVES-body.a: lib/std/STD.TEXTIO lib/ieee/IEEE.VITAL_PRIMITIVES $(top_srcdir)/lib/ieee/prmtvs_b.vhdl

lib/ieee/_IEEE.VITAL_PRIMITIVES-body.so: lib/std/STD.TEXTIO lib/ieee/IEEE.VITAL_PRIMITIVES $(top_srcdir)/lib/ieee/prmtvs_b.vhdl

lib/ieee/_IEEE.VITAL_PRIMITIVES-body.bc: lib/std/STD.TEXTIO lib/ieee/IEEE.VITAL_PRIMITIVES $(top_srcdir)/lib/ieee/prmtvs_b.vhdl

lib/ieee/IEEE.NUMERIC_BIT: $(top_srcdir)/lib/ieee/numeric_bit.vhdl

lib/ieee/_IEEE.NUMERIC_BIT.a: $(top_srcdir)/lib/ieee/numeric_bit.vhdl

lib/ieee/_IEEE.NUMERIC_BIT.so: $(top_srcdir)/lib/ieee/numeric_bit.vhdl

lib/ieee/_IEEE.NUMERIC_BIT.bc: $(top_srcdir)/lib/ieee/numeric_bit.vhdl

lib/ieee/IEEE.NUMERIC_BIT-body: lib/ieee/IEEE.NUMERIC_BIT $(top_srcdir)/lib/ieee/numeric_bit-body.vhdl

lib/ieee/_IEEE.NUMERIC_BIT-body.a: lib/ieee/IEEE.NUMERIC_BIT $(top_srcdir)/lib/ieee/numeric_bit-body.vhdl

lib/ieee/_IEEE.NUMERIC_BIT-body.so: lib/ieee/IEEE.NUMERIC_BIT $(top_srcdir)/lib/ieee/numeric_bit-body.vhdl

lib/ieee/_IEEE.NUMERIC_BIT-body.bc: lib/ieee/IEEE.NUMERIC_BIT $(top_srcdir)/lib/ieee/numeric_bit-body.vhdl

lib/ieee/IEEE.MATH_REAL-body: lib/ieee/IEEE.MATH_REAL $(top_srcdir)/lib/ieee/math_real-body.vhdl

lib/ieee/_IEEE.MATH_REAL-body.a: lib/ieee/IEEE.MATH_REAL $(top_srcdir)/lib/ieee/math_real-body.vhdl

lib/ieee/_IEEE.MATH_REAL-body.so: lib/ieee/IEEE.MATH_REAL $(top_srcdir)/lib/ieee/math_real-body.vhdl

lib/ieee/_IEEE.MATH_REAL-body.bc: lib/ieee/IEEE.MATH_REAL $(top_srcdir)/lib/ieee/math_real-body.vhdl

lib/ieee/IEEE.MATH_REAL: $(top_srcdir)/lib/ieee/math_real.vhdl

lib/ieee/_IEEE.MATH_REAL.a: $(top_srcdir)/lib/ieee/math_real.vhdl

lib/ieee/_IEEE.MATH_REAL.so: $(top_srcdir)/lib/ieee/math_real.vhdl

lib/ieee/_IEEE.MATH_REAL.bc: $(top_srcdir)/lib/ieee/math_real.vhdl

lib/ieee/IEEE.MATH_COMPLEX-body: lib/ieee/IEEE.MATH_REAL lib/ieee/IEEE.MATH_COMPLEX $(top_srcdir)/lib/ieee/math_complex-body.vhdl

lib/ieee/_IEEE.MATH_COMPLEX-body.a: lib/ieee/IEEE.MATH_REAL lib/ieee/IEEE.MATH_COMPLEX $(top_srcdir)/lib/ieee/math_complex-body.vhdl

lib/ieee/_IEEE.MATH_COMPLEX-body.so: lib/ieee/IEEE.MATH_REAL lib/ieee/IEEE.MATH_COMPLEX $(top_srcdir)/lib/ieee/math_complex-body.vhdl

lib/ieee/_IEEE.MATH_COMPLEX-body.bc: lib/ieee/IEEE.MATH_REAL lib/ieee/IEEE.MATH_COMPLEX $(top_srcdir)/lib/ieee/math_complex-body.vhdl

lib/ieee/IEEE.VITAL_TIMING-body: lib/std/STD.TEXTIO lib/ieee/IEEE.VITAL_TIMING $(top_srcdir)/lib/ieee/timing_b.vhdl

lib/ieee/_IEEE.VITAL_TIMING-body.a: lib/std/STD.TEXTIO lib/ieee/IEEE.VITAL_TIMING $(top_srcdir)/lib/ieee/timing_b.vhdl

lib/ieee/_IEEE.VITAL_TIMING-body.so: lib/std/STD.TEXTIO lib/ieee/IEEE.VITAL_TIMING $(top_srcdir)/lib/ieee/timing_b.vhdl

lib/ieee/_IEEE.VITAL_TIMING-body.bc: lib/std/STD.TEXTIO lib/ieee/IEEE.VITAL_TIMING $(top_srcdir)/lib/ieee/timing_b.vhdl

