# Generated by nvc 1.9-devel

lib/nvc.19/NVC.POLYFILL: $(top_srcdir)/lib/nvc.08/polyfill.vhd

lib/nvc.19/NVC.SIM_PKG: lib/std.19/STD.STANDARD $(top_srcdir)/lib/nvc/sim_pkg.vhd

lib/nvc.19/NVC.TEXTBUF-body: lib/std.19/STD.STANDARD lib/nvc.19/NVC.TEXTBUF $(top_srcdir)/lib/nvc/textbuf-body.vhd

lib/nvc.19/NVC.TEXTBUF: lib/std.19/STD.STANDARD $(top_srcdir)/lib/nvc/textbuf.vhd

