# Generated by nvc 1.7-devel

lib/nvc.08/NVC.IEEE_SUPPORT-body: lib/std.08/STD.STANDARD lib/ieee.08/IEEE.STD_LOGIC_1164 lib/nvc.08/NVC.IEEE_SUPPORT $(top_srcdir)/lib/nvc.08/ieee_support-body.vhd

lib/nvc.08/NVC.IEEE_SUPPORT: lib/ieee.08/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/nvc.08/ieee_support.vhd

lib/nvc.08/NVC.POLYFILL: $(top_srcdir)/lib/nvc.08/polyfill.vhd

lib/nvc.08/NVC.SIM_PKG: lib/std.08/STD.STANDARD $(top_srcdir)/lib/nvc/sim_pkg.vhd

