# Generated by nvc 1.16-devel

lib/nvc.08/NVC.IEEE_SUPPORT-body: lib/std.08/STD.STANDARD lib/nvc.08/NVC.IEEE_SUPPORT lib/ieee.08/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/nvc.08/ieee_support-body.vhd

lib/nvc.08/NVC.IEEE_SUPPORT: lib/std.08/STD.STANDARD lib/ieee.08/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/nvc.08/ieee_support.vhd

lib/nvc.08/NVC.POLYFILL: lib/std.08/STD.STANDARD $(top_srcdir)/lib/nvc.08/polyfill.vhd

lib/nvc.08/NVC.COVER_PKG-body: lib/std.08/STD.STANDARD lib/nvc.08/NVC.COVER_PKG $(top_srcdir)/lib/nvc/cover_pkg-body.vhd

lib/nvc.08/NVC.COVER_PKG: lib/std.08/STD.STANDARD $(top_srcdir)/lib/nvc/cover_pkg.vhd

lib/nvc.08/NVC.PSL_SUPPORT-body: lib/std.08/STD.STANDARD lib/nvc.08/NVC.PSL_SUPPORT lib/ieee.08/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/nvc/psl_support-body.vhd

lib/nvc.08/NVC.PSL_SUPPORT: lib/std.08/STD.STANDARD lib/ieee.08/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/nvc/psl_support.vhd

lib/nvc.08/NVC.RANDOM-body: lib/std.08/STD.STANDARD lib/nvc.08/NVC.RANDOM $(top_srcdir)/lib/nvc/random-body.vhd

lib/nvc.08/NVC.RANDOM: lib/std.08/STD.STANDARD $(top_srcdir)/lib/nvc/random.vhd

lib/nvc.08/NVC.SIM_PKG-body: lib/std.08/STD.STANDARD lib/nvc.08/NVC.SIM_PKG $(top_srcdir)/lib/nvc/sim_pkg-body.vhd

lib/nvc.08/NVC.SIM_PKG: lib/std.08/STD.STANDARD $(top_srcdir)/lib/nvc/sim_pkg.vhd

lib/nvc.08/NVC.TEXT_UTIL-body: lib/std.08/STD.STANDARD lib/nvc.08/NVC.TEXT_UTIL lib/nvc.08/NVC.POLYFILL $(top_srcdir)/lib/nvc/text_util-body.vhd

lib/nvc.08/NVC.TEXT_UTIL: lib/std.08/STD.STANDARD $(top_srcdir)/lib/nvc/text_util.vhd

lib/nvc.08/NVC.VERILOG-body: lib/std.08/STD.STANDARD lib/nvc.08/NVC.VERILOG lib/nvc.08/NVC.POLYFILL lib/ieee.08/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/nvc/verilog-body.vhd

lib/nvc.08/NVC.VERILOG: lib/std.08/STD.STANDARD lib/ieee.08/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/nvc/verilog.vhd

