# Generated by nvc 0.1

nvc/NVC.ENV-body nvc/_NVC.ENV-body.a nvc/_NVC.ENV-body.so nvc/_NVC.ENV-body.bc nvc/NVC.ENV: $(top_srcdir)/lib/nvc/env.vhd

# Generated by nvc 0.1

../std/std/STD.ENV-body ../std/std/_STD.ENV-body.a ../std/std/_STD.ENV-body.so ../std/std/_STD.ENV-body.bc ../std/std/STD.ENV: $(top_srcdir)/lib/nvc/env.vhd

../std/std/STD.STANDARD: $(top_srcdir)/lib/std/standard.vhd

../std/std/STD.TEXTIO ../std/std/_STD.TEXTIO.a ../std/std/_STD.TEXTIO.so ../std/std/_STD.TEXTIO.bc ../std/std/STD.TEXTIO-body ../std/std/_STD.TEXTIO-body.a ../std/std/_STD.TEXTIO-body.so ../std/std/_STD.TEXTIO-body.bc: $(top_srcdir)/lib/std/textio.vhd

