# Generated by nvc 1.19-devel

lib/nvc/NVC.COVER_PKG-body: $(top_srcdir)/lib/nvc/cover_pkg-body.vhd lib/std/STD.STANDARD lib/nvc/NVC.COVER_PKG

lib/nvc/NVC.COVER_PKG: $(top_srcdir)/lib/nvc/cover_pkg.vhd lib/std/STD.STANDARD

lib/nvc/NVC.POLYFILL-body: $(top_srcdir)/lib/nvc/polyfill-body.vhd lib/std/STD.STANDARD lib/nvc/NVC.POLYFILL

lib/nvc/NVC.POLYFILL: $(top_srcdir)/lib/nvc/polyfill.vhd lib/std/STD.STANDARD

lib/nvc/NVC.PSL_SUPPORT-body: $(top_srcdir)/lib/nvc/psl_support-body.vhd lib/std/STD.STANDARD lib/nvc/NVC.PSL_SUPPORT lib/ieee/IEEE.STD_LOGIC_1164

lib/nvc/NVC.PSL_SUPPORT: $(top_srcdir)/lib/nvc/psl_support.vhd lib/std/STD.STANDARD lib/ieee/IEEE.STD_LOGIC_1164

lib/nvc/NVC.RANDOM-body: $(top_srcdir)/lib/nvc/random-body.vhd lib/std/STD.STANDARD lib/nvc/NVC.RANDOM

lib/nvc/NVC.RANDOM: $(top_srcdir)/lib/nvc/random.vhd lib/std/STD.STANDARD

lib/nvc/NVC.SIM_PKG-body: $(top_srcdir)/lib/nvc/sim_pkg-body.vhd lib/std/STD.STANDARD lib/nvc/NVC.SIM_PKG

lib/nvc/NVC.SIM_PKG: $(top_srcdir)/lib/nvc/sim_pkg.vhd lib/std/STD.STANDARD

lib/nvc/NVC.TEXT_UTIL-body: $(top_srcdir)/lib/nvc/text_util-body.vhd lib/std/STD.STANDARD lib/nvc/NVC.TEXT_UTIL lib/nvc/NVC.POLYFILL

lib/nvc/NVC.TEXT_UTIL: $(top_srcdir)/lib/nvc/text_util.vhd lib/std/STD.STANDARD

lib/nvc/NVC.VERILOG-body: $(top_srcdir)/lib/nvc/verilog-body.vhd lib/std/STD.STANDARD lib/nvc/NVC.VERILOG lib/nvc/NVC.POLYFILL lib/ieee/IEEE.STD_LOGIC_1164

lib/nvc/NVC.VERILOG: $(top_srcdir)/lib/nvc/verilog.vhd lib/std/STD.STANDARD lib/ieee/IEEE.STD_LOGIC_1164

