# Generated by nvc 1.19-devel

lib/ieee.19/IEEE.FIXED_FLOAT_TYPES: $(top_srcdir)/lib/ieee.08/fixed_float_types.vhdl lib/std.19/STD.STANDARD

lib/ieee.19/IEEE.FIXED_GENERIC_PKG-body: $(top_srcdir)/lib/ieee.08/fixed_generic_pkg-body.vhdl lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_1164 lib/ieee.19/IEEE.NUMERIC_STD lib/ieee.19/IEEE.MATH_REAL lib/ieee.19/IEEE.FIXED_GENERIC_PKG lib/ieee.19/IEEE.FIXED_FLOAT_TYPES

lib/ieee.19/IEEE.FIXED_GENERIC_PKG: $(top_srcdir)/lib/ieee.08/fixed_generic_pkg.vhdl lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_1164 lib/ieee.19/IEEE.NUMERIC_STD lib/ieee.19/IEEE.FIXED_FLOAT_TYPES

lib/ieee.19/IEEE.FIXED_PKG: $(top_srcdir)/lib/ieee.08/fixed_pkg.vhdl lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_1164 lib/ieee.19/IEEE.NUMERIC_STD lib/ieee.19/IEEE.FIXED_GENERIC_PKG-body lib/ieee.19/IEEE.FIXED_GENERIC_PKG lib/ieee.19/IEEE.FIXED_FLOAT_TYPES

lib/ieee.19/IEEE.FLOAT_GENERIC_PKG-body: $(top_srcdir)/lib/ieee.08/float_generic_pkg-body.vhdl lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_1164 lib/ieee.19/IEEE.NUMERIC_STD lib/ieee.19/IEEE.FLOAT_GENERIC_PKG lib/ieee.19/IEEE.FIXED_GENERIC_PKG lib/ieee.19/IEEE.FIXED_FLOAT_TYPES

lib/ieee.19/IEEE.FLOAT_GENERIC_PKG: $(top_srcdir)/lib/ieee.08/float_generic_pkg.vhdl lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_1164 lib/ieee.19/IEEE.NUMERIC_STD lib/ieee.19/IEEE.FIXED_GENERIC_PKG lib/ieee.19/IEEE.FIXED_FLOAT_TYPES

lib/ieee.19/IEEE.FLOAT_PKG: $(top_srcdir)/lib/ieee.08/float_pkg.vhdl lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_1164 lib/ieee.19/IEEE.NUMERIC_STD lib/ieee.19/IEEE.FLOAT_GENERIC_PKG-body lib/ieee.19/IEEE.FLOAT_GENERIC_PKG lib/ieee.19/IEEE.FIXED_PKG lib/ieee.19/IEEE.FIXED_GENERIC_PKG lib/ieee.19/IEEE.FIXED_FLOAT_TYPES

lib/ieee.19/IEEE.IEEE_BIT_CONTEXT: $(top_srcdir)/lib/ieee.08/ieee_bit_context.vhdl lib/std.19/STD.STANDARD lib/ieee.19/IEEE.NUMERIC_BIT

lib/ieee.19/IEEE.IEEE_STD_CONTEXT: $(top_srcdir)/lib/ieee.08/ieee_std_context.vhdl lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_1164 lib/ieee.19/IEEE.NUMERIC_STD

lib/ieee.19/IEEE.NUMERIC_BIT-body: $(top_srcdir)/lib/ieee.08/numeric_bit-body.vhdl lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD lib/nvc.19/NVC.SIM_PKG lib/ieee.19/IEEE.NUMERIC_BIT

lib/ieee.19/IEEE.NUMERIC_BIT: $(top_srcdir)/lib/ieee.08/numeric_bit.vhdl lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD

lib/ieee.19/IEEE.NUMERIC_BIT_UNSIGNED-body: $(top_srcdir)/lib/ieee.08/numeric_bit_unsigned-body.vhdl lib/std.19/STD.STANDARD lib/ieee.19/IEEE.NUMERIC_BIT_UNSIGNED lib/ieee.19/IEEE.NUMERIC_BIT

lib/ieee.19/IEEE.NUMERIC_BIT_UNSIGNED: $(top_srcdir)/lib/ieee.08/numeric_bit_unsigned.vhdl lib/std.19/STD.STANDARD

lib/ieee.19/IEEE.NUMERIC_STD-body: $(top_srcdir)/lib/ieee.08/numeric_std-body.vhdl lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD lib/nvc.19/NVC.SIM_PKG lib/ieee.19/IEEE.STD_LOGIC_1164 lib/ieee.19/IEEE.NUMERIC_STD

lib/ieee.19/IEEE.NUMERIC_STD: $(top_srcdir)/lib/ieee.08/numeric_std.vhdl lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_1164

lib/ieee.19/IEEE.NUMERIC_STD_UNSIGNED-body: $(top_srcdir)/lib/ieee.08/numeric_std_unsigned-body.vhdl lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_1164 lib/ieee.19/IEEE.NUMERIC_STD_UNSIGNED lib/ieee.19/IEEE.NUMERIC_STD

lib/ieee.19/IEEE.NUMERIC_STD_UNSIGNED: $(top_srcdir)/lib/ieee.08/numeric_std_unsigned.vhdl lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_1164

lib/ieee.19/IEEE.STD_LOGIC_1164-body: $(top_srcdir)/lib/ieee.08/std_logic_1164-body.vhdl lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_1164

lib/ieee.19/IEEE.STD_LOGIC_1164: $(top_srcdir)/lib/ieee.08/std_logic_1164.vhdl lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD

lib/ieee.19/IEEE.STD_LOGIC_TEXTIO: $(top_srcdir)/lib/ieee.08/std_logic_textio.vhdl lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_1164

lib/ieee.19/IEEE.MATH_COMPLEX-body: $(top_srcdir)/lib/ieee/math_complex-body.vhdl lib/std.19/STD.STANDARD lib/ieee.19/IEEE.MATH_REAL lib/ieee.19/IEEE.MATH_COMPLEX

lib/ieee.19/IEEE.MATH_COMPLEX: $(top_srcdir)/lib/ieee/math_complex.vhdl lib/std.19/STD.STANDARD lib/ieee.19/IEEE.MATH_REAL

lib/ieee.19/IEEE.MATH_REAL-body: $(top_srcdir)/lib/ieee/math_real-body.vhdl lib/std.19/STD.STANDARD lib/ieee.19/IEEE.MATH_REAL

lib/ieee.19/IEEE.MATH_REAL: $(top_srcdir)/lib/ieee/math_real.vhdl lib/std.19/STD.STANDARD

lib/ieee.19/IEEE.STD_LOGIC_ARITH-body: $(top_srcdir)/lib/synopsys/std_logic_arith.vhd lib/std.19/STD.STANDARD lib/nvc.19/NVC.SIM_PKG lib/ieee.19/IEEE.STD_LOGIC_1164

lib/ieee.19/IEEE.STD_LOGIC_ARITH: $(top_srcdir)/lib/synopsys/std_logic_arith.vhd lib/std.19/STD.STANDARD lib/nvc.19/NVC.SIM_PKG lib/ieee.19/IEEE.STD_LOGIC_1164

lib/ieee.19/IEEE.STD_LOGIC_MISC-body: $(top_srcdir)/lib/synopsys/std_logic_misc.vhd lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_1164

lib/ieee.19/IEEE.STD_LOGIC_MISC: $(top_srcdir)/lib/synopsys/std_logic_misc.vhd lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_1164

lib/ieee.19/IEEE.STD_LOGIC_SIGNED-body: $(top_srcdir)/lib/synopsys/std_logic_signed.vhd lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_ARITH lib/ieee.19/IEEE.STD_LOGIC_1164

lib/ieee.19/IEEE.STD_LOGIC_SIGNED: $(top_srcdir)/lib/synopsys/std_logic_signed.vhd lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_ARITH lib/ieee.19/IEEE.STD_LOGIC_1164

lib/ieee.19/IEEE.STD_LOGIC_UNSIGNED-body: $(top_srcdir)/lib/synopsys/std_logic_unsigned.vhd lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_ARITH lib/ieee.19/IEEE.STD_LOGIC_1164

lib/ieee.19/IEEE.STD_LOGIC_UNSIGNED: $(top_srcdir)/lib/synopsys/std_logic_unsigned.vhd lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_ARITH lib/ieee.19/IEEE.STD_LOGIC_1164

lib/ieee.19/IEEE.VITAL_MEMORY-body: $(top_srcdir)/lib/vital/memory_b.vhdl lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD lib/ieee.19/IEEE.VITAL_TIMING lib/ieee.19/IEEE.VITAL_PRIMITIVES lib/ieee.19/IEEE.VITAL_MEMORY lib/ieee.19/IEEE.STD_LOGIC_1164

lib/ieee.19/IEEE.VITAL_MEMORY: $(top_srcdir)/lib/vital/memory_p.vhdl lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD lib/ieee.19/IEEE.VITAL_TIMING lib/ieee.19/IEEE.VITAL_PRIMITIVES lib/ieee.19/IEEE.STD_LOGIC_1164

lib/ieee.19/IEEE.VITAL_PRIMITIVES-body: $(top_srcdir)/lib/vital/prmtvs_b.vhdl lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD lib/ieee.19/IEEE.VITAL_TIMING lib/ieee.19/IEEE.VITAL_PRIMITIVES lib/ieee.19/IEEE.STD_LOGIC_1164

lib/ieee.19/IEEE.VITAL_PRIMITIVES: $(top_srcdir)/lib/vital/prmtvs_p.vhdl lib/std.19/STD.STANDARD lib/ieee.19/IEEE.VITAL_TIMING lib/ieee.19/IEEE.STD_LOGIC_1164

lib/ieee.19/IEEE.VITAL_TIMING-body: $(top_srcdir)/lib/vital/timing_b.vhdl lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD lib/ieee.19/IEEE.VITAL_TIMING lib/ieee.19/IEEE.STD_LOGIC_1164

lib/ieee.19/IEEE.VITAL_TIMING: $(top_srcdir)/lib/vital/timing_p.vhdl lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_1164

