# Generated by nvc 1.8-devel

lib/ieee.19/IEEE.FIXED_FLOAT_TYPES: lib/std.19/STD.STANDARD $(top_srcdir)/lib/ieee.08/fixed_float_types.vhdl

lib/ieee.19/IEEE.FIXED_GENERIC_PKG-body: lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_1164 lib/ieee.19/IEEE.NUMERIC_STD lib/ieee.19/IEEE.MATH_REAL lib/ieee.19/IEEE.FIXED_GENERIC_PKG lib/ieee.19/IEEE.FIXED_FLOAT_TYPES $(top_srcdir)/lib/ieee.08/fixed_generic_pkg-body.vhdl

lib/ieee.19/IEEE.FIXED_GENERIC_PKG: lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_1164 lib/ieee.19/IEEE.NUMERIC_STD lib/ieee.19/IEEE.FIXED_FLOAT_TYPES $(top_srcdir)/lib/ieee.08/fixed_generic_pkg.vhdl

lib/ieee.19/IEEE.FIXED_PKG: lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_1164 lib/ieee.19/IEEE.NUMERIC_STD lib/ieee.19/IEEE.FIXED_GENERIC_PKG-body lib/ieee.19/IEEE.FIXED_GENERIC_PKG lib/ieee.19/IEEE.FIXED_FLOAT_TYPES $(top_srcdir)/lib/ieee.08/fixed_pkg.vhdl

lib/ieee.19/IEEE.FLOAT_GENERIC_PKG-body: lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_1164 lib/ieee.19/IEEE.NUMERIC_STD lib/ieee.19/IEEE.FLOAT_GENERIC_PKG lib/ieee.19/IEEE.FIXED_GENERIC_PKG lib/ieee.19/IEEE.FIXED_FLOAT_TYPES $(top_srcdir)/lib/ieee.08/float_generic_pkg-body.vhdl

lib/ieee.19/IEEE.FLOAT_GENERIC_PKG: lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_1164 lib/ieee.19/IEEE.NUMERIC_STD lib/ieee.19/IEEE.FIXED_GENERIC_PKG lib/ieee.19/IEEE.FIXED_FLOAT_TYPES $(top_srcdir)/lib/ieee.08/float_generic_pkg.vhdl

lib/ieee.19/IEEE.FLOAT_PKG: lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_1164 lib/ieee.19/IEEE.NUMERIC_STD lib/ieee.19/IEEE.FLOAT_GENERIC_PKG-body lib/ieee.19/IEEE.FLOAT_GENERIC_PKG lib/ieee.19/IEEE.FIXED_PKG lib/ieee.19/IEEE.FIXED_GENERIC_PKG lib/ieee.19/IEEE.FIXED_FLOAT_TYPES $(top_srcdir)/lib/ieee.08/float_pkg.vhdl

lib/ieee.19/IEEE.IEEE_BIT_CONTEXT: lib/std.19/STD.STANDARD lib/ieee.19/IEEE.NUMERIC_BIT $(top_srcdir)/lib/ieee.08/ieee_bit_context.vhdl

lib/ieee.19/IEEE.IEEE_STD_CONTEXT: lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_1164 lib/ieee.19/IEEE.NUMERIC_STD $(top_srcdir)/lib/ieee.08/ieee_std_context.vhdl

lib/ieee.19/IEEE.NUMERIC_BIT-body: lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD lib/nvc.19/NVC.SIM_PKG lib/ieee.19/IEEE.NUMERIC_BIT $(top_srcdir)/lib/ieee.08/numeric_bit-body.vhdl

lib/ieee.19/IEEE.NUMERIC_BIT: lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD $(top_srcdir)/lib/ieee.08/numeric_bit.vhdl

lib/ieee.19/IEEE.NUMERIC_BIT_UNSIGNED-body: lib/std.19/STD.STANDARD lib/ieee.19/IEEE.NUMERIC_BIT_UNSIGNED lib/ieee.19/IEEE.NUMERIC_BIT $(top_srcdir)/lib/ieee.08/numeric_bit_unsigned-body.vhdl

lib/ieee.19/IEEE.NUMERIC_BIT_UNSIGNED: lib/std.19/STD.STANDARD $(top_srcdir)/lib/ieee.08/numeric_bit_unsigned.vhdl

lib/ieee.19/IEEE.NUMERIC_STD-body: lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD lib/nvc.19/NVC.SIM_PKG lib/ieee.19/IEEE.STD_LOGIC_1164 lib/ieee.19/IEEE.NUMERIC_STD $(top_srcdir)/lib/ieee.08/numeric_std-body.vhdl

lib/ieee.19/IEEE.NUMERIC_STD: lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee.08/numeric_std.vhdl

lib/ieee.19/IEEE.NUMERIC_STD_UNSIGNED-body: lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_1164 lib/ieee.19/IEEE.NUMERIC_STD_UNSIGNED lib/ieee.19/IEEE.NUMERIC_STD $(top_srcdir)/lib/ieee.08/numeric_std_unsigned-body.vhdl

lib/ieee.19/IEEE.NUMERIC_STD_UNSIGNED: lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee.08/numeric_std_unsigned.vhdl

lib/ieee.19/IEEE.STD_LOGIC_1164-body: lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee.08/std_logic_1164-body.vhdl

lib/ieee.19/IEEE.STD_LOGIC_1164: lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD $(top_srcdir)/lib/ieee.08/std_logic_1164.vhdl

lib/ieee.19/IEEE.STD_LOGIC_TEXTIO: lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD lib/ieee.19/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee.08/std_logic_textio.vhdl

lib/ieee.19/IEEE.MATH_COMPLEX-body: lib/std.19/STD.STANDARD lib/ieee.19/IEEE.MATH_REAL lib/ieee.19/IEEE.MATH_COMPLEX $(top_srcdir)/lib/ieee/math_complex-body.vhdl

lib/ieee.19/IEEE.MATH_COMPLEX: lib/std.19/STD.STANDARD lib/ieee.19/IEEE.MATH_REAL $(top_srcdir)/lib/ieee/math_complex.vhdl

lib/ieee.19/IEEE.MATH_REAL-body: lib/std.19/STD.STANDARD lib/ieee.19/IEEE.MATH_REAL $(top_srcdir)/lib/ieee/math_real-body.vhdl

lib/ieee.19/IEEE.MATH_REAL: lib/std.19/STD.STANDARD $(top_srcdir)/lib/ieee/math_real.vhdl

