# Generated by nvc 1.11-devel

lib/std.19/STD.ENV-body: lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD lib/std.19/STD.ENV lib/nvc.19/NVC.TEXT_UTIL $(top_srcdir)/lib/std.19/env-body.vhd

lib/std.19/STD.ENV: lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD $(top_srcdir)/lib/std.19/env.vhdl

lib/std.19/STD.REFLECTION-body: lib/std.19/STD.STANDARD lib/std.19/STD.REFLECTION $(top_srcdir)/lib/std.19/reflection-body.vhd

lib/std.19/STD.REFLECTION: lib/std.19/STD.STANDARD $(top_srcdir)/lib/std.19/reflection.vhdl

lib/std.19/STD.STANDARD: $(top_srcdir)/lib/std.19/standard.vhd

lib/std.19/STD.TEXTIO: lib/std.19/STD.STANDARD $(top_srcdir)/lib/std.19/textio.vhdl

lib/std.19/STD.TEXTIO-body: lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD lib/std.19/STD.ENV $(top_srcdir)/lib/std/textio-body.vhd

