# Generated by nvc 1.8-devel

lib/std.19/STD.STANDARD: $(top_srcdir)/lib/std.08/standard.vhd

lib/std.19/STD.TEXTIO: lib/std.19/STD.STANDARD $(top_srcdir)/lib/std.19/textio.vhdl

lib/std.19/STD.TEXTIO-body: lib/std.19/STD.TEXTIO lib/std.19/STD.STANDARD $(top_srcdir)/lib/std/textio-body.vhd

