# Generated by nvc 1.6-devel

lib/ieee.08/IEEE.NUMERIC_BIT-body: lib/nvc/NVC.SIM_PKG lib/std.08/STD.STANDARD lib/ieee.08/IEEE.NUMERIC_BIT $(top_srcdir)/lib/ieee.08/numeric_bit-body.vhdl

lib/ieee.08/_IEEE.NUMERIC_BIT.so: lib/nvc/NVC.SIM_PKG lib/std.08/STD.STANDARD lib/ieee.08/IEEE.NUMERIC_BIT $(top_srcdir)/lib/ieee.08/numeric_bit-body.vhdl

lib/ieee.08/_IEEE.NUMERIC_BIT.vcode: lib/nvc/NVC.SIM_PKG lib/std.08/STD.STANDARD lib/ieee.08/IEEE.NUMERIC_BIT $(top_srcdir)/lib/ieee.08/numeric_bit-body.vhdl

lib/ieee.08/IEEE.NUMERIC_BIT: lib/std.08/STD.TEXTIO lib/std.08/STD.STANDARD $(top_srcdir)/lib/ieee.08/numeric_bit.vhdl

lib/ieee.08/IEEE.NUMERIC_BIT_UNSIGNED-body: lib/ieee.08/IEEE.NUMERIC_BIT lib/std.08/STD.STANDARD lib/ieee.08/IEEE.NUMERIC_BIT_UNSIGNED $(top_srcdir)/lib/ieee.08/numeric_bit_unsigned-body.vhdl

lib/ieee.08/_IEEE.NUMERIC_BIT_UNSIGNED.so: lib/ieee.08/IEEE.NUMERIC_BIT lib/std.08/STD.STANDARD lib/ieee.08/IEEE.NUMERIC_BIT_UNSIGNED $(top_srcdir)/lib/ieee.08/numeric_bit_unsigned-body.vhdl

lib/ieee.08/_IEEE.NUMERIC_BIT_UNSIGNED.vcode: lib/ieee.08/IEEE.NUMERIC_BIT lib/std.08/STD.STANDARD lib/ieee.08/IEEE.NUMERIC_BIT_UNSIGNED $(top_srcdir)/lib/ieee.08/numeric_bit_unsigned-body.vhdl

lib/ieee.08/IEEE.NUMERIC_BIT_UNSIGNED: lib/std.08/STD.STANDARD $(top_srcdir)/lib/ieee.08/numeric_bit_unsigned.vhdl

lib/ieee.08/IEEE.NUMERIC_STD-body: lib/nvc/NVC.SIM_PKG lib/std.08/STD.STANDARD lib/ieee.08/IEEE.NUMERIC_STD $(top_srcdir)/lib/ieee.08/numeric_std-body.vhdl

lib/ieee.08/_IEEE.NUMERIC_STD.so: lib/nvc/NVC.SIM_PKG lib/std.08/STD.STANDARD lib/ieee.08/IEEE.NUMERIC_STD $(top_srcdir)/lib/ieee.08/numeric_std-body.vhdl

lib/ieee.08/_IEEE.NUMERIC_STD.vcode: lib/nvc/NVC.SIM_PKG lib/std.08/STD.STANDARD lib/ieee.08/IEEE.NUMERIC_STD $(top_srcdir)/lib/ieee.08/numeric_std-body.vhdl

lib/ieee.08/IEEE.NUMERIC_STD: lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.TEXTIO lib/std.08/STD.STANDARD $(top_srcdir)/lib/ieee.08/numeric_std.vhdl

lib/ieee.08/IEEE.NUMERIC_STD_UNSIGNED-body: lib/ieee.08/IEEE.NUMERIC_STD lib/std.08/STD.STANDARD lib/ieee.08/IEEE.NUMERIC_STD_UNSIGNED $(top_srcdir)/lib/ieee.08/numeric_std_unsigned-body.vhdl

lib/ieee.08/_IEEE.NUMERIC_STD_UNSIGNED.so: lib/ieee.08/IEEE.NUMERIC_STD lib/std.08/STD.STANDARD lib/ieee.08/IEEE.NUMERIC_STD_UNSIGNED $(top_srcdir)/lib/ieee.08/numeric_std_unsigned-body.vhdl

lib/ieee.08/_IEEE.NUMERIC_STD_UNSIGNED.vcode: lib/ieee.08/IEEE.NUMERIC_STD lib/std.08/STD.STANDARD lib/ieee.08/IEEE.NUMERIC_STD_UNSIGNED $(top_srcdir)/lib/ieee.08/numeric_std_unsigned-body.vhdl

lib/ieee.08/IEEE.NUMERIC_STD_UNSIGNED: lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.STANDARD $(top_srcdir)/lib/ieee.08/numeric_std_unsigned.vhdl

lib/ieee.08/IEEE.STD_LOGIC_1164-body: lib/std.08/STD.STANDARD lib/ieee.08/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee.08/std_logic_1164-body.vhdl

lib/ieee.08/_IEEE.STD_LOGIC_1164.so: lib/std.08/STD.STANDARD lib/ieee.08/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee.08/std_logic_1164-body.vhdl

lib/ieee.08/_IEEE.STD_LOGIC_1164.vcode: lib/std.08/STD.STANDARD lib/ieee.08/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee.08/std_logic_1164-body.vhdl

lib/ieee.08/IEEE.STD_LOGIC_1164: lib/std.08/STD.TEXTIO lib/std.08/STD.STANDARD $(top_srcdir)/lib/ieee.08/std_logic_1164.vhdl

lib/ieee.08/IEEE.STD_LOGIC_TEXTIO: lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.TEXTIO lib/std.08/STD.STANDARD $(top_srcdir)/lib/ieee.08/std_logic_textio.vhdl

lib/ieee.08/_IEEE.STD_LOGIC_TEXTIO.so: lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.TEXTIO lib/std.08/STD.STANDARD $(top_srcdir)/lib/ieee.08/std_logic_textio.vhdl

lib/ieee.08/_IEEE.STD_LOGIC_TEXTIO.vcode: lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.TEXTIO lib/std.08/STD.STANDARD $(top_srcdir)/lib/ieee.08/std_logic_textio.vhdl

lib/ieee.08/IEEE.MATH_COMPLEX-body: lib/ieee.08/IEEE.MATH_REAL lib/std.08/STD.STANDARD lib/ieee.08/IEEE.MATH_COMPLEX $(top_srcdir)/lib/ieee/math_complex-body.vhdl

lib/ieee.08/_IEEE.MATH_COMPLEX.so: lib/ieee.08/IEEE.MATH_REAL lib/std.08/STD.STANDARD lib/ieee.08/IEEE.MATH_COMPLEX $(top_srcdir)/lib/ieee/math_complex-body.vhdl

lib/ieee.08/_IEEE.MATH_COMPLEX.vcode: lib/ieee.08/IEEE.MATH_REAL lib/std.08/STD.STANDARD lib/ieee.08/IEEE.MATH_COMPLEX $(top_srcdir)/lib/ieee/math_complex-body.vhdl

lib/ieee.08/IEEE.MATH_COMPLEX: lib/ieee.08/IEEE.MATH_REAL lib/std.08/STD.STANDARD $(top_srcdir)/lib/ieee/math_complex.vhdl

lib/ieee.08/IEEE.MATH_REAL-body: lib/std.08/STD.STANDARD lib/ieee.08/IEEE.MATH_REAL $(top_srcdir)/lib/ieee/math_real-body.vhdl

lib/ieee.08/_IEEE.MATH_REAL.so: lib/std.08/STD.STANDARD lib/ieee.08/IEEE.MATH_REAL $(top_srcdir)/lib/ieee/math_real-body.vhdl

lib/ieee.08/_IEEE.MATH_REAL.vcode: lib/std.08/STD.STANDARD lib/ieee.08/IEEE.MATH_REAL $(top_srcdir)/lib/ieee/math_real-body.vhdl

lib/ieee.08/IEEE.MATH_REAL: lib/std.08/STD.STANDARD $(top_srcdir)/lib/ieee/math_real.vhdl

lib/ieee.08/IEEE.STD_LOGIC_ARITH-body: lib/nvc/NVC.SIM_PKG lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.STANDARD $(top_srcdir)/lib/synopsys/std_logic_arith.vhd

lib/ieee.08/_IEEE.STD_LOGIC_ARITH.so: lib/nvc/NVC.SIM_PKG lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.STANDARD $(top_srcdir)/lib/synopsys/std_logic_arith.vhd

lib/ieee.08/_IEEE.STD_LOGIC_ARITH.vcode: lib/nvc/NVC.SIM_PKG lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.STANDARD $(top_srcdir)/lib/synopsys/std_logic_arith.vhd

lib/ieee.08/IEEE.STD_LOGIC_ARITH: lib/nvc/NVC.SIM_PKG lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.STANDARD $(top_srcdir)/lib/synopsys/std_logic_arith.vhd

lib/ieee.08/IEEE.STD_LOGIC_SIGNED-body: lib/ieee.08/IEEE.STD_LOGIC_ARITH lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.STANDARD $(top_srcdir)/lib/synopsys/std_logic_signed.vhd

lib/ieee.08/_IEEE.STD_LOGIC_SIGNED.so: lib/ieee.08/IEEE.STD_LOGIC_ARITH lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.STANDARD $(top_srcdir)/lib/synopsys/std_logic_signed.vhd

lib/ieee.08/_IEEE.STD_LOGIC_SIGNED.vcode: lib/ieee.08/IEEE.STD_LOGIC_ARITH lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.STANDARD $(top_srcdir)/lib/synopsys/std_logic_signed.vhd

lib/ieee.08/IEEE.STD_LOGIC_SIGNED: lib/ieee.08/IEEE.STD_LOGIC_ARITH lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.STANDARD $(top_srcdir)/lib/synopsys/std_logic_signed.vhd

lib/ieee.08/IEEE.STD_LOGIC_UNSIGNED-body: lib/ieee.08/IEEE.STD_LOGIC_ARITH lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.STANDARD $(top_srcdir)/lib/synopsys/std_logic_unsigned.vhd

lib/ieee.08/_IEEE.STD_LOGIC_UNSIGNED.so: lib/ieee.08/IEEE.STD_LOGIC_ARITH lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.STANDARD $(top_srcdir)/lib/synopsys/std_logic_unsigned.vhd

lib/ieee.08/_IEEE.STD_LOGIC_UNSIGNED.vcode: lib/ieee.08/IEEE.STD_LOGIC_ARITH lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.STANDARD $(top_srcdir)/lib/synopsys/std_logic_unsigned.vhd

lib/ieee.08/IEEE.STD_LOGIC_UNSIGNED: lib/ieee.08/IEEE.STD_LOGIC_ARITH lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.STANDARD $(top_srcdir)/lib/synopsys/std_logic_unsigned.vhd

