# Generated by nvc 1.7-devel

lib/ieee.08/IEEE.FIXED_FLOAT_TYPES: lib/std.08/STD.STANDARD $(top_srcdir)/lib/ieee.08/fixed_float_types.vhdl

lib/ieee.08/IEEE.FIXED_GENERIC_PKG-body: lib/std.08/STD.TEXTIO lib/ieee.08/IEEE.MATH_REAL lib/ieee.08/IEEE.FIXED_FLOAT_TYPES lib/ieee.08/IEEE.NUMERIC_STD lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.STANDARD lib/ieee.08/IEEE.FIXED_GENERIC_PKG $(top_srcdir)/lib/ieee.08/fixed_generic_pkg-body.vhdl

lib/ieee.08/IEEE.FIXED_GENERIC_PKG: lib/std.08/STD.TEXTIO lib/ieee.08/IEEE.NUMERIC_STD lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.STANDARD lib/ieee.08/IEEE.FIXED_FLOAT_TYPES $(top_srcdir)/lib/ieee.08/fixed_generic_pkg.vhdl

lib/ieee.08/IEEE.FIXED_PKG: lib/std.08/STD.TEXTIO lib/ieee.08/IEEE.STD_LOGIC_1164 lib/ieee.08/IEEE.FIXED_GENERIC_PKG lib/ieee.08/IEEE.NUMERIC_STD lib/std.08/STD.STANDARD lib/ieee.08/IEEE.FIXED_GENERIC_PKG-body lib/ieee.08/IEEE.FIXED_FLOAT_TYPES $(top_srcdir)/lib/ieee.08/fixed_pkg.vhdl

lib/ieee.08/IEEE.FLOAT_GENERIC_PKG-body: lib/std.08/STD.TEXTIO lib/ieee.08/IEEE.FIXED_GENERIC_PKG lib/ieee.08/IEEE.FIXED_FLOAT_TYPES lib/ieee.08/IEEE.NUMERIC_STD lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.STANDARD lib/ieee.08/IEEE.FLOAT_GENERIC_PKG $(top_srcdir)/lib/ieee.08/float_generic_pkg-body.vhdl

lib/ieee.08/IEEE.FLOAT_GENERIC_PKG: lib/std.08/STD.TEXTIO lib/ieee.08/IEEE.FIXED_GENERIC_PKG lib/ieee.08/IEEE.NUMERIC_STD lib/ieee.08/IEEE.STD_LOGIC_1164 lib/ieee.08/IEEE.FIXED_FLOAT_TYPES lib/std.08/STD.STANDARD $(top_srcdir)/lib/ieee.08/float_generic_pkg.vhdl

lib/ieee.08/IEEE.FLOAT_PKG: lib/ieee.08/IEEE.FIXED_PKG lib/std.08/STD.TEXTIO lib/ieee.08/IEEE.FIXED_GENERIC_PKG lib/ieee.08/IEEE.NUMERIC_STD lib/std.08/STD.STANDARD lib/ieee.08/IEEE.FLOAT_GENERIC_PKG lib/ieee.08/IEEE.STD_LOGIC_1164 lib/ieee.08/IEEE.FLOAT_GENERIC_PKG-body lib/ieee.08/IEEE.FIXED_FLOAT_TYPES $(top_srcdir)/lib/ieee.08/float_pkg.vhdl

lib/ieee.08/IEEE.NUMERIC_BIT-body: lib/std.08/STD.TEXTIO lib/nvc.08/NVC.SIM_PKG lib/std.08/STD.STANDARD lib/ieee.08/IEEE.NUMERIC_BIT $(top_srcdir)/lib/ieee.08/numeric_bit-body.vhdl

lib/ieee.08/IEEE.NUMERIC_BIT: lib/std.08/STD.TEXTIO lib/std.08/STD.STANDARD $(top_srcdir)/lib/ieee.08/numeric_bit.vhdl

lib/ieee.08/IEEE.NUMERIC_BIT_UNSIGNED-body: lib/ieee.08/IEEE.NUMERIC_BIT lib/std.08/STD.STANDARD lib/ieee.08/IEEE.NUMERIC_BIT_UNSIGNED $(top_srcdir)/lib/ieee.08/numeric_bit_unsigned-body.vhdl

lib/ieee.08/IEEE.NUMERIC_BIT_UNSIGNED: lib/std.08/STD.STANDARD $(top_srcdir)/lib/ieee.08/numeric_bit_unsigned.vhdl

lib/ieee.08/IEEE.NUMERIC_STD-body: lib/std.08/STD.TEXTIO lib/nvc.08/NVC.SIM_PKG lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.STANDARD lib/ieee.08/IEEE.NUMERIC_STD $(top_srcdir)/lib/ieee.08/numeric_std-body.vhdl

lib/ieee.08/IEEE.NUMERIC_STD: lib/std.08/STD.TEXTIO lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.STANDARD $(top_srcdir)/lib/ieee.08/numeric_std.vhdl

lib/ieee.08/IEEE.NUMERIC_STD_UNSIGNED-body: lib/std.08/STD.STANDARD lib/ieee.08/IEEE.NUMERIC_STD lib/ieee.08/IEEE.STD_LOGIC_1164 lib/ieee.08/IEEE.NUMERIC_STD_UNSIGNED $(top_srcdir)/lib/ieee.08/numeric_std_unsigned-body.vhdl

lib/ieee.08/IEEE.NUMERIC_STD_UNSIGNED: lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.STANDARD $(top_srcdir)/lib/ieee.08/numeric_std_unsigned.vhdl

lib/ieee.08/IEEE.STD_LOGIC_1164-body: lib/std.08/STD.TEXTIO lib/std.08/STD.STANDARD lib/ieee.08/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee.08/std_logic_1164-body.vhdl

lib/ieee.08/IEEE.STD_LOGIC_1164: lib/std.08/STD.TEXTIO lib/std.08/STD.STANDARD $(top_srcdir)/lib/ieee.08/std_logic_1164.vhdl

lib/ieee.08/IEEE.STD_LOGIC_TEXTIO: lib/std.08/STD.STANDARD lib/std.08/STD.TEXTIO lib/ieee.08/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee.08/std_logic_textio.vhdl

lib/ieee.08/IEEE.MATH_COMPLEX-body: lib/ieee.08/IEEE.MATH_REAL lib/std.08/STD.STANDARD lib/ieee.08/IEEE.MATH_COMPLEX $(top_srcdir)/lib/ieee/math_complex-body.vhdl

lib/ieee.08/IEEE.MATH_COMPLEX: lib/ieee.08/IEEE.MATH_REAL lib/std.08/STD.STANDARD $(top_srcdir)/lib/ieee/math_complex.vhdl

lib/ieee.08/IEEE.MATH_REAL-body: lib/std.08/STD.STANDARD lib/ieee.08/IEEE.MATH_REAL $(top_srcdir)/lib/ieee/math_real-body.vhdl

lib/ieee.08/IEEE.MATH_REAL: lib/std.08/STD.STANDARD $(top_srcdir)/lib/ieee/math_real.vhdl

lib/ieee.08/IEEE.STD_LOGIC_ARITH-body: lib/nvc.08/NVC.SIM_PKG lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.STANDARD $(top_srcdir)/lib/synopsys/std_logic_arith.vhd

lib/ieee.08/IEEE.STD_LOGIC_ARITH: lib/nvc.08/NVC.SIM_PKG lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.STANDARD $(top_srcdir)/lib/synopsys/std_logic_arith.vhd

lib/ieee.08/IEEE.STD_LOGIC_SIGNED-body: lib/ieee.08/IEEE.STD_LOGIC_ARITH lib/std.08/STD.STANDARD lib/ieee.08/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/synopsys/std_logic_signed.vhd

lib/ieee.08/IEEE.STD_LOGIC_SIGNED: lib/ieee.08/IEEE.STD_LOGIC_ARITH lib/std.08/STD.STANDARD lib/ieee.08/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/synopsys/std_logic_signed.vhd

lib/ieee.08/IEEE.STD_LOGIC_UNSIGNED-body: lib/ieee.08/IEEE.STD_LOGIC_ARITH lib/std.08/STD.STANDARD lib/ieee.08/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/synopsys/std_logic_unsigned.vhd

lib/ieee.08/IEEE.STD_LOGIC_UNSIGNED: lib/ieee.08/IEEE.STD_LOGIC_ARITH lib/std.08/STD.STANDARD lib/ieee.08/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/synopsys/std_logic_unsigned.vhd

lib/ieee.08/IEEE.VITAL_MEMORY-body: lib/ieee.08/IEEE.VITAL_TIMING lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.TEXTIO lib/std.08/STD.STANDARD lib/ieee.08/IEEE.VITAL_MEMORY $(top_srcdir)/lib/vital/memory_b.vhdl

lib/ieee.08/IEEE.VITAL_MEMORY: lib/ieee.08/IEEE.VITAL_TIMING lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.STANDARD $(top_srcdir)/lib/vital/memory_p.vhdl

lib/ieee.08/IEEE.VITAL_PRIMITIVES-body: lib/std.08/STD.TEXTIO lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.STANDARD lib/ieee.08/IEEE.VITAL_TIMING lib/ieee.08/IEEE.VITAL_PRIMITIVES $(top_srcdir)/lib/vital/prmtvs_b.vhdl

lib/ieee.08/IEEE.VITAL_PRIMITIVES: lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.STANDARD lib/ieee.08/IEEE.VITAL_TIMING $(top_srcdir)/lib/vital/prmtvs_p.vhdl

lib/ieee.08/IEEE.VITAL_TIMING-body: lib/std.08/STD.TEXTIO lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.STANDARD lib/ieee.08/IEEE.VITAL_TIMING $(top_srcdir)/lib/vital/timing_b.vhdl

lib/ieee.08/IEEE.VITAL_TIMING: lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.STANDARD $(top_srcdir)/lib/vital/timing_p.vhdl

