# Generated by nvc 1.6-devel

lib/ieee.08/IEEE.STD_LOGIC_1164-body: lib/std.08/STD.STANDARD lib/ieee.08/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee.08/std_logic_1164-body.vhdl

lib/ieee.08/_IEEE.STD_LOGIC_1164-body.a: lib/std.08/STD.STANDARD lib/ieee.08/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee.08/std_logic_1164-body.vhdl

lib/ieee.08/_IEEE.STD_LOGIC_1164-body.so: lib/std.08/STD.STANDARD lib/ieee.08/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee.08/std_logic_1164-body.vhdl

lib/ieee.08/_IEEE.STD_LOGIC_1164-body.vcode: lib/std.08/STD.STANDARD lib/ieee.08/IEEE.STD_LOGIC_1164 $(top_srcdir)/lib/ieee.08/std_logic_1164-body.vhdl

lib/ieee.08/IEEE.STD_LOGIC_1164: lib/std.08/STD.TEXTIO lib/std.08/STD.STANDARD $(top_srcdir)/lib/ieee.08/std_logic_1164.vhdl

lib/ieee.08/IEEE.NUMERIC_STD: lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.TEXTIO lib/std.08/STD.STANDARD $(top_srcdir)/lib/ieee.08/numeric_std.vhdl

lib/ieee.08/_IEEE.NUMERIC_STD.a: lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.TEXTIO lib/std.08/STD.STANDARD $(top_srcdir)/lib/ieee.08/numeric_std.vhdl

lib/ieee.08/_IEEE.NUMERIC_STD.so: lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.TEXTIO lib/std.08/STD.STANDARD $(top_srcdir)/lib/ieee.08/numeric_std.vhdl

lib/ieee.08/_IEEE.NUMERIC_STD.vcode: lib/ieee.08/IEEE.STD_LOGIC_1164 lib/std.08/STD.TEXTIO lib/std.08/STD.STANDARD $(top_srcdir)/lib/ieee.08/numeric_std.vhdl

lib/ieee.08/IEEE.NUMERIC_BIT: lib/std.08/STD.TEXTIO lib/std.08/STD.STANDARD $(top_srcdir)/lib/ieee.08/numeric_bit.vhdl

lib/ieee.08/_IEEE.NUMERIC_BIT.a: lib/std.08/STD.TEXTIO lib/std.08/STD.STANDARD $(top_srcdir)/lib/ieee.08/numeric_bit.vhdl

lib/ieee.08/_IEEE.NUMERIC_BIT.so: lib/std.08/STD.TEXTIO lib/std.08/STD.STANDARD $(top_srcdir)/lib/ieee.08/numeric_bit.vhdl

lib/ieee.08/_IEEE.NUMERIC_BIT.vcode: lib/std.08/STD.TEXTIO lib/std.08/STD.STANDARD $(top_srcdir)/lib/ieee.08/numeric_bit.vhdl

