# Generated by nvc 0.1

std/STD.ENV-body std/_STD.ENV-body.a std/_STD.ENV-body.so std/_STD.ENV-body.bc std/STD.ENV: $(top_srcdir)/lib/nvc/env.vhd

std/STD.STANDARD: $(top_srcdir)/lib/std/standard.vhd

std/STD.TEXTIO std/_STD.TEXTIO.a std/_STD.TEXTIO.so std/_STD.TEXTIO.bc std/STD.TEXTIO-body std/_STD.TEXTIO-body.a std/_STD.TEXTIO-body.so std/_STD.TEXTIO-body.bc: $(top_srcdir)/lib/std/textio.vhd

