# Generated by nvc 1.6-devel

lib/synopsys/SYNOPSYS.ATTRIBUTES: lib/std/STD.STANDARD $(top_srcdir)/lib/synopsys/attributes.vhd

lib/synopsys/_SYNOPSYS.ATTRIBUTES.so: lib/std/STD.STANDARD $(top_srcdir)/lib/synopsys/attributes.vhd

lib/synopsys/_SYNOPSYS.ATTRIBUTES.vcode: lib/std/STD.STANDARD $(top_srcdir)/lib/synopsys/attributes.vhd

