# Generated by nvc 0.1

../ieee/ieee/IEEE.STD_LOGIC_TEXTIO-body ../ieee/ieee/_IEEE.STD_LOGIC_TEXTIO-body.so ../ieee/ieee/_IEEE.STD_LOGIC_TEXTIO-body.bc ../ieee/ieee/IEEE.STD_LOGIC_TEXTIO: ../ieee/ieee/IEEE.STD_LOGIC_1164 ../../../lib/synopsys/std_logic_textio.vhd

../ieee/ieee/IEEE.STD_LOGIC_SIGNED-body ../ieee/ieee/_IEEE.STD_LOGIC_SIGNED-body.so ../ieee/ieee/_IEEE.STD_LOGIC_SIGNED-body.bc ../ieee/ieee/IEEE.STD_LOGIC_SIGNED: ../ieee/ieee/IEEE.STD_LOGIC_1164 ../ieee/ieee/IEEE.STD_LOGIC_ARITH ../../../lib/synopsys/std_logic_signed.vhd

../ieee/ieee/IEEE.VITAL_MEMORY: ../ieee/ieee/IEEE.STD_LOGIC_1164 ../ieee/ieee/IEEE.VITAL_TIMING ../ieee/ieee/IEEE.VITAL_PRIMITIVES ../../../lib/ieee/memory_p.vhdl

../ieee/ieee/IEEE.VITAL_PRIMITIVES ../ieee/ieee/_IEEE.VITAL_PRIMITIVES.so ../ieee/ieee/_IEEE.VITAL_PRIMITIVES.bc: ../ieee/ieee/IEEE.STD_LOGIC_1164 ../ieee/ieee/IEEE.VITAL_TIMING ../../../lib/ieee/prmtvs_p.vhdl

../ieee/ieee/IEEE.VITAL_TIMING ../ieee/ieee/_IEEE.VITAL_TIMING.so ../ieee/ieee/_IEEE.VITAL_TIMING.bc: ../ieee/ieee/IEEE.STD_LOGIC_1164 ../../../lib/ieee/timing_p.vhdl

../ieee/ieee/IEEE.MATH_REAL ../ieee/ieee/_IEEE.MATH_REAL.so ../ieee/ieee/_IEEE.MATH_REAL.bc: ../../../lib/ieee/math_real.vhdl

../ieee/ieee/IEEE.NUMERIC_STD-body ../ieee/ieee/_IEEE.NUMERIC_STD-body.so ../ieee/ieee/_IEEE.NUMERIC_STD-body.bc: ../ieee/ieee/IEEE.NUMERIC_STD ../../../lib/ieee/numeric_std-body.vhdl

../ieee/ieee/IEEE.NUMERIC_STD ../ieee/ieee/_IEEE.NUMERIC_STD.so ../ieee/ieee/_IEEE.NUMERIC_STD.bc: ../ieee/ieee/IEEE.STD_LOGIC_1164 ../../../lib/ieee/numeric_std.vhdl

../ieee/ieee/IEEE.NUMERIC_BIT ../ieee/ieee/_IEEE.NUMERIC_BIT.so ../ieee/ieee/_IEEE.NUMERIC_BIT.bc: ../../../lib/ieee/numeric_bit.vhdl

../ieee/ieee/IEEE.STD_LOGIC_1164-body ../ieee/ieee/_IEEE.STD_LOGIC_1164-body.so ../ieee/ieee/_IEEE.STD_LOGIC_1164-body.bc: ../ieee/ieee/IEEE.STD_LOGIC_1164 ../../../lib/ieee/std_logic_1164-body.vhdl

../ieee/ieee/IEEE.NUMERIC_BIT-body ../ieee/ieee/_IEEE.NUMERIC_BIT-body.so ../ieee/ieee/_IEEE.NUMERIC_BIT-body.bc: ../ieee/ieee/IEEE.NUMERIC_BIT ../../../lib/ieee/numeric_bit-body.vhdl

../ieee/ieee/IEEE.MATH_REAL-body ../ieee/ieee/_IEEE.MATH_REAL-body.so ../ieee/ieee/_IEEE.MATH_REAL-body.bc: ../ieee/ieee/IEEE.MATH_REAL ../../../lib/ieee/math_real-body.vhdl

../ieee/ieee/IEEE.VITAL_TIMING-body ../ieee/ieee/_IEEE.VITAL_TIMING-body.so ../ieee/ieee/_IEEE.VITAL_TIMING-body.bc: ../ieee/ieee/IEEE.VITAL_TIMING ../../../lib/ieee/timing_b.vhdl

../ieee/ieee/IEEE.VITAL_PRIMITIVES-body ../ieee/ieee/_IEEE.VITAL_PRIMITIVES-body.so ../ieee/ieee/_IEEE.VITAL_PRIMITIVES-body.bc: ../ieee/ieee/IEEE.VITAL_PRIMITIVES ../../../lib/ieee/prmtvs_b.vhdl

../ieee/ieee/IEEE.STD_LOGIC_1164: ../../../lib/ieee/std_logic_1164.vhdl

../ieee/ieee/IEEE.STD_LOGIC_ARITH-body ../ieee/ieee/_IEEE.STD_LOGIC_ARITH-body.so ../ieee/ieee/_IEEE.STD_LOGIC_ARITH-body.bc ../ieee/ieee/IEEE.STD_LOGIC_ARITH: ../ieee/ieee/IEEE.STD_LOGIC_1164 ../../../lib/synopsys/std_logic_arith.vhd

../ieee/ieee/IEEE.STD_LOGIC_UNSIGNED ../ieee/ieee/IEEE.STD_LOGIC_UNSIGNED-body ../ieee/ieee/_IEEE.STD_LOGIC_UNSIGNED-body.so ../ieee/ieee/_IEEE.STD_LOGIC_UNSIGNED-body.bc: ../ieee/ieee/IEEE.STD_LOGIC_1164 ../ieee/ieee/IEEE.STD_LOGIC_ARITH ../../../lib/synopsys/std_logic_unsigned.vhd

