name: Test LLVM releases

on:
  workflow_dispatch:
  schedule:
    - cron: '30 21 * * 1'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ubuntu:
    strategy:
      matrix:
        include:
          - { llvm: 13 }
          - { llvm: 15 }
          - { llvm: 17 }
          - { llvm: 18 }
          - { llvm: 19 }
          - { llvm: 20 }
    name: LLVM ${{ matrix.llvm }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nickg/nvc-ubuntu-builder:22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install LLVM
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh ${{ matrix.llvm }}
      - name: Generate configure script
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          ./autogen.sh
      - name: Configure
        run: |
          mkdir build && cd build
          ../configure --with-llvm=/usr/bin/llvm-config --enable-debug \
             --with-llvm=/usr/bin/llvm-config-${{ matrix.llvm }}
      - name: Build
        run: make -C build -j $(nproc)
      - name: Check version
        run: ./build/bin/nvc --version
      - name: Test
        run: |
          export NVC_JIT_ASYNC=0
          export NVC_JIT_THRESHOLD=1
          make -C build check
